### PR TITLE
[NETBEANS-1074] Module Review php.phing

### PR DESCRIPTION
**Pull request by junichi11**
- Change the license headers of Bundle.properties and build.xml

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I strongly disagree with removing the license header and not replacing it with the ALv2 one. It was argued, that "people" are scared by license headers even if they are as liberal as the ALv2 one. But in this case the license header is already present and till this day was not a problem, so I'd argue, don't go down the "exception" route, but just replace the GPL/CDDL header in the template file with a ALv2 one. As this is a freemarker template, it won't be present in the generated file, just in the template.

**Comment by junichi11** [comment]
Yes, I understand that(actually, a generated file does not have it.), but if we don't remove it, it gets into the situation that some template files have the license header, the others don't have it. I don't think this is good... I think we should unify that. Probably, we discussed this in the 1st donation. The reason was "user visible", maybe. OK, I'll ask about this via the mailing list.

**Comment by matthiasblaesing** [comment]
It was discussed and never resolved - so my way was to not change the status quo. Removing the header, although it was not a problem for several year just cements one opinion.

**Comment by junichi11** [comment]
I sent it: https://lists.apache.org/thread.html/4be2dfa83506f69525828e12f8f3e44fbf5175efa8fcdb5110021be9@%3Cdev.netbeans.apache.org%3E

If anyone else does not have objections, I'll just change it ;)

**Comment by geertjanw** [comment]
Can this be merged?

**Comment by junichi11** [comment]
I'll change the license header. so please waite a while.

**Comment by junichi11** [comment]
Fixed.

**Pull request merged**
