### PR TITLE
Activate enterprise cluster and disable modules with incompatible licenses

### PR DESCRIPTION
**Pull request by matthiasblaesing**
PR #1098 activates the enterprise cluster. There are however modules,
that have dependencies on incompatible license (wildfly + jboss LGPL,
weblogic 9 commercial, wsit OASIS license). PR #1101 removes some,
but skips wildfly (it is indicated, that red hat might be willing to relax
licensing for the DTDs/XSDs).

In the current state however the module does not qualify and thus is
disabled.

The enterprise cluster also includes some libraries, that need either
adjustment to use common dependencies or adjustments in the build
system to tollerate duplicate libraries.

This PR merges the work from #1098, #1101 and adds the described
pieces. In combination this should let the travis builds succeed.

Please do not squash this, I'll merge myself, when reviewed.

Closes: #1098 
Closes: #1101

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I'm looking into the build failures.

**Comment by matthiasblaesing** [comment]
Thank you both for checking - lets see how the fallout will look.

**Comment by geertjanw** [comment]
I've unzipped the latest build that includes the enterprise cluster. Something isn't working quite right with the enablement, i.e., when clicking Next in 'Java Web' or 'Java EE' in the New Project dialog, to enable the feature, the 'Finding Feature' dialog appears and messages of 'Not all requested modules can be installed' appears, starting with org.netbeans.modules.web.primefaces.

**Comment by matthiasblaesing** [comment]
Yes I see, it can be reproduced locally to. However, manually enabling JavaEE in the plugin manager correctly enabled the feature and then the error is gone. It would be great if some one with a bit more experience in the black magic of automatic feature enablement (is that ergonomics?) could have a look.

**Comment by matthiasblaesing** [comment]
Update: please clear the userdir. I ran `ant tryme` after I removed `nbbuild/testuserdir/`. After that I'm correctly asked do "Download and activate" the feature.

**Comment by geertjanw** [comment]
I can still reproduce it, though I started by downloading the ZIP from the artifacts on Jenkins, then ran with a fresh user directory, and can still see the same problem.

**Comment by geertjanw** [comment]
Definitely was a network issue of some kind, VPN, etc.

**Pull request merged**
