### PR TITLE
NETBEANS-109 fix server generation

### PR DESCRIPTION
**Pull request by ebarboni**
add test
fix related javadoc

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Could you please check the completeness of this PR? You mention that you added a test, but there is no test.

**Comment by ebarboni** [comment]
test added sorry for that

**Comment by matthiasblaesing** [comment]
In general this looks good. My personal preference for the commit message is a short explanation/reasoning for the change, that way a reader can deduce from the commit log why a change was introduced. I suggest to adjust that.

The test looks to be modeled following the existing tests and so the structure is generally ok. A comment, that applies to the existing and new tests is, that relying on a specific formatting is IMHO dangerous, using an XML parser and checking the DOM would give a more stable test (this is just an observation and no request for a change). One thing, that should be removed are the superfluous imports.

**Comment by ebarboni** [comment]
tried to ajust the commit message.  (maybe I can comment more on jira; )

is it possible to get a link to jira according to the issue number ?

I keep the test the way they was done. Only want to fix this issue for now. Will wait until licence check over to put effort on refactor/coverage...

**Comment by matthiasblaesing** [comment]
I reworded the commit message a bit and merged it into master. Thank you!

**Pull request closed without merging**
