### PR TITLE
Attempt to load PNG for legacy GIFs

### PR DESCRIPTION
**Pull request by sdedic**
I have a branding problem :) because I'd like to brand NB application (icon, maybe splash) with a PNG image (because of alpha channel support), but the platform codebase looks for a GIF.

There are several approaches; I don't want to rename the resource in platform, as that would surely break someone else's branding set up for .gif image. One possibility is to publish a PNG disguised with .gif extension - the existing code would attempt to read it using auto-detection, so it would succeed by detecting PNG (despite the extension).

But I would rather propose a change that attempts to first read a .png for .gif resources. PNG is the recommended format anyway. The change will double the number of `Classloader.getResource` calls - but the result will be cached under the originally requested name, so no (much) harm should be done at least not long-term.

I originally thought that I'd make PNG as fallback for (missing) GIFs, but that would not work well for branding, which just adds resources, but cannot remove them.

Simple measurement counters show that on startup, extra 1450 `getResource()` calls are made, total 123ms

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
-1 for me. PNGs with a GIF extension already work. All mine are like that. I'd rather see us support pluggable branding providers so that all sorts of loaders could be supported (eg. SVG, icon fonts, etc.) than tinker around the edges of this, particularly if it slows things down.

**Comment by neilcsmith-net** [comment]
@sdedic sorry, a complicated sounding way of describing something quite simple :smile:  I mean that putting further logic in to resolve a path to an image hard-coded in this class is wrong IMO.  The dark LAF stuff is horrible!  A better approach would be to allow people to register a provider to override the resolution of -

```
public static final Image loadImage(String resource, boolean localized)
```
That way we can not only support what you're trying to do here, but people can develop modules for high-res icons, icon fonts, svg, icon themes, etc. too.

And yes, probably better on the mailing list!

**Comment by Chris2011** [comment]
It depends, but for gif there is no reason nowadays to use it anymore. No transparency (Only 1 or 0, but not in between), less colors, etc. So PNG is the better choice, as you can see it for the SplashScreen (https://issues.apache.org/jira/browse/NETBEANS-1444).

It would be nice if we can handle SVG as icons too, that would be a big enhancement. But this is another topic.

**Comment by Chris2011** [comment]
And if we can have a performance impact at the startup, that would be also great.

**Comment by Chris2011** [comment]
Why was this closed?

**Comment by neilcsmith-net** [comment]
@Chris2011 well, it doesn't solve the problem you think it does, as you can already use PNG in place of any GIF. You sure the splashscreen is actually a GIF?!  And while I agree with @sdedic that hiding PNG as GIF is a horrible hack, it doesn't seem worth having a negative performance impact to fix it?!

SVG would be great, but ideally requires being able to plugin in to the image resolution code - let's talk on mailing list, because I would love to work on this.

**Comment by Chris2011** [comment]
Ok, but afaik, there was some exception after using a PNG or a GIF, instead of another format. I think it should be similar. SVG would be great but someone said, that this is not possible with normal Swing AFAIK.

Anyway, what I thought is to change everything where it makes sense (maybe 80-90%) to PNG instead of using GIF. And AFAIK yes the splashscreen is GIF instead of PNG, this is why the quality is a bit poor. But I'm not 100% sure, @geertjanw asked for the GIF for the SplashScreen and for a PNG for the about dialog or vice versa. can't remember it exactly.

**Comment by Chris2011** [comment]
And yes should be discussed on the mailing list :).

**Comment by Chris2011** [comment]
Only to let you know, I created a ticket for the Splashscreen: https://issues.apache.org/jira/browse/NETBEANS-1444

**Pull request closed without merging**
