### PR TITLE
Backport of jtulach's fixes made after Apr 22, 2017

### PR DESCRIPTION
**Pull request by JaroslavTulach**
As you may know the development in http://hg.netbeans.org repositories continued even after Sat Apr 22 (the day when Apache donation files were synced for the last time). The development wasn't very active, but there was some.

I've made four commits since then. I'd like to backport them to Apache NetBeans repository as they fix real issues found in NetBeans. Please consider accepting my pull request.

### CODE REVIEW

**Comment by geertjanw** [comment]
Awesome!

**Comment by JaroslavTulach** [comment]
I've got these changesets by using following steps. I cloned @emilianbold [repository](https://github.com/emilianbold/netbeans-releases/) and then I executed:
```bash
netbeans-releases$ git log -r NB9_FF...emilian/master --no-merges  --author=jtulach --format=%H
bf9a5b8befa55723fc35c6c5cb1b72e176d4973e
0ce716155e4cfeab3dc1b840c78d0c620dca0c41
9ee3e285e758bbb1be1be129cfc053eb79cc1e77
42b544f1c1a06b597fef1a47df6052bbfad5bf0d
```
then I manually (as I have just four commits) did `git show $id` in Emilian's repository and then `patch -p1`  and `git commit` with copied message from the original commit in this repository.

**Comment by JaroslavTulach** [comment]
I'd be thankful if somebody else from the community could take a look and merge my changes. I don't think it is correct to merge myself.

**Comment by geertjanw** [comment]
Everyone agrees that Apache NetBeans should be in line with NetBeans that is in Oracle hg. This code has been reviewed. No one had complained. I will wait 24 hours and then merge, unless anyone raises an objecton, and any other Apache NetBeans committer is invited to merge this instead if me as well.

**Pull request merged**
