### PR TITLE
[NETBEANS-1252] Fix shifted cursor in output window with GDK_SCALE=2

### PR DESCRIPTION
**Pull request by hlavki**
Remove ExtPlainView methods viewToModel() & modelToView() and use those from parent.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
The change itself looks sane. The removed implementation looks like a direct copy from the JDK implementation, so switching to the JDKs default implementation is sane.

I'd like you do adjust the commit though:
- the summary (first) line of the commit should hold the referenced issue in brackets as first element
- as the name suggests the first line should give a summary of the change (why was it done)
- then an empty line should follow
- the rest of the message should give a reasoning for the change

In this case:

```
[NETBEANS-1252] Fix shifted cursor in output window with GDK_SCALE=2

Remove custom implementation of #viewToModel and# modelToView methods, ....
```

You can update the message by amending the commit and doing a force push of the branch the PR is based on.

A final comment: You introduced changes not directly related to the fix (whitespace removal + constant introduction). They are sane, but in general that should not be done. (in this case keep it, as I already looked through it).

**Comment by matthiasblaesing** [comment]
@hlavki you reacted with a thumbs up - just to be sure - are you planning on updating the commit message?

**Comment by matthiasblaesing** [comment]
There is not the redo the PR. This sequence works:
- switch your working copy to the branch NETBEANS-1252
- run `git commit --amend`
- update the commit message
- do a force push `git push -f` to update the remote branch

The `amend` option allows you to change the last commit you made. You don't want to make further file changes, but it also allows you to change the commit message.

The force push is necessary as normally a remote head can't be changed/removed and your push will require that.

When the push is done, the PR will reflect the state of the latest state of the NETBEANS-1252 branch.

**Comment by lkishalmi** [comment]
Changes are looks fine tested on Ubuntu non HiDPI as well it works Ok.
Shall we merge this one?

**Comment by hlavki** [comment]
@matthiasblaesing, done. thanks for hint.

**Comment by hlavki** [comment]
@lkishalmi  don't know for whom this question is, but I think there is no problem to merge this.

**Pull request merged**
