### PR TITLE
NETBEANS-134 wip attempt to get ignore from .gitgnore

### PR DESCRIPTION
**Pull request by ebarboni**
ant task to build patternset from gitignore file. Try to reduce false positive.

### CODE REVIEW

**Comment by jlahoda** [comment]
Seems good to me. I was thinking of introducing a new fileset(/patternset) that would set-up itself from .gitignore, but this is good as well.

**Comment by ebarboni** [comment]
I tried to map gitignore to exclude pattern first. But the pattern /*/external/*/** for example has not simple mapping in ant fileset. it was ignoring everything on external instead of ignoring every thing in subfolder from external.

So I change my mind to get ignore from git directly

**Comment by ebarboni** [comment]
connect to NETBEANS-134

**Comment by geertjanw** [comment]
Makes sense to me. Anything to block the merge of this one?

**Comment by geertjanw** [comment]
What is the usage for this, i.e., if this is merged, what does one need to do/when/where is something needed to be done to use this?

**Comment by ebarboni** [comment]
it generate an exlusion list based on git. 
This list of excluded file  is added to the "normal" ant rat task with no interference with the human made list.
Nothing to be done to make it work (except having git)

**Comment by matthiasblaesing** [comment]
Having git on the PATH sounds like a dangerous assumption. We had a similar problem for patching. Linux users normally have patch on the path, so the author did not recognice, that this could be a problem. At the end we replaced the patch binary with a java solution, it would not be good to regress here.

**Comment by ebarboni** [comment]
RatReportTask is build using the same assumption of having the version control tool available with "no issue so far". Mercurial related task were done this way in nbbuild ant task.  

IMHO, the change to a java based version control stuff need to be done for all task in one  go.

**Comment by matthiasblaesing** [comment]
Sorry - I did not notice, that RatReportTask introduced that already. Nonetheless currently the rat report is clean without this change. There was  a generial "*/build/**" entry, but there are subprojects in the tree, that were not covered by this. With a recent changeset this was changed to "**/build/**".

The only remaining offending entries are from the hibernate module, for which the license is just not compatible with ALv2 (LGPL only).

I suggest to close this.

**Pull request closed without merging**
