### PR TITLE
[NETBEANS-1074] Module Review websvc.restlib

### PR DESCRIPTION
**Pull request by vikasprabhakar**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
- These files are CDDL-1.1 or GPL-v2-CPE (choose CDDL-1.1 for the project, see MANIFEST of the files, that is the link for the 1.1 variant of the CDDL):
jersey-server-2.5.1.jar
jersey-media-moxy-2.5.1.jar
jersey-entity-filtering-2.5.1.jar
jersey-container-servlet-core-2.5.1.jar
jersey-container-servlet-2.5.1.jar
jersey-common-2.5.1.jar
jersey-client-2.5.1.jar
hk2-utils-2.2.0-b21.jar
hk2-locator-2.2.0-b21.jar
hk2-api-2.2.0-b21.jar

- This file is not pure CDDL-1.0 - according to the MANIFEST it is CDDL1.1-GPLv2-CPE. And in addition it requires attribution - the ASM License is 3 clause BSD: https://asm.ow2.io/license.html
asm-all-repackaged-2.2.0-b21.jar

- According to the LICENSE file in `cglib-2.2.0-b21.jar` the file is ALv2 licensed.

- javax.annotation-api-1.2.jar is present in the zip you are replacing, but not present it the new binaries-list.

**Comment by vikasprabhakar** [comment]
> * These files are CDDL-1.1 or GPL-v2-CPE (choose CDDL-1.1 for the project, see MANIFEST of the files, that is the link for the 1.1 variant of the CDDL):
>   jersey-server-2.5.1.jar
>   jersey-media-moxy-2.5.1.jar
>   jersey-entity-filtering-2.5.1.jar
>   jersey-container-servlet-core-2.5.1.jar
>   jersey-container-servlet-2.5.1.jar
>   jersey-common-2.5.1.jar
>   jersey-client-2.5.1.jar
>   hk2-utils-2.2.0-b21.jar
>   hk2-locator-2.2.0-b21.jar
>   hk2-api-2.2.0-b21.jar
--> Licenses are changed to CDDL-1.1

> * This file is not pure CDDL-1.0 - according to the MANIFEST it is CDDL1.1-GPLv2-CPE. And in addition it requires attribution - the ASM License is 3 clause BSD: https://asm.ow2.io/license.html
>   asm-all-repackaged-2.2.0-b21.jar
--> A new license (CDDL-1.1-ASM) in nbbuild/licenses and same is updated in asm-all-repackaged-2.2.0-b21-license.txt file

> * According to the LICENSE file in `cglib-2.2.0-b21.jar` the file is ALv2 licensed.
--> Maven license path https://mvnrepository.com/artifact/org.glassfish.hk2.external/cglib/2.2.0-b21
It has CDDL GPL 1.1 GPL 2.0 license. should it be CDDL 1.1 or ALv2?
> * javax.annotation-api-1.2.jar is present in the zip you are replacing, but not present it the new binaries-list.
-->Got message "enterprise/websvc.restlib/external/javax.annotation-api-1.2.jar and java/maven.indexer/external/javax.annotation-api-1.2.jar are identical" while running the command ant -Dcluster.config=full verify-libs-and-licenses . Can we kept the same jar in two different module?

**Comment by rtaneja1** [comment]
>>Got message "enterprise/websvc.restlib/external/javax.annotation-api-1.2.jar and java/maven.indexer/external/javax.annotation-api-1.2.jar are identical" while running the command ant -Dcluster.config=full verify-libs-and-licenses . Can we kept the same jar in two different module?

You need to update ignored-overlaps files for this
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps

**Comment by vikasprabhakar** [comment]
> > > Got message "enterprise/websvc.restlib/external/javax.annotation-api-1.2.jar and java/maven.indexer/external/javax.annotation-api-1.2.jar are identical" while running the command ant -Dcluster.config=full verify-libs-and-licenses . Can we kept the same jar in two different module?
> 
> You need to update ignored-overlaps files for this
> nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps

Changes are added

**Comment by matthiasblaesing** [comment]
For cglib: The jar contains a LICENSE file, that is in line with the information from the cglib project itself (both are ALv2). I don't know where 

https://mvnrepository.com/artifact/org.glassfish.hk2.external/cglib/2.2.0-b21

gets its info from. But there is exactly one file that qualifies for CDDL/GPL licenseing and that is the pom.xml. So for me this package is ALv2. If the pom.xml is considered as copyrightable, the whole jar would need a special license file to cover both choosen licenses (CDDL+ALv2).

**Comment by vikasprabhakar** [comment]
> For cglib: The jar contains a LICENSE file, that is in line with the information from the cglib project itself (both are ALv2). I don't know where
> 
> https://mvnrepository.com/artifact/org.glassfish.hk2.external/cglib/2.2.0-b21
> 
> gets its info from. But there is exactly one file that qualifies for CDDL/GPL licenseing and that is the pom.xml. So for me this package is ALv2. If the pom.xml is considered as copyrightable, the whole jar would need a special license file to cover both choosen licenses (CDDL+ALv2).

License "CDDL+ALv2" added  for cglib-2.2.0-b21 jar

**Comment by matthiasblaesing** [comment]
Thank you - merging.

**Pull request merged**
