### PR TITLE
properties for by module report

### PR DESCRIPTION
**Pull request by ebarboni**
Hi this is a little modification to allow rat target to report only one folder at a time. I was puzzled by the size of full rat report.

Usage example:
ant rat -Dmodule=uihandler 

default ant rat is working like before

Regards

### CODE REVIEW

**Comment by geertjanw** [comment]
Very cool!

**Comment by svenreimers** [comment]
Awesome +1

**Comment by mklaehn** [comment]
great +1

**Comment by emilianbold** [comment]
The file doesn't seem formatted properly (`<property` and `<rat` look off by 1 space) but other than that it's nice.

**Comment by mklaehn** [comment]
If we're onthe topic of formatting then there's also 
1. the issue of the empty inserted lines and
1. the issue of the use TAB character in the line with the added property.

**Comment by ebarboni** [comment]
I'm enhancing my skill on rebase :p, hope its ok now

**Comment by emilianbold** [comment]
I don't believe you are rebasing correctly. You shouldn't see something like:

>jlahoda committed with ebarboni 8 days ago

**Comment by ebarboni** [comment]
@emilianbold  , I sorry was trying to resync but this PR is on my master branch so I go back to a usable state.

**Comment by matthiasblaesing** [comment]
This change introduces a problem: exclude patterns can't be defined per module anymore. @jlahoda introduced the fist such set `form/test/unit/data/goldenfiles/*` and I'll need to do the same for `diff` module, where the test data needs to be excluded. With this change, the exclude won't work.

**Comment by ebarboni** [comment]
closing this PR. Do not want to add false positive to the rat report

**Pull request closed without merging**
