### PR TITLE
[NETBEANS-54] Module Review lib.terminalemulator

### PR DESCRIPTION
**Pull request by vieiro**
- Added Apache license to different files.
  - genfiles.properties, build-impl.xml and manifest.mf files to be handled centrally.
  - No other licensing issues found.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
There are a few files were you added the ALv2 at the end of the file. As most license scanners expect it at the top, it would be good to retain that assumption. So could you update these files accordingly?

If you need a short form of the license, it is available: http://www.apache.org/legal/src-headers.html#is-a-short-form-of-the-source-header-available

**Comment by vieiro** [comment]
Definitely, expect this whithin 24-48h from now. Sorry & thanks for the link.

**Comment by vieiro** [comment]
Should be ready now.

**Comment by matthiasblaesing** [comment]
Nice work.

**Pull request merged**
