### PR TITLE
Maven first in New Project Wizard

### PR DESCRIPTION
**Pull request by dukescript**
There's a [discussion in the netbeans-dev mailing list ](https://lists.apache.org/thread.html/e0c9493f19fd291590180ac1cbb304ee556b1812b0229cfb12cac9a0@%3Cdev.netbeans.apache.org%3E)about changing the layout of the "New project" wizard. 

Currently the "Java" Category creates an ANT-based project. As ANT is old and only few projects use it, this Category should use Maven. This can be done by simply rearranging the projects a bit, mostly via branding.

### CODE REVIEW

**Comment by dukescript** [comment]
bildschirmfoto 2018-11-25 um 15 37 13
bildschirmfoto 2018-11-25 um 15 38 39

**Comment by matthiasblaesing** [comment]
Not sure this was intentionally closed, but could we please not go down the "Ant(ic)" route? It is not funny. People choose ant for a reason and you don't need to belittle them.

**Comment by dukescript** [comment]
Thanks for the comment, I was in a hurry to get on the road and accidentally closed it. 

Agreed, I can change the name tomorrow morning, what would you suggest?

**Comment by dukescript** [comment]
I updated the PR with a more agreeable categrory name: bildschirmfoto 2018-11-26 um 12 09 28

**Comment by Chris2011** [comment]
The original/current names in the wizard are Java and Maven, why not now Java Maven and Java Ant? So everyone knows on the very first view what is meant here.

Followed the discussion, future wish could be only using Java maybe with sub categories or wizard enhancements. But for now I would prefer to see Java Maven and Java Ant, IMHO.

**Comment by dukescript** [comment]
First I thought, it's only a small change, and I should do it, but actually I think the current naming is better, as it serves a purpose:

"Java Maven" and "Java Ant" does not really fix the problem of making Maven the default and "nudging" new developers to stay away from Ant. It only changes the visibility of Maven a little bit, and instead forces users to make a decision. 

Imagine a new developer who wants to create his first Java project. If we present him the options "Java" and "Java Ant", he'll very likely choose "Java", which would be great. If we present him with "Java Maven" and "Java Ant", he'll be lost and in the best case resort to google. Like Tim said on the mailing list, we force a user into a choice they don't (shouldn't) care about [For reference: Joel Spolsky's Blog Post](https://www.joelonsoftware.com/2000/04/12/choices/).

I'd prefer to keep the names like this, as a tool to point users in the right direction.

**Comment by matthiasblaesing** [comment]
I would concur with @Chris2011 and go with "Java Ant" and "Java Maven" or "Java (ant)" and "Java (maven)". If the label is not present and I want to create a maven project, I have to guess how to get there (you are hindering my experience in that case).

Yes, as a developer you have to know some terms and if you don't know them, you should better learn.

**Comment by matthiasblaesing** [comment]
If you don't say, that "Java" means "Maven" how should an experienced user know hat netbeans does when he clicks "Next"? You still ask the user to make a decision and then you hide the important information. So if I can choose between:

- Java
- Ant Java

how should I know which is the right one, given that I want to create a maven project? Behind "Java" everything could hide (gradle, maven, make, $newCoolBuildsystem).

For me (yes, I'm also a user) hiding the build system makes the situation worse.

**Comment by geertjanw** [comment]
Are we ready to merge this?

**Comment by JaroslavTulach** [comment]
Who's "are"?Me? Yes, I support merging.Toni? Ye.s.Community? Likely.Matthias? No.-jtOdesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: Geertjan Wielenga <notifications@github.com> Datum: 27.11.18  16:07  (GMT+01:00) Komu: apache/incubator-netbeans <incubator-netbeans@noreply.github.com> Cc: Jaroslav Tulach <jaroslav.tulach@oracle.com>, Review requested <review_requested@noreply.github.com> Předmět: Re: [apache/incubator-netbeans] Maven first in New Project Wizard (#1038) Are we ready to merge this?

—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-netbeans","title":"apache/incubator-netbeans","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-netbeans"}},"updates":{"snippets":[{"icon":"PERSON","message":"@geertjanw in #1038: Are we ready to merge this?"}],"action":{"name":"View Pull Request","url":"https://github.com/apache/incubator-netbeans/pull/1038#issuecomment-442091771"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-netbeans/pull/1038#issuecomment-442091771",
"url": "https://github.com/apache/incubator-netbeans/pull/1038#issuecomment-442091771",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-netbeans] Maven first in New Project Wizard (#1038)",
"sections": [
{
"text": "",
"activityTitle": "**Geertjan Wielenga**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@geertjanw",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-netbeans\",\n\"issueId\": 1038,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"apache/incubator-netbeans\",\n\"pullRequestId\": 1038\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-netbeans/pull/1038#issuecomment-442091771"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415723158\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by dukescript** [comment]
> If you don't say, that "Java" means "Maven" how should an experienced user know hat netbeans does when he clicks "Next"? 

Just like it worked for last 20 years: If you select a project, a description is displayed, which also says how this project is built. You can see that in the 2nd and 3rd screenshot "A simple Java Application using Maven."...

**Comment by jtulach** [comment]
Can this PR be merged now? Or is there someone who wants Toni to organize a vote on the mailing list?

My feeling is that there exists a majority that is either +1 or +0 on the "Maven 1st UI change" and this PR is good enough to begin our move towards that direction. A formal vote would of course verify/reject my feeling properly. 

Speakup if you want Toni to initiate such vote.

**Comment by matthiasblaesing** [comment]
There is always the option to cancel the PR and rethink. My opinion stands, I want our users to make informed decisions and that means he/she should know what he/she chooses. You plan to take away that information . For me this is a step back.

The quoted article [Joel on Software - Choices](https://www.joelonsoftware.com/2000/04/12/choices/) does not even apply here. It argues, that useless decisions should not be presented to the user, which this PR does not do, it leaves all options accessible. It explicitly does not state, that information should be hidden from the user, which hinders the decision process.

**Comment by jtulach** [comment]
Certainly not eligible for cherry picking into NetBeans 10. We need more time to stabilize and polish the change.

@matthiasblaesing and/or everyone else, please explicitly state you insist on a **vote**. Otherwise I'll push forward merging of this PR on the basis of lazy consensus.

**Comment by matthiasblaesing** [comment]
I don't insist on a vote, I want a better solution. I veto the merge of this PR.

**Comment by vieiro** [comment]
Hi all,

I have to agree with @matthiasblaesing and I think this deserves some further consideration/thought, preferably in the mailing list. Matthias is putting the user first, and that's my motto as well, so I have to agree with his veto.

Trying to be positive, I'd rather see a "Java" main section with the following options:

- Ant based project.
- Maven based project.

Also let's try to be positive about ant. Apache Ant is a companion project in the ASF and deserves our consideration. The fact that it's an "old technology" deserves a respect as well. Ant has served NetBeans well during many years, and we still depend on it to build our own food.

**Comment by eppleton** [comment]
@viero I think everyone here tries to put the user first. In my personal opinion, the PR does that, and the other solution would be confusing and bad for the user. You have a different opinion. That's OK and I respect that. But please don't assume that I don't care about usability. If you read my replies you should be able to see that my whole argument is about usability, and I'd be glad if you could respect that too, even if you don't agree.

@matthiasblaesing There was a "Java" category before, which defaulted to ANT, now it defaults to Maven. How is this a step back? It is a change of the default for Java, no more no less. And regarding the "Choices" blog, that Tim Boudreau mentioned on the mailing list: For a Java newbie it's exactly the same as the "optimize database" example in the blog: We ask the user for a decision he very likely doesn't care about and doesn't have enough information to make (What is ANT or Maven?). And for a more experienced user it's not hard to find the information, as it is in the description of the wizard.

**Comment by matthiasblaesing** [comment]
@eppleton the referenced article argues, to _not_ ask the user at all, if the developer should know better and the user can be expected not to care/know. We can't take that road, as there are different pros and cons to choose the build system and the option needs to be there. So the user needs to choose and needs information to base its decision on. Given that the difference between the two options is the build system I don't see why that fact should be hidden and why that would help the developer at all.

Before the the change there was:
- Java: An ant based project with netbeans specific project files
- Maven: A maven based project without any netbeans specifics

No we have:
- Java
- Ant Java

So what tells me what "Java" does? If my peer group says "gradle" is _the_ build system, I would expect that to be created. Bummer - does not happen - there is some file "pom.xml" generated, but no  "build.gradle". You can replace "gradle" with $featured build system. So why not:

- Java (maven based)
- Java (ant based)

Putting maven first, indicates to order "we" suggest and lets the user choose.

**Comment by vieiro** [comment]
@eppleton Oh, of course we all want the best for the user. Apologies for my bad explanation. I like best your proposal of explaining the build system "Java (ant based)" and "Java (maven based)".

**Comment by jtulach** [comment]
What shall be the next steps with this PR? Can those who object to current state (@matthiasblaesing, @vieiro) modify the PR so it is acceptable for them?

Btw. recently I was teaching my kids Java and found a [nice course that uses NetBeans](https://www.itnetwork.cz/java/zaklady/java-tutorial-instalace-a-ovladani-netbeans-ide-konzolova-aplikace)! Having courses like this is an excellent value that we don't want to loose. It has to be admitted that for existing materials like this, it is important to keep the Ant based projects around and _deprecate_ them _carefully_.

**Comment by geertjanw** [comment]
Since this is going to impact one of the very first steps in all of our tutorials, and could have an adverse effect on the starting point of each and every newbie of Apache NetBeans, I think we should together take a look at the impact of this on the documentation -- i.e., if someone can't do step 1 because they cannot find the project template described in step 1 of a tutorial, there's a real chance they'll not go to step 2 at all.

**Comment by geertjanw** [comment]
Here is where our documentation at Apache is found:

https://github.com/vieiro/incubator-netbeans-website/tree/feature/third-donation-tutorials/netbeans.apache.org/src/content/kb/docs

Here's the quick start, i.e., the starting point for most users, for example, though note some broken images:

https://github.com/vieiro/incubator-netbeans-website/blob/feature/third-donation-tutorials/netbeans.apache.org/src/content/kb/docs/java/quickstart.asciidoc

**Comment by vieiro** [comment]
I think @geertjanw has a good point. Let's polish our tutorials (http://netbeans.apache.org/kb/docs/java/quickstart.html, for instance) and then let's update the "New Project Wizard". Otherwise the users will be confused. 

Proposal: What about adding different new categories to the left of the wizard?

- Java (ant)
- Java (maven)
- Java (gradle)

...

**Comment by matthiasblaesing** [comment]
To answer the "put your work where your mouth is" request: I created:

https://github.com/matthiasblaesing/incubator-netbeans/tree/pr-1038-suggestion

That modifies this suggestion in the following way:
- switch from "Java" to "Java (Maven)"
- rename "Ant Java" to "Deprecated" (there will be other project types, that will move there)
- create a new subfolder under "Deprecated" for "Java (Ant)"
- move items from original "Ant Java" folder to "Java (Ant)"

Screenshot:
screenshot

This way:
- Maven based java projects are in clear favor (first entry in the project list)
- You can spot the project type directly from the category (true for ant and maven)
- Ant and Maven project types are marked in the same way
- project types we don't recommend anymore are moved to category well known to programmers (deprecated). It should be noted, that I consider dreprecated here as in "java.util.Date" deprecated  (everybody dislikes "java.util.Date", but it will probably stay around for a very long time)

This is a suggestion and should be taken as such.

**Comment by geertjanw** [comment]
Why is "NetBeans Modules" deprecated?

I'm not sure about the idea of a Deprecated folder, though I understand the intention behind it, maybe use "Legacy" instead?

**Comment by Chris2011** [comment]
-1 for the depcrecated or legacy stuff, because we don't want to remove ant at all. We should close this PR and should find a consens on the mailing list first. My proposal is similar to that what PHP and HTML5 does. so It should be consistent.

HTML5
 -> Choose Project type
 -> Last step is to choose the tools (Package.json, grulpfile, gruntfile, etc.)

PHP
 -> Choose Project type
 -> After some other steps choose the framework

So my proposal is this

Java
 -> Choose project type
 -> Next step or later choose your build/package pipeline (ant, maven, gradle, etc.)

NetBeans Module Development
 -> Choose project type
 -> Next step or later choose your build/package pipeline (ant, maven, gradle, etc.)


Cheers

Chris

**Comment by geertjanw** [comment]
I must admit I am very hesitant about it too. For anyone actually using Ant, it is not Deprecated or Legacy at all. Maybe instead -- until we have the full implementation similar to what Chris suggests -- we could have two folders, Recommended and Other, with Maven and PHP and NetBeans Modules in Recommended and Ant and JavaFX in Other? I think there's nothing wrong with recommending one approach over the other -- both in terms of our support of it as well as the direction in which the industry has gone over the past years.

**Comment by pdurbin** [comment]
Hi! @geertjanw posted an updated tutorial on the netbeans-users mailing list: https://lists.apache.org/thread.html/5c6a64062a3d4a4ce99264089a304bad23613b061a13ad436dc206eb@%3Cusers.netbeans.apache.org%3E

I was a little sad to see that Ant is still the default. If possible, the default should be Maven.

**Comment by geertjanw** [comment]
Some believe it is obvious that the default should be Maven, but it's not obvious to everybody, that's for sure. And even if Maven should be the default, what does that mean? That it is listed first? 

Ideally, we'd have one single Java project wizard, within which one can select whether one wants a Java SE project or a Java EE project, with a choice of Ant, Maven, or Gradle for the build system. But who is actually going to step forward and create this unified wizard?

**Comment by geertjanw** [comment]
I think I may have a very simple solution that everyone will probably agree with -- change the name of the Maven category to "Java with Maven", change the Gradle category to "Java with Gradle" and change the Java category to "Java with Ant". Then put all the template from "Java Web" and "Java EE" into the "Java with Ant" category.

**Comment by OndroMih** [comment]
I like @Chris2011 suggestion best but it would require some refactoring of the dialogues.

As an intermediary solution, maybe what @geertjanw suggested today is best, but I suggest making Java with Maven more prominent by grouping Java with Gradle and Java with Ant into a subcategory Java (other):

Java with Maven
Java (other)
-> Java with Gradle
-> Java with Ant
HTML5/JavaScript
PHP

This would simultaneously make it easier for newcomers to choose the proper dialog for their new project, make it explicit that Maven is used for the preferred projects and also make it easy to access other build systems for experienced programmers.

I think we should give Maven a prominent position Netbeans wants to make it the recommended and most supported build system.

**Comment by geertjanw** [comment]
hey @OndroMih, now you're going to make the Gradle people and Ant people upset. :-) I think the best and fairest we can do, without making various factions of the Java community run after us with flaming pitchforks, is to order them in a way that discriminates in favor of Maven, but that doesn't completely push the others under the carpet.

**Comment by Chris2011** [comment]
I'm also ok with the solution from geertjan, until we have a better solution for that and we will not loose it from our eyes. Maybe we should make a ticket for the other, better solution to not miss that.

**Comment by ggam** [comment]
That sounds pretty reasonable.

**Comment by gilbertoca** [comment]
> My proposal is similar to that what PHP and HTML5 does. so It should be consistent.
> 
> HTML5
> -> Choose Project type
> -> Last step is to choose the tools (Package.json, grulpfile, gruntfile, etc.)
> 
> PHP
> -> Choose Project type
> -> After some other steps choose the framework
> 
> So my proposal is this
> 
> Java
> -> Choose project type
> -> Next step or later choose your build/package pipeline (ant, maven, gradle, etc.)
> 
> NetBeans Module Development
> -> Choose project type
> -> Next step or later choose your build/package pipeline (ant, maven, gradle, etc.)
> 
> Cheers
> 
> Chris

This proposal is uniform and would remove any doubt about legacy discussion. Even better, it is open for new future build tool.

**Comment by Chris2011** [comment]
@gilbertoca I think the most (or some people) will agree with that solution and find it nice, but someone has to hook that topic up and change the current wizard to the new one. And to say that, it was my idea but I will not find time to do that, unfortunately.

**Comment by neilcsmith-net** [comment]
@gilbertoca that also assumes that each build system has the same project type requirements, and at the moment at least they don't overlap.  It may be a bit of work to try and make them overlap, and might be less understandable if they did (eg. what's the generic variant of `POM Project`?)

**Comment by gilbertoca** [comment]
> @gilbertoca that also assumes that each build system has the same project type requirements, and at the moment at least they don't overlap. 

@neilcsmith-net Do you think the idea is complex?
How they(each build) work today (they need or use any generic project type)? Each build system knows your own requirements, doesn't it?

@Chris2011 thank you! I understand and I can't help much right now (maybe testing).

**Comment by neilcsmith-net** [comment]
@gilbertoca I'm not sure I understand your question.  I don't think the idea is complex technically, I think the idea is complex _for the user_.  The three build systems have different project types.  At least in the proposal outlined by Geertjan all the options are still easily discoverable.  Until there's a good _user facing_ way to categorize those different types of project across build systems, I think we need build system as the first choice.

**Comment by geertjanw** [comment]
I think we should only do a vote on a unified wizard once we have a commitment from someone to actually implement that. And it will not be trivial to implement. :-) (Plus, as @neilcsmith-net points out, it may end up being a lot less intuitive than the current situation for end users. Don't forget that all changes have unintended side effects, so it's better to make changes as small as possible.)

Today, I will create a PR for the proposal I suggested above and that seems to have everyone's approval -- "Java with Maven", "Java with Gradle", and "Java with Ant", in that order, with all the project templates related to Java organized into those three categories.

**Comment by geertjanw** [comment]
Here is the issue with full description:

**Comment by geertjanw** [comment]
Here is the PR: https://github.com/apache/incubator-netbeans/pull/1115
Here is the blog with pic: https://blogs.apache.org/netbeans/entry/restructuring-of-project-templates-in

**Comment by geertjanw** [comment]
My PR is merged. As a consequence, since Maven is now first, as requested via this PR, I am closing this PR.

**Pull request closed without merging**
