### PR TITLE
[NETBEANS-54] Module Review api.search

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
The changes look to only touch files, that I would have seen under "central problems". The change itself looks good though.

**Comment by geertjanw** [comment]
Right. I thought, basically, "let's just get it done".

**Comment by geertjanw** [comment]
Hope someone can do the merges of my PRs, such as this one, haven't got that working yet.

**Comment by matthiasblaesing** [comment]
Done.

**Pull request merged**
