### PR TITLE
Switches to netbeans.osuosl.org for 3rd party non-Maven Central depen…

### PR DESCRIPTION
**Pull request by emilianbold**
…dency binaries

### CODE REVIEW

**Comment by geertjanw** [comment]
Nicely done, sir.

**Comment by geertjanw** [comment]
Background info for this PR: https://jaxenter.com/netbeans/towards-building-netbeans-new-home

**Comment by matthiasblaesing** [comment]
What exactly are we gaining by the switch? Is the new system actively maintained?

**Comment by geertjanw** [comment]
We’re gaining not being dependent on (occasionally fragile) Oracle servers.

**Comment by matthiasblaesing** [comment]
Just to be clear: we still depend on the Oracle server for uploads (https://hg.netbeans.org/binaries/upload), so oracle can not yet drop the server.

**Comment by geertjanw** [comment]
Absolutely true. However, by means of this PR we can switch away from Oracle, plus Emilian has instructions for how to upload to there.

**Comment by emilianbold** [comment]
> Just to be clear: we still depend on the Oracle server for uploads (https://hg.netbeans.org/binaries/upload), so oracle can not yet drop the server.

The NetBeans PPMC has SSH keys to the OSUOSL server. It's totally possible to upload new files there and start using it.

**Comment by geertjanw** [comment]
Shall we merge this?

**Comment by geertjanw** [comment]
Any reason not to merge? Will merge in 24 hours if no objections.

**Comment by matthiasblaesing** [comment]
I'm ok with switching, as long as the oracle server is retained (and used) for uploads, as there is not yet an established way to directly upload to the new system

**Comment by emilianbold** [comment]
>  as there is not yet an established way to directly upload to the new system

`scp` should work, you just need to rename the dependency using that "SHA1 + name" format.

Not saying this to insist on using OSUOSL, it's up to the PPMC to decide. But there's SSH and you have a folder there. Adding a new dependency is just copying a new file.

**Comment by matthiasblaesing** [comment]
As no one else had an option on this and I was the only one voicing concern, I'll merge this. Using the mirror for external access is sound, as the system seems to be used as a dedicated mirror and as such should be maintained. The question of migrating uploads can be discussed later.

**Pull request merged**
