### PR TITLE
[NETBEANS-1074] Licensing 105 unlicensed xml files listed in rat-report

### PR DESCRIPTION
**Pull request by thilina01**

### CODE REVIEW

**Comment by junichi11** [comment]
It seems that there are unit test files. Did you run unit tests whether they success?

**Comment by thilina01** [comment]
@junichi11 
ant -> success
ant tryme -> success
ant rat -> following failures

[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/enterprise.xml: 65 failures out of 65 tests
[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/ergonomics.xml: 1 failures out of 1 tests
[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/groovy.xml: 6 failures out of 6 tests
[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/not cluster.xml: 1 failures out of 1 tests
[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/php.xml: 21 failures out of 21 tests
[rattotest] /home/thilina/github/incubator-netbeans/nbbuild/build/rat/webcommon.xml: 31 failures out of 31 tests
===========
Examined all failures one by one and noticed everything is "Unapproved license....." only
If there is any other command I should run to test, please advise.

**Comment by junichi11** [comment]
> ant -> success
> ant tryme -> success
> ant rat -> following failures

@thilina01 I don't mean these. 
e.g. 
`web.jsf/test/unit/src/org/netbeans/modules/web/jsf/refactoring/data/goldenfiles/ModificationsTest/gold-modifications.xml`
This file is used in 
`web.jsf/test/unit/src/org/netbeans/modules/web/jsf/refactoring/ModificationsTest.java`.
I meant that open the web.jsf module in NetBeans, then right-click ModificationsTest.java, run Test File.

In this case, if you add the license header, test fails. So we should not add the license header. Instead, we have to add the file to rat-exclusions.txt.

I suggest you should check modules[1] one by one because this PR may be a cause of confusion...
Please also look at [2] and PRs of the 1st review e.g. #26 e.t.c. 
[1] https://cwiki.apache.org/confluence/display/NETBEANS/2nd+Donation%3A+List+of+Modules+to+Review
[2] https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

**Comment by thilina01** [comment]
@junichi11 
Thank you for the nice clarification. :+1:  
I will proceed to check the modules one by one. Will update the table accordingly. :)

**Comment by junichi11** [comment]
@thilina01 Thanks a lot for your contribution!

**Comment by junichi11** [comment]
@thilina01 I've created some PRs. Please also have a look at Matthias' comments ;)

**Comment by thilina01** [comment]
Sure, thanks.

**Pull request closed without merging**
