### PR TITLE
[NETBEANS-285] Fix Quick Search Exception on missing JavaHelp RT

### PR DESCRIPTION
**Pull request by lkishalmi**

### CODE REVIEW

**Comment by emilianbold** [comment]
This seems to fix only the symptom and not the cause. The cause is the bad separation from the javahelp jar. (Which I am not entirely certain but might be complicated to pull off since we re-export the JavaHelp APIs, no?)

Anyhow, it might be a good temporary workaround but ideally we should use the module system somehow and not rely on NCDFE / CNFE checks and --cp:a...

**Comment by lkishalmi** [comment]
Well, I guess JavaHelp has some license issues so this one has happened: https://github.com/apache/incubator-netbeans/pull/249/commits/bdb74770a17d5484b9c1fe068c98f41ced7fe07b
We might create another issue to mend this stuff when the fate of the help system get decided.

**Comment by matthiasblaesing** [comment]
@lkishalmi sorry for the late reply. Geertjan proposed a different solution in #467. His approach has the benefit, that the whole registration for java help is removed - that looks cleaner.

**Comment by lkishalmi** [comment]
@matthiasblaesing Well, that was my first solution as well, then I thought that there would be some platform applications bundling JavaHelp, then they would need to re-add these services. But I'm fine with #467, so I'm closing this PR.

**Pull request closed without merging**
