### PR TITLE
[NETBEANS-345] Fix "Move Inner to Outer Level" produces "<captured wildcard>"

### PR DESCRIPTION
**Pull request by dtrebbien**

### CODE REVIEW

**Comment by geertjanw** [comment]
Since @ralphbenjamin approves this, is there a reason not to merge?

**Comment by jlahoda** [comment]
One question: there's a hint to convert an implicit lambda to explicit lambda; that still works, right? Besides this, I don't see a reason why not merge this.

**Comment by matthiasblaesing** [comment]
I checked the hint Jan mentioned and it indeed still works. Merging this.

**Comment by dtrebbien** [comment]
Thank you for your review & question, Jan, and thank you, Matthias, for
following up.  I am sorry for not responding earlier; I have been traveling
without my computer.

**Pull request merged**
