### PR TITLE
Backport of dbalek's fixes made after Apr 22, 2017

### PR DESCRIPTION
**Pull request by dbalek**
This is a batch commit of changes for NetBeans 9 done during legal review of sources already being reviewed and donated. These changes were not part of original donation and contain important fixes for Apache NetBeans to work on/with JDK9.

### CODE REVIEW

**Comment by bdelacretaz** [comment]
Are you the author of all these changes? The "Backport of dbalek's changes" title seems to imply that you are, but if not the authors need to be identified.

**Comment by geertjanw** [comment]
Yes, he's the author.

**Comment by dbalek** [comment]
Why do you think the changes are not mine?

**Comment by geertjanw** [comment]
Because there's so many. It's a compliment. :-)

**Comment by dbalek** [comment]
That is cumulative work since April till now :-)

**Comment by bdelacretaz** [comment]
Cool! I did not imply the changes are not yours, just verifying that they are as it's important in an Apache context. With my incubation mentor hat on...we're all good, thanks for clarifying.

**Comment by geertjanw** [comment]
OK, looked through them, makes sense to me, merging.

**Pull request merged**
