### PR TITLE
[NETBEANS-229] Fixing NPE on creating Installers for Netbeans Platform Applications

### PR DESCRIPTION
**Pull request by thilina01**
Adding Missing resource
incubator-netbeans/nbi/engine/src/org/netbeans/installer/utils/applications/TestJDK.class
JIRA: https://issues.apache.org/jira/browse/NETBEANS-229

### CODE REVIEW

**Comment by geertjanw** [comment]
I guess the question is what does the TestJDK class do -- and how is it licensed? I.e., if it belongs to the JDK, and it is GPL-licensed, we can't add it to an Apache project just like that.

**Comment by thilina01** [comment]
//decompile result of TestJDK.class

import java.io.PrintStream;

public class TestJDK
{
  public static void main(String[] paramArrayOfString)
  {
    System.out.println(System.getProperty("java.version"));
    System.out.println(System.getProperty("java.vm.version"));
    System.out.println(System.getProperty("java.vendor"));
    System.out.println(System.getProperty("os.name"));
    System.out.println(System.getProperty("os.arch"));
  }
  
  public TestJDK() {}
}

**Comment by geertjanw** [comment]
That seems OK. Why is it needed as a .class file?

**Comment by thilina01** [comment]
Will look deep to see the reason and further improvements. In the mean time I assume we can move forward with this PR.

**Pull request merged**
