### PR TITLE
[NETBEANS-1074] Module Review web.jsf.editor

### PR DESCRIPTION
**Pull request by sarveshkesharwani**
- Mavenization of jsf-api-docs.zip to javax.faces-api-2.0-javadoc.jar
- Added CDDL-1.1 license for javax.faces-api-2.0-javadoc.jar instead of CDDL-GPL-CP2
- Added licenseinfo.xml file for graphic files

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Could you please explain the reason to post-process the javadoc file? From a first glance the file from maven central contained more documents, but they are not stripped.

**Comment by sarveshkesharwani** [comment]
> Could you please explain the reason to post-process the javadoc file? From a first glance the file from maven central contained more documents, but they are not stripped.

The new jar from maven central contained many more documents than `jsf-api-docs.zip` (which only contained the javadoc), so while generating the new `generated-jsf-api-docs-2.0.zip`, I wanted to mimic the old `jsf-api-docs.zip` as much as possible. So, I removed all the extra files that were present in `javax.faces-api-2.0-javadoc.jar`. Which extra files do you see in the generated zip that are not yet stripped?

**Comment by matthiasblaesing** [comment]
Sorry - I misread your approach (I overlooked, that you used a different base dir for the new zip). The approach is sound.

One slight nitpick: Could you please move the `jsf_editor_api_location` into the `build` dir? That way all temporary artifacts are there. You can also drop `jsf_editor_api_target_location` if you directly build the zip file without copying files. The zip task can handle excludes itself and supported embedded filesets.

**Comment by sarveshkesharwani** [comment]
> One slight nitpick: Could you please move the `jsf_editor_api_location` into the `build` dir? That way all temporary artifacts are there. You can also drop `jsf_editor_api_target_location` if you directly build the zip file without copying files. The zip task can handle excludes itself and supported embedded filesets.

@matthiasblaesing , You're right. We can drop the `jsf_editor_api_target_location` and directly build the zip file without copying the files. I have done that and moved the `jsf_editor_api_location` into the `build` dir in the latest commit.

**Comment by matthiasblaesing** [comment]
Than you Sarvesh. Merging.

**Comment by matthiasblaesing** [comment]
I screwed the merged - it should have been a squashed before. Sorry.

**Pull request merged**
