### PR TITLE
Backport of junichi11's fixes made after Apr 22, 2017

### PR DESCRIPTION
**Pull request by junichi11**
I've applied my changes using Matthias's steps.
https://lists.apache.org/thread.html/56ab329e71ad9955138edf6399625f2d627ac315b72bcb91c8fd7fb5@%3Cprivate.netbeans.apache.org%3E

### CODE REVIEW

**Comment by geertjanw** [comment]
Very cool. Should we wait to relicense everything in the 2nd donation or integrate this there already?

**Comment by junichi11** [comment]
I'm not sure but some people (e.g. @JaroslavTulach, @sdedic, @dbalek ) did the same thing in the 1st donation.
Furthermore, I have 8 patches for new features. When I worked on them, I didn't push them because new feature phase was already past. So I just attached them to each issue. e.g.
- https://netbeans.org/bugzilla/show_bug.cgi?id=267470
- https://netbeans.org/bugzilla/show_bug.cgi?id=251395
- https://netbeans.org/bugzilla/show_bug.cgi?id=132066
- https://netbeans.org/bugzilla/show_bug.cgi?id=270929
e.t.c.
I would like to merge them as soon as possible because I'm not sure whether I can apply patches correctly after license headers are changed.

If there is a problem, I'll just wait :)
Thanks!

**Comment by geertjanw** [comment]
Are there any that need to be reviewed or should we merge them all without additional steps? Up to you, either way, happy to do what you think best.

**Comment by geertjanw** [comment]
OK, merging.

**Comment by junichi11** [comment]
Probably, in this case, probably, we should not squash & merge because it would be big one commit and it would be hard to find specified changes...

**Pull request merged**
