### PR TITLE
Replace old logo and URL with new Logo and URL on Start Page

### PR DESCRIPTION
**Pull request by thilina01**
Update URL to open http://netbeans.apache.org when a user clicks on NetBeans logo on Start Page

### CODE REVIEW

**Comment by emilianbold** [comment]
Those utm_source and utm_campaign parameters can't hurt. We might be able to separate them in the logs perhaps?

**Comment by thilina01** [comment]
Just realized the importance of having those. 
Yes, not only in the log, we may later implement functionality to track the clicks on the web as well. 
And, ATM there is no effect having them in the URL, it just opens the site with no problem. 
Will add them and update the patch.

**Comment by emilianbold** [comment]
+1

Note there are more URLs in the file but they could be part of other commits if you want to. The whole `welcome` module might need some tweaks because we have fewer project types now, we don't need an Oracle link, etc.

**Comment by thilina01** [comment]
I've started a discussion in Dev mailing list about updating welcome module. Will move forward with some more pull requests based on the suggestions.

**Comment by geertjanw** [comment]
Yes, if you can integrate the new logo into the Welcome screen, that would be great.

**Comment by vieiro** [comment]
I'm afraid we don't have access to logs in netbeans.apache.org, so adding params to the url is of no use.

What we've done in [NETBEANS-330](https://issues.apache.org/jira/browse/NETBEANS-330) is to redirect to http://netbeans-vm.apache.org/ (which in turn redirects to Apache mirrors), I think @jkovalsky  has some root permissions and we can have some statistics if required.

What we could do is to create a link to netbeans-vm.apache.org with appropriate parameters in the Start Page, have them logged in netbeans-vm.apache.org and then redirect to netbeans.apache.org.

**Comment by thilina01** [comment]
@geertjanw I like the way that logo and "Apache NetBeans IDE 9.0" text used in your PR for "splash screen" can I have the source file, so that I can extract the logo and text from it to use in the welcome screen?

**Comment by geertjanw** [comment]
I don't have the source file. We're trying to get it from the person who created it.

**Comment by thilina01** [comment]
@geertjanw Please refer the attached image demonstrating the new logo placed on the start page. would it be okay to amend the PR? 
nbspv2

**Comment by neilcsmith-net** [comment]
> What we could do is to create a link to netbeans-vm.apache.org with appropriate parameters in the Start Page, have them logged in netbeans-vm.apache.org and then redirect to netbeans.apache.org.

-1 to hardcoding any links to the VM in the IDE.  My suggestion with the other URLs was to use the /nb path, and I suggest we do the same here - eg. `https://netbeans.apache.org/nb/welcome/`. We can redirect via the VM to collect stats, moving to another solution later if that proves unviable, without needing to push URL changes to the IDE.

**Comment by emilianbold** [comment]
BTW, @thilina01 , I've added my smaller tweak in this review: https://reviews.apache.org/r/67570/

If you want I would appreciate your feedback over there (and we also check that the site works).

**Comment by emilianbold** [comment]
This can be merged, correct?

**Comment by geertjanw** [comment]
+1 for merging

**Comment by neilcsmith-net** [comment]
0 for merging. As @vieiro said earlier, we have no way of doing stats this way afaik, which we could look to do with a unique inbound URL.  Depends how important that is?

**Comment by emilianbold** [comment]
I would like to at least have the logos, branding and URLs correct.

Metrics are somewhat unrelated and there's no need to block this until we figure it out.

**Comment by neilcsmith-net** [comment]
> Metrics are somewhat unrelated and there's no need to block this until we figure it out.

Agreed!  Hence explicitly changing my -1 to 0. :smile:  Mind you, this might mean we couldn't figure out the metrics question until the next release (that's the pro of having unique URL's, although we might be able to so something with user agent instead).

**Comment by vieiro** [comment]
+1 for merging too. If stats are required let's open a new JIRA for that.

**Comment by geertjanw** [comment]
OK, let's merge. But this is for 'master', not 'release90', must that be done as well?

**Comment by emilianbold** [comment]
So... this was not cherry-picked into release90 branch, correct?

Anybody mind if I do it?

**Comment by emilianbold** [comment]
Done: https://github.com/apache/incubator-netbeans/commit/6b90703f8e89cd5a7fec292276ccb7b41779126e

**Pull request merged**
