### PR TITLE
[NETBEANS-1074] Module review j2ee.sun.dd

### PR DESCRIPTION
**Pull request by arusinha**
Adding back the contents of external zip which contains .dtd files and created licenseinfo.xml for the added files. 
 1. For glassfish schema .dtd files CDDL-1.1 license is used.
found below link for Glassfish .dtd files
https://github.com/javaee/glassfish/tree/master/appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds
https://github.com/javaee/glassfish/blob/master/appserver/tests/v2-tests/appserv-tests/sqetests/avk/ejb/stateless/converter/static-verification_1_4.dtd

2. Also some .dtd files were internal to NetBeans, so for those ASF-2.0  license is used

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Thanks - I'll start with the ALv2 files. You have an ICLA on file so I assume, that, as an Oracle employee, you are in a position to donate the new files. Having written this, you don't need to add the files to the `licenseinfo.xml` please just add the ASF header to the four files and remove the entries in the file.

I noticed, that several of the DTDs don't include a incomplete/missing/wrong license headers. These look like artifacts from when the files were first imported. I looks as if Oracle/Sun got better with this is recent times and the glassfish project distributes:

https://repo1.maven.org/maven2/org/glassfish/main/appclient/gf-client-module/5.0/gf-client-module-5.0.jar

There the DTDs and XSDs contain sane license information. It would be good to replace the files with fresh copies. The `static-verification_1_4.dtd` file is not in there, but I would replace that with the version from the glassfish repository you already referenced.

**Comment by arusinha** [comment]
For below 3 files old files were checked in as with latest available file, schema generation is failing. 
  sun-resources_1_3.dtd 
 glassfish-ejb-jar_3_1-1.dtd
 glassfish-resources_1_5.dtd
Rest files are taken from either https://repo1.maven.org/maven2/org/glassfish/main/appclient/gf-client-module/5.0/gf-client-module-5.0.jar or https://repo1.maven.org/maven2/org/glassfish/ repo except the below
 sun-ejb-jar_3_0-1.dtd(http://www.sun.com/software/appserver/dtds/sun-ejb-jar_3_0-1.dtd)

**Comment by matthiasblaesing** [comment]
The compile errors come from `Schema2Beans`. It turns out, that `Schema2Beans` fails if entity declarations span more than one line in a DTD. I'm looking into improving `Schema2Beans`, so that at least basic support for multiline entities is possible.

**Comment by matthiasblaesing** [comment]
Please have a look at:
https://github.com/matthiasblaesing/incubator-netbeans/tree/github-pr-958

The two commits:
https://github.com/matthiasblaesing/incubator-netbeans/commit/7ce419135d42aad0e4a42b99c6dbd89b38eaa5b1
https://github.com/matthiasblaesing/incubator-netbeans/commit/d5608f2ba35f8e0b18e7f7d2bb3daa229a19751b

fix Schema2Beans for parsing files with entities and especially files with multi line entity definitions.

**Comment by arusinha** [comment]
> Please have a look at:
> https://github.com/matthiasblaesing/incubator-netbeans/tree/github-pr-958
> 
> The two commits:
> [matthiasblaesing@7ce4191](https://github.com/matthiasblaesing/incubator-netbeans/commit/7ce419135d42aad0e4a42b99c6dbd89b38eaa5b1)
> [matthiasblaesing@d5608f2](https://github.com/matthiasblaesing/incubator-netbeans/commit/d5608f2ba35f8e0b18e7f7d2bb3daa229a19751b)
> 
> fix Schema2Beans for parsing files with entities and especially files with multi line entity definitions.

I am on vacation and so is the delay.
@matthiasblaesing request you to merge these two commits in apache:master . Then I will be able to use these schema generation changes in this PR

**Comment by matthiasblaesing** [comment]
@arusinha merged as requested.

**Comment by arusinha** [comment]
Thanks @matthiasblaesing for merging schema changes.
After these schema changes ,schema generation if failing only for glassfish-ejb-jar_3_1-1.dtd(present inside https://repo1.maven.org/maven2/org/glassfish/main/appclient/gf-client-module/5.0/gf-client-module-5.0.jar) , for rest two files(sun-resources_1_3.dtd, glassfish-resources_1_5.dtd) it worked

I found out below tag is  causing the issue
<!ELEMENT enterprise-beans (name?, unique-id?, ejb*, pm-descriptors?, cmp-resource?,
	message-destination*, webservice-description*, property*)>
	
in old file tag was
<!ELEMENT enterprise-beans (name?, unique-id?, ejb*, pm-descriptors?, cmp-resource?,
	message-destination*, webservice-description*)>
If I remove attribute 'property*' , build happens successfully.
error msg is as below
incubator-netbeans/enterprise/j2ee.sun.dd/build/classes-generated/org/netbeans/modules/j2ee/sun/dd/impl/ejb/model_3_1_1/EnterpriseBeans.java:359: error: method setPropertyElement(int,PropertyElement) is already defined in class EnterpriseBeans
[nb-javac] public void setPropertyElement(int index, org.netbeans.modules.j2ee.sun.dd.api.ejb.PropertyElement value) throws VersionNotSupportedException

**Comment by matthiasblaesing** [comment]
@arusinha your finding is correct. The error message from javac gives an additional hint: The code generator generates duplicate methods. The `@Schema2Beans` annotation for the 3.1.1 model reads:

```java
@Schema2Beans(
    schema="../../resources/glassfish-ejb-jar_3_1-1.dtd",
    schemaType=SchemaType.DTD,
    mddFile="../../resources/glassfish-ejb-jar_3_1-1.mdd",
    outputType=OutputType.TRADITIONAL_BASEBEAN,
    docRoot="glassfish-ejb-jar",
    useInterfaces=true,
    validate=false,
    attrProp=true,
    java5=true
)
```

From there you get to the `mdd` file and in `glassfish-ejb-jar_3_1-1.mdd` you find lines 52-85. These customize the code generation and in this case the problem is in the `user-code`. That element adds dummy methods for the `property´ related methods. With the correct DTD you added, the code is generated and the dummy methods are present.

Solution: Remove the whole `user-code` element from the `EnterpriseBeans` customization - lines 59-84 in `glassfish-ejb-jar_3_1-1.mdd`. After running `ant clean` the code generator will produce sane code.

**Comment by arusinha** [comment]
Thanks @matthiasblaesing for the solution, the build was successful
I had now commented out lines 59-84 commented out in glassfish-ejb-jar_3_1-1.mdd and had added latest available .dtd files(glassfish-ejb-jar_3_1-1.dtd,sun-resources_1_3.dtd, glassfish-resources_1_5.dtd)

**Comment by matthiasblaesing** [comment]
Merging - thank you.

**Pull request merged**
