### PR TITLE
Fixes bug in FileChooserBuilderTest

### PR DESCRIPTION
**Pull request by emilianbold**
The tmpdir is loaded but the temporary file is not created in it, resulting on macOS in a Permission denied IOException because java cannot write on root (/). The fix just places the temporary file in java.io.tmpdir as it was probably intended.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I agree with your interpretation, but I'm missing cleanup of the created file in this test. What do you think about this alternative approach:
- use `java.io.File#createTempFile` to create a test file at the beginning of the test
- wrap the test procedure in to a `try {} finally {}` and delete the temp file in the finally clause

**Comment by emilianbold** [comment]
You are right about the cleanup, of course. I've pushed another commit that uses getWorkDir() instead. This seems to be the standard. Cleanup is not assumed unless clearWorkDir is called.

**Comment by matthiasblaesing** [comment]
Looks good. the workdir is below `nb.build.dir` and this is cleaned up by the `clean` task.

**Comment by emilianbold** [comment]
Committed.

**Pull request closed without merging**
