### PR TITLE
Added link to Jenkins builds

### PR DESCRIPTION
**Pull request by cowwoc**

### CODE REVIEW

**Comment by vieiro** [comment]
Better to add this in a level three (###) heading below "Get In Touch".
We should have a link to JIRA as well, I think.

**Comment by geertjanw** [comment]
Agree with Antonio. And the link could be simpler, like this:

https://builds.apache.org/job/incubator-netbeans-release/

**Comment by cowwoc** [comment]
Done, though I believe that the vast majority of your target audience will want to download a copy of Netbeans before they will want the other information on this page. By burying the download link so low you risk losing these potential users before they convert into contributors. Just my 2 cents :)

**Comment by geertjanw** [comment]
Note this is not the homepage of NetBeans, but the location of the NetBeans sources. The main reason for ending up on the page of NetBeans sources is to get the sources, not the download.

**Comment by cowwoc** [comment]
True. Thanks for the merge.

**Pull request merged**
