### PR TITLE
Exclude the GPL beansbinding library

### PR DESCRIPTION
**Pull request by emilianbold**
This commit excludes the GPLed beansbinding library. It also disabled the Matisse Beans binding feature (which depends on the library).

In the IDE the 'Bind' menu is gone as is the Properties section about binding.

Opening a previous Ant-based project which needs beans-binding shows this IDE dialog (and the user will have to manually configure the library).

beans-binding-missing

The sample project ClientEditor is also excluded since it uses a form with bindings.

### CODE REVIEW

**Comment by geertjanw** [comment]
+1 Very nice.

**Comment by jlahoda** [comment]
Looks OK to me too. We could save the form.binding module (it is an eager module, so it would automatically be enabled when its dependencies are satistied, i.e. if the user installed the beansbinding module), but we can do that later. (And removing it as a dependency of form.kit seems good to me anyways - it does not make much sense to me to include eager modules as dependencies of "kits".

**Comment by geertjanw** [comment]
You can have the honor of closing this one: https://issues.apache.org/jira/browse/NETBEANS-172

**Comment by emilianbold** [comment]
> We could save the form.binding module (it is an eager module, so it would automatically be enabled when its dependencies are satistied, i.e. if the user installed the beansbinding module), but we can do that later

@jlahoda: I like this idea very much! I didn't notice that form.binding is eager.

So, for future reference: if we could make o.jdesktop.beansbinding only a compile-time dependency we could still ship form.binding and users would need to install externally just o.jdesktop.beansbinding. (Maybe even go the semi-automated install like we did for JUnit before.)

I'm not pursuing this further but I though it's important to underline how nice this approach would be.

**Pull request merged**
