### PR TITLE
Change phpstan.png

### PR DESCRIPTION
**Pull request by junichi11**
The author of PHPStan provided the official logo. The license is MIT.
https://github.com/apache/incubator-netbeans/pull/896#issuecomment-425189054

nb-phpstan-icon

### CODE REVIEW

**Comment by junichi11** [comment]
Just in case, will request the review.

**Comment by junichi11** [comment]
I see. I'll remove it. Thank you, Tomas and Matthias!

**Comment by junichi11** [comment]
It should be OK now.

**Comment by matthiasblaesing** [comment]
I agree with the change (to be clear: a merge withouot the change would have been ok too - it was just meant as a hint).

**Pull request merged**
