### PR TITLE
add aditional options to the Replace Constructor with Builder window

### PR DESCRIPTION
**Pull request by jherkel**
This change adds two additional edit fields to the Replace Constructor with Builder window :
1) Prefix for setter methods - before this change all setters were constructed like "set" + variable name. When user wanted to change name for setter, he had to edit setter only manually. And when there were a lot of variables it was a little tiring to do it like that. With this change user can change prefix and all setters will be changed at once. If prefix will be empty then variable name will be used for setter method name.
2) Build method name - before this change builder method was constructed like "create" + class name. With this change user can set his own build method name.

### CODE REVIEW

**Comment by geertjanw** [comment]
Thanks a lot, this looks great, will take a look at it.

**Comment by geertjanw** [comment]
Are there any thoughts on this? To me, it looks good and makes sense -- other thoughts, insights, or should it be merged? The impact is on a specific area of NetBeans, i.e., extending the existing refactoring functionality for one specific refactoring and these are exactly the kinds of enhancements we should be hoping to get.

**Comment by jbecicka** [comment]
Looks great

**Comment by geertjanw** [comment]
Thanks for the review, @jbecicka. Merging it.

**Pull request merged**
