### PR TITLE
[NETBEANS-1074] Module Review cordova.platforms.ios

### PR DESCRIPTION
**Pull request by sdedic**
Fixed version in `ios-sim` license. Formatted LGPL to pass through checker. **Removed** `cordova.platform.sim` from cluster configuration as it contains LGPL libraries.

Reviewers, please confirm/object the removal; thanks.

### CODE REVIEW

**Comment by geertjanw** [comment]
For me, this looks good. Does anyone have comments?

**Comment by matthiasblaesing** [comment]
I agree that it looks good. We should be prepared for a discussion at release time with the IPMC, as we have GPL depdendencies in the codebase (I know that is not build with the cluster exclusion, but the last time the replies were not to reasonable). That said, we I would merge it as is.

**Comment by geertjanw** [comment]
OK, merging.

**Comment by junichi11** [comment]
5 XML files don't have the license header.
- [test/unit/src/org/netbeans/modules/cordova/platforms/ios/disconnected.xml](https://github.com/apache/incubator-netbeans/blob/master/webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/disconnected.xml)
- [test/unit/src/org/netbeans/modules/cordova/platforms/ios/jsoncommand.xml](https://github.com/apache/incubator-netbeans/blob/master/webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/jsoncommand.xml)
- [test/unit/src/org/netbeans/modules/cordova/platforms/ios/listing.xml](https://github.com/apache/incubator-netbeans/blob/master/webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/listing.xml)
- [test/unit/src/org/netbeans/modules/cordova/platforms/ios/toback.xml](https://github.com/apache/incubator-netbeans/blob/master/webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/toback.xml)
- [test/unit/src/org/netbeans/modules/cordova/platforms/ios/tofront.xml](https://github.com/apache/incubator-netbeans/blob/master/webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/tofront.xml)

**Pull request merged**
