### PR TITLE
NETBEANS-892: Fix updation of unrelated files during refactor

### PR DESCRIPTION
**Pull request by rtaneja1**
Couldn't reproduce this issue with MoveClassTest, hence no test.

### CODE REVIEW

**Comment by SirIntellegence** [comment]
So, I have a question about this. Is it really necessary to update all references to everything in the file, even if it is unrelated? Just a thought. Also, it should do a read-only check as well. You should stab the person that wrote that code.

**Comment by SirIntellegence** [comment]
*With a blunt object

**Comment by emilianbold** [comment]
Man, language!

**Comment by jlahoda** [comment]
So, I agree the call to importFQNs looks suspicious. Reema, what happens if that's removed altogether? I see the references to the moved class are rewritten using QualIdents (which should automagically resolve imports), so these shouldn't(?) need importFQNs. (The call to importFQNs in createNewFileForType seems fine, of course.)

**Comment by rtaneja1** [comment]
If I remove this importFQNs call, imports for newly added inner class are not added. Investigating, this call seems to be required only for the target file.

**Comment by jlahoda** [comment]
I think it should be possible to be even more strict, and rewrite only identifiers, but I guess we can live with the proposed state for now. Please file a bug to investigate how to improve the code (and to add tests).

**Comment by rtaneja1** [comment]
Logged https://issues.apache.org/jira/projects/NETBEANS/issues/NETBEANS-1005

**Pull request merged**
