### PR TITLE
[NETBEANS-373] Removing synchronization from refactoring dialog.

### PR DESCRIPTION
**Pull request by geertjanw**
Remove synchronization flags in refactoring dialog as discussed here: https://issues.apache.org/jira/browse/NETBEANS-373

### CODE REVIEW

**Comment by geertjanw** [comment]
Seems to have removed the Apache licensing somehow, but we can put it back.

**Comment by geertjanw** [comment]
But there’s currently no change to the .form file anymore. Is there a way to remove it from the pr?

**Comment by ralphbenjamin** [comment]
OK to me.
The underlying problem is; the refactoring-engine is tied to the dialogs. Separating these two would be a huge improvement.
Removing the synchronized keywords makes it possible to have multiple refactoring sessions at the same time, at which I would not know what would happen, but that seems better to me than not working at all for a lot of users.

**Comment by junichi11** [comment]
One of the simplest ways is committing your changes after you recreate a new branch from master one. Then you can close this PR, submit a new one.

**Comment by geertjanw** [comment]
Great, will do that today.

**Comment by geertjanw** [comment]
Followed @ralphbenjamin suggestion and this should mean that only the .java file is changed, so that only the synchronization is removed.

**Pull request merged**
