### PR TITLE
Release90 apidocbranding

### PR DESCRIPTION
**Pull request by ebarboni**
Update index file and last release date to get javadoc main pages and api changes with accurate date

### CODE REVIEW

**Comment by ebarboni** [comment]
Hi @vieiro do you think this would be acceptable with also your modification 
https://github.com/apache/incubator-netbeans/commit/4f98d5b61eb81ea88f1e441a517dbb8864ff20ee

Asking also @neilcsmith-net for review.

**Comment by lkishalmi** [comment]
Can we have such a PR for release100 branch as well?

**Comment by vieiro** [comment]
Hi @ebarboni I don't think https://github.com/apache/incubator-netbeans/commit/4f98d5b61eb81ea88f1e441a517dbb8864ff20ee is worth it since this is a "release" javadoc. The timestamp trick makes sense if were to push the same javadoc multiple times (as this would reduce the number of diffs), but we're pushing the 9.0 javadocs just once.

**Comment by neilcsmith-net** [comment]
Sorry, only just noticed this because of the Release100 one.  I know I made a few more changes to the output from `export2html.xsl`, both changing the title in head and a lot of the body text / links to refer to Apache.  https://github.com/apache/incubator-netbeans-docs/blob/asf-site/content/9.0/javadoc/overview-summary.html  I started editing `export2html.xsl` but then ended up editing the output file instead for some reason that escapes me now.  Obviously needs to go into the xsl file.

Longer term it might be good if we could switch on a release flag (or even the version number) so that release and dev text variants can remain in the file?

Also be good to get the Release100 one in at least before the vote so that checking out the tag for 10.0 can build the correct Javadoc.  Obviously not an option for this one.

**Comment by lkishalmi** [comment]
Just one note guys. As long as the project in incubator phase we cannot use the name Apache NetBeans without mentioning "(incubating)". Please fix the headers!

**Comment by ebarboni** [comment]
Hi I ask @sdedic for review as it's more or less the same than for release100 branch.

Would be nice to merge if ok.

**Comment by ebarboni** [comment]
Hi @emilianbold, would just notify that I want to merge on release90 to have apidoc prepared for generation. (as you are the release manager for release90)

Best Regards

**Comment by emilianbold** [comment]
I have nothing against this PR, seems to only do some minor changes. We don't need to do another 9.0 release so all is well.

+1

**Comment by ebarboni** [comment]
merging apidoc branding

**Pull request merged**
