### PR TITLE
[NETBEANS-747] Implement basic support for variable syntax in CSS grammar

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Apart from the syntax, mark occurences and instant rename are supported.

### CODE REVIEW

**Comment by jwoehr** [comment]
Checked out branch, built and run.  Looks good, solves _my_ problem anyway :)
nb_css_vars

**Comment by peedeeboy** [comment]
I've got some work nearly ready for supporting CSS @supports rules.  Combined with this pull request, that should stop the Bootstrap CSS showing parsing errors in NB.

I'll hold off on submitting a PR until this is approved, so as not to conflict with recompiling the lexer and parser for the Antlr grammar.

I do have a question for @matthiasblaesing or anyone else knowledgeable - I notice you haven't adding any new interfaces/classes to the CSS Source Model library.  This is the bit that is taking my time / annoying me at the moment (may have to refactor my grammar rules to make it easier to build an OO model) - how essential is this, and where does it get used?

**Comment by matthiasblaesing** [comment]
@peedeeboy did you have a look at the changeset? If you agree, I'll merge.

For the model - sorry, I think I can't give direct advise. If you have some code, I'm willing to have a look though.

**Comment by peedeeboy** [comment]
Works great for some properties I tested (width, height etc.) but doesn't work for others e.g. color.  Apologies if you know this already!:

:root {
  --main-color: #06c;
  --accent-color: #006;
}
.h1 {
  color: var(--main-color);
}

fails to parse.

**Comment by matthiasblaesing** [comment]
@peedeeboy you are right - don't apologize, I indeed missed, that the spec for variables defines where it can be used as "nearly everywhere". In contrast to the calc function, the spec is very inprecise about the usability of the var function. I'm looking into it again ...

**Comment by matthiasblaesing** [comment]
@peedeeboy @jwoehr I updated the original PR:
- add var function as a potential value to properties
- update unittests to check for the new functions
- add code completion for variables
I'd appreciate another look.

**Comment by peedeeboy** [comment]
Awesome :)  I'll find time to take a look tomorrow

**Comment by jwoehr** [comment]
Okay, a little unclear now with the "force-pushed" stuff, do I check out your fork, or do I check out master, in order to test, @matthiasblaesing ?

**Comment by matthiasblaesing** [comment]
Sorry for the confusion: The force push was a cleanup. The last few days I incrementally pushed changes and fix ups. In the end I decided to squash them together, as they formed a single commit. This has not yet reached master (that is the whole point of this PR), the right source for the change is `css-variables`. If you pulled the earlier version, you might need to `git reset` that.

**Comment by jwoehr** [comment]
hmm, reset and pull produce conflicts
```
CONFLICT (content): Merge conflict in ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/default_module.properties
Auto-merging ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
CONFLICT (content): Merge conflict in ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
```
Guess I should just delete and pull fresh.

**Comment by matthiasblaesing** [comment]
The accepted answer here:
https://stackoverflow.com/questions/9813816/git-pull-after-forced-update
might help.

**Comment by jwoehr** [comment]
Totally confused now :(
I deleted the tree and did
`git clone https://github.com/matthiasblaesing/incubator-netbeans`
then
```
$ git branch --list
* master
```
And there's no Css*.g file anywhere to generate the parser.

**Comment by matthiasblaesing** [comment]
- `git branch -r` should show remote branches (you are looking for css-variables)
- The master branch in my github repo is not in sync with the incubator master and most probably is still missing the grammar merge
- `git checkout origin/css-variables` should give you the development branch



Am 27. März 2019 22:38:34 MEZ schrieb "Jack J. Woehr" <notifications@github.com>:
>Totally confused now :(
>I deleted the tree and did
>`git clone https://github.com/matthiasblaesing/incubator-netbeans`
>then
>```
>$ git branch --list
>* master
>```
>And there's no Css*.g file anywhere to generate the parser.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/incubator-netbeans/pull/1172#issuecomment-477357648

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jwoehr** [comment]
Ah. Excuse me, doing 3 things at once :) 
Yes, that works.
Yes, it compiles the grammar.
Yes, it builds.
Yes, it runs.
Yes, it is correct for every test case I have in my limited repertoire of CSS, including completion of var names.
Thank you.

**Comment by peedeeboy** [comment]
Tested several examples, all work great!  Awesome stuff :)

**Comment by matthiasblaesing** [comment]
Thank you both for checking. Will merge.

**Pull request merged**
