### PR TITLE
adding crlf characters for the failing tests in api.templates

### PR DESCRIPTION
**Pull request by sarveshkesharwani**
This fixes the failing tests in "SCFTHandlerTest.java" in api.templates module.

### CODE REVIEW

**Comment by junichi11** [comment]
Probably, it's incomplete. I guess that your OS is Windows. Tests would fail in Linux if the changes are added.

BTW, we should remove the license header of utf8.xml [1] because we get an error. (It should be excluded from rat)
```
Testcase: testUTF8(org.netbeans.modules.templates.SCFTHandlerTest):	Caused an ERROR
class.txt:1:0 Expected an operand but found <
<!--
^ in class.txt at line number 1 at column number 0 Log:
```

[1] https://github.com/apache/incubator-netbeans/blob/master/api.templates/test/unit/src/org/netbeans/modules/templates/utf8.xml

@JaroslavTulach @jlahoda 
Should we consider Windows in tests?

Thanks.

**Comment by sarveshkesharwani** [comment]
Yes, my OS is Windows. Were the tests in SCFTHandlerTest.java passing before in linux? (without these crlf changes)

**Comment by jlahoda** [comment]
My personal opinion: ideally tests should pass/work on both Linux and Windows. Instead of playing with different line endings in the expected text, I'd suggest to normalize to one line endings format (ideally the Linux one). I.e. the expected text would have only one format ('\n') of line endings, just readFile(newForm) would do '.replace("\r\n", "\n")' or '.replace(System.getProperty("line.separator"), "\n")'.

**Comment by junichi11** [comment]
> Were the tests in SCFTHandlerTest.java passing before in linux? (without these crlf changes)

Yes, other than the above problem I wrote. (I created a new PR #255)

@jlahoda Thank you for your help! Great idea.

@sarveshkesharwani Could you please fix it? (Please see Jan's comment)

**Comment by sarveshkesharwani** [comment]
@jlahoda Thank you. That's really a great idea.
@junichi11 Fixed. Thanks a lot for the review.

**Comment by JaroslavTulach** [comment]
There are two jobs running (some of) our tests: [windows](https://builds.apache.org/job/incubator-netbeans-windows/) and [linux](https://builds.apache.org/job/incubator-netbeans-linux/). I believe it is important to stabilize them both - e.g. it is desirable that our tests pass on Windows as well as Linux.

Btw. it is unfortunate the windows job has been broken for a while and nobody paid attention to that. Ideas how to make stable test runs priority for the community are welcomed.

**Comment by ebarboni** [comment]
@JaroslavTulach maybe we should connect jenkins to dev mailing list   ?
see [1] section how do I allow Jenkins to mail to my project's "dev" list?

[1] https://wiki.apache.org/general/Jenkins?action=show&redirect=Hudson#Are_there_recommended_or_mandatory_Jenkins_settings_for_ASF_projects.3F

**Comment by junichi11** [comment]
@sarveshkesharwani Great. Thanks a lot! It would be nice if you can rebase and squash your changes into one commit with a proper commit message.

@JaroslavTulach That makes sense. Thank you for your help!

**Comment by sarveshkesharwani** [comment]
@junichi11 That makes sense. Done.

**Comment by junichi11** [comment]
@sarveshkesharwani BTW, Did you send iCLA[1]? (I'm not sure whether this change requires it.) If no and you are going to continue contributing to Apache NetBeans, you should send it :) 

[1] https://www.apache.org/licenses/#clas

**Comment by sarveshkesharwani** [comment]
@junichi11  I haven't sent an iCLA yet, but I am definitely going to continue contributing to Apache NetBeans. I will send the iCLA once I have made a little more contribution towards Apache NetBeans. :)

**Comment by junichi11** [comment]
@sarveshkesharwani Great to hear. We can merge your change without problems after you send it.

**Comment by matthiasblaesing** [comment]
Merged as "trivial fix" without an iCLA. Thanks for looking into this.

**Pull request closed without merging**
