### PR TITLE
[NETBEANS-54] Module Review openide.nodes

### PR DESCRIPTION
**Pull request by emilianbold**

### CODE REVIEW

**Comment by jlahoda** [comment]
Looks OK to me.

**Comment by emilianbold** [comment]
Looks like a Jackpot hints file. Not sure when it's loaded for tests only though...

**Comment by matthiasblaesing** [comment]
Ok - I also did not find out the "why", but indeed the path is read from `org.netbeans.modules.java.hints.declarative.DeclarativeHintRegistry` in the `java.hints.declarative` module. The grammar suggests, that the block comment syntax is correct. Thanks for the hint.

**Comment by jlahoda** [comment]
Sorry for now answering sooner. This is a test for "openide.nodes/src/META-INF/upgrade/org.openides.nodes.Node.hint". It is parsed by org.netbeans.modules.java.hints.declarative.test.TestParser.parse, and I believe the parser should ignore everything before the first %%TestCase.

(In principle, the tests can be also run when the module tests are run, but I doubt that is configured for the nodes module. So the way to run the test is to open it in the IDE.)

**Comment by emilianbold** [comment]
Committed.

**Pull request closed without merging**
