### PR TITLE
Silly use of Boolean

### PR DESCRIPTION
**Pull request by jglick**
Originally posted in [bug #208411](https://netbeans.org/bugzilla/show_bug.cgi?id=208411) but never evaluated: just a minor code simplification.

### CODE REVIEW

**Comment by jglick** [comment]
Note that I get five test failures in this module, but the same is true in `master`. I guess the Travis build is not yet running tests, so we need to that manually, ick.

**Comment by JaroslavTulach** [comment]
Čau Jesse. The platform tests are executed by [jenkins](https://builds.apache.org/job/incubator-netbeans-linux/) builds. Nobody runs all the (non-platform) module tests continuously, however. It would be excellent if you can/want to set more test runs up somewhere.

**Comment by jglick** [comment]
Got it. Would need some discussion about what PR builds should test, etc.

**Comment by JaroslavTulach** [comment]
It is also important to get the tests in the shape - last time I tried to run all NetBeans tests, they timed out. Such tests need to be excluded. Anyway I don't expect we can run all of them in less then few hours, and that is too much for a single Travis job.

**Pull request merged**
