### PR TITLE
Case insensitive SHA-1 comparisons for downloaded binaries.

### PR DESCRIPTION
**Pull request by vieiro**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I'm a bit ambivalent about this, as it introduces the possibility for subtle bugs. One side effect is, that if the same file is used twice in the code base it could be downloaded/cached multiple time as the hash is part of the cache file. Assuming this should be done an alternative idea would be to normalize the hash to upper case at read time. Based on current master, that would be this part in the `DownloadBinaries#execute` method:

```java
String[] hashAndFile = line.split(" ", 2);
if (hashAndFile.length < 2) {
    throw new BuildException("Bad line '" + line + "' in " + manifest, getLocation());
}

if (MavenCoordinate.isMavenFile(hashAndFile[1])) {
    MavenCoordinate mc = MavenCoordinate.fromGradleFormat(hashAndFile[1]);
    fillInFile(hashAndFile[0], mc.toArtifactFilename(), manifest, () -> mavenFile(mc));
} else {
    fillInFile(hashAndFile[0], hashAndFile[1], manifest, () -> legacyDownload(hashAndFile[0] + "-" + hashAndFile[1]));
}
```

The first entry of hashAndFile is the hash and it could be converted there. What do you think?

**Comment by vieiro** [comment]
I think we should normalize to either upper or lower case. Maven currently returns all lowercase, as far as I remember, but allows upper/lower case searches. Another option would be to normalize all manifests to lower case. Maybe that's a better approach.

Let's think about this for a few days.

**Comment by vieiro** [comment]
Matthias, I don't think this is worthwhile any longer.

We can already do the builds perfectly without this, so I think we should discard this PR.

**Comment by matthiasblaesing** [comment]
I agree Antonio, feel free to just close this.

**Comment by vieiro** [comment]
Ok. Closing then.

**Pull request closed without merging**
