### PR TITLE
[NETBEANS-602] Improved support for getting the name from Multi-Release jars

### PR DESCRIPTION
**Pull request by robfitz273k**
Here's a suggested fix for the issue I reported, to do with detecting the module name in Multi-Release jar files.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
CC @tzezula, @dbalek , @sdedic.

**Comment by lkishalmi** [comment]
Hi could you update this PR, so we could include it into NetBeans 10?

**Comment by lkishalmi** [comment]
Any update on this?

**Comment by geertjanw** [comment]
Multi-release JAR support has been added by @jlahoda here:

https://github.com/apache/incubator-netbeans/pull/965

Not sure whether this issue is applicable anymore?

**Comment by geertjanw** [comment]
Is this still needed now that we have multi-jar support added already since this issue was created?

**Comment by lkishalmi** [comment]
It might be needed, I've compared with #965 and these stuff are different. It would be good if the author could answer/retry the testcase. I simply have no time for that now.

**Comment by robfitz273k** [comment]
I've checked with today's Jenkins build (1013) on Java 11 and the issue I reported has been fix by other module related changes.  Thanks for looking at it, I'll close the pull request.

**Pull request closed without merging**
