### PR TITLE
 [NETBEANS-54] Module Review o.apache.commons.lang

### PR DESCRIPTION
**Pull request by arusinha**
Added maven coordinate for external resource commons-lang-2.6.jar

### CODE REVIEW

**Comment by geertjanw** [comment]
Looks good, thanks a lot.

**Comment by matthiasblaesing** [comment]
commons-lang has a notice file, that should be included in the distribution. See for an example here:

https://github.com/apache/incubator-netbeans/commit/a204dcca4b7bd99954e6e67a0331ec172542332c

**Comment by arusinha** [comment]
1. Added notice file from https://svn.apache.org/repos/asf/commons/_moved_to_git/lang/tags/LANG_2_6/NOTICE.txt

2. Also license filename was changed to common-lang-2.6-license.txt

**Comment by matthiasblaesing** [comment]
Thanks for ensuring correct naming!

**Pull request merged**
