### PR TITLE
Removed failing tests dependent on nbm

### PR DESCRIPTION
**Pull request by rtaneja1**
Removed the failing tests as discussed with Geertjan and Jaroslav. These tests require test .nbm files that were removed at the time of donation.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Wouldn't it be better to disable the test instead of deleting them? Even if they are not executed right now, the next one working on the modules might be supported by the code and can reuse it.

**Comment by rtaneja1** [comment]
Disabled the tests, instead of removing.

**Comment by geertjanw** [comment]
Looks like a good solution, not deleting but disabling, so as not to remove the related knowledge from the project.

**Comment by lbruun** [comment]
@rtaneja1 
@geertjanw 

This commit changed **all of the files**, due to change from Unix line endings to Windows line endings.  Been there myself. This mistake is very easy to do, especially with git. I wonder if it is possible to check this in Travis?

Anyway, this commit should be fixed, IMHO.

For the record, I have put 

```
[core]
	autocrlf = input
```

into my _global_ git config. This works for me for now, as all projects I work on happen to use Unix line endings. As far as I understand there's a solution where this setting sits in the repo instead, and I'll raise that issue on the mailing list.

**Pull request merged**
