### PR TITLE
A little cleanup of (IDE) distribution content:

### PR DESCRIPTION
**Pull request by jlahoda**
-THIRDPARTYLICENSE.txt removed (should be replaced with DEPENDENCIES)
-LICENSE.txt removed (in the distribution root, this is replaced with LICENSE, (augmented version of) which is also copied to o.n.upgrader for the Accept License dialog)
-added source README.

### CODE REVIEW

**Comment by geertjanw** [comment]
Great, thank you, though just a Travis build failure, can you fix?

**Comment by matthiasblaesing** [comment]
I had a quick look at the problem and the new files are caught by the rat check.

**Comment by jlahoda** [comment]
Sorry I always forgot the check the travis build on a PR, expecting e-mails in case something goes wrong. I've excluded the new files from Rat.

**Comment by geertjanw** [comment]
Excellent, thanks, merging.

**Pull request merged**
