### PR TITLE
[NETBEANS-1162] Javafx cluster move

### PR DESCRIPTION
**Pull request by mcdonnell-john**
Moving the JavaFX cluster into a JavaFX sub directory.

### CODE REVIEW

**Comment by geertjanw** [comment]
Nice, thanks, really fast, maybe you'd like to pick up another similar cluster, @mcdonnell-john?

**Comment by mcdonnell-john** [comment]
Just about to create a PR for apisupport

**Comment by mcdonnell-john** [comment]
Failing on: ant -quiet verify-libs-and-licenses -Dverify-libs-and-licenses.haltonfailure=true

**Comment by mcdonnell-john** [comment]
Not sure I understand the travis failure.

From what I can see the command:
`ant -quiet verify-libs-and-licenses -Dverify-libs-and-licenses.haltonfailure=true`
failed:
```
[0K$ if [ "x$LICENSE" == "xtrue" ]; then ant -quiet verify-libs-and-licenses -Dverify-libs-and-licenses.haltonfailure=true; fi
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
     [echo] Bootstrapping NetBeans-specific Ant extensions...
     [echo] Downloading external binaries (*/external/ directories) for cluster.config=basic...
[verifylibsandlicenses] Warning: org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[verifylibsandlicenses] Compiler warnings:
[verifylibsandlicenses]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'

BUILD FAILED
/home/travis/build/apache/incubator-netbeans/nbbuild/build.xml:1528: Failed VerifyLibsAndLicenses test(s):
Some binaries were found outside of <module>/external/ directories (edit nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-binaries as needed)
scratch/ide/external/launchers-9.0.zip

Total time: 44 seconds
```
But if I run the locally it passes:
```
Johns-MacBook-Pro-2:incubator-netbeans john$ ant -quiet verify-libs-and-licenses -Dverify-libs-and-licenses.haltonfailure=true
     [echo] Bootstrapping NetBeans-specific Ant extensions...
     [echo] Downloading external binaries (*/external/ directories) for cluster.config=basic...

BUILD SUCCESSFUL
Total time: 17 seconds
```

Any help here ?

**Comment by mcdonnell-john** [comment]
Travis is completing successfully so will merge, as I don't see anything else here.

**Pull request merged**
