### PR TITLE
[NETBEANS-54] Module Review c.jcraft.jsch

### PR DESCRIPTION
**Pull request by junichi11**
- external library jsch-0.1.54.jar: BSD-jsch-variant. Maven coordinates added.
- checked Rat report: everything has been relicensed to Apache, included in 'central problems' list above, or excluded via Rat
- skimmed through the module, did not notice additional problems

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Looks good.

**Comment by emilianbold** [comment]
@junichi11 will you commit this yourself?

**Comment by junichi11** [comment]
@emilianbold Yes. Are the following steps OK if I push my changes myself?
```
$ cd incubator-netbeans

$ git remote add upstream-apache https://git-wip-us.apache.org/repos/asf/incubator-netbeans

$ git checkout master 
$ git pull upstream-apache master
$ git push origin master

$ git checkout module-review-branch
$ git rebase master module-review-branch
$ git push -f origin module-review-branch

$ git checkout master
$ git merge module-review-branch
$ git push upstream-apache master
```

**Comment by emilianbold** [comment]
These look good to me.

Before doing the final push you might do:

**Comment by junichi11** [comment]
Thank you for it :) I'll push changes tomorrow.

**Comment by jlahoda** [comment]
Please note that this changes fail the build, because the jar from maven central has a different hash. The hash on the central is:
DA3584329A263616E277E15462B387ADDD1B208D

I skimmed through the differences, and so far it seems to me it is OK to use the jar from central (we presumably would eventually learn if there would be issues anyway).  I can do that tonight, unless someone will do that before.

**Comment by junichi11** [comment]
@jlahoda I'm sorry... Would you please do that?

**Comment by emilianbold** [comment]
You know, I was just thinking how super useful it is to have the hash when switching to Maven Central since at least you know it's the same JAR.

How could they differ for the same library?

**Comment by jlahoda** [comment]
I agree the hash is useful (among other things) to verify that the jar from the central is the same.

But it is unfortunately not the same in this case. Seems the jar on hg/binaries is the same as a download from the JSch web page, and the jar on maven central is different. My wild guess is that these have been produced by different build processes and different JDKs.

**Pull request merged**
