### PR TITLE
[NETBEANS-592] Fixes Git History regression

### PR DESCRIPTION
**Pull request by emilianbold**

### CODE REVIEW

**Comment by jtulach** [comment]
I am not sure I get the difference? Can `remaining` be negative?

**Comment by emilianbold** [comment]
Hm, let me rebuild and check.

**Comment by emilianbold** [comment]
Yes, `SearchCriteria.getLimit()` may be -1 for all commits.

So your new code will just skip if `remaining` is -1 while my code (which basically copies the logic of the previous `for`) will be executed at least once and return the correct history. (`walk.next()` will return `null` at the next step which means we'll `break`)

**Comment by jtulach** [comment]
I see. Thanks for finding this out and correcting my mistake. Feel free to integrate.

**Pull request merged**
