### PR TITLE
[NETBEANS-406] Fix a potential memory leak involving DocumentUtilities.addPropertyChangeListener.

### PR DESCRIPTION
**Pull request by eirikbakke**
See https://issues.apache.org/jira/browse/NETBEANS-406 . This fixes the problem underlying the following IDE console warning:

`WARNING [org.openide.util.WeakListenerImpl]: Can't remove java.beans.PropertyChangeListener using method org.netbeans.modules.editor.NbEditorDocument.removePropertyChangeListener from org.netbeans.modules.editor.NbEditorDocument@299b063c, mimeType='text/x-editor-search', kitClass=null, length=9, version=15, file=null`

This was a potential memory leak, though I'm not sure if it had a serious impact or not.

### CODE REVIEW

**Comment by geertjanw** [comment]
Any reason not to merge, any potential side effect anticipated?

**Comment by eirikbakke** [comment]
Myself, I can't think of any possible adverse side-effects to this one.

**Comment by matthiasblaesing** [comment]
I know that I'm late to the game, but I would try to avoid changing public API. At present it is possible to relax access modifier via reflection, but we see a trend to prevent this (aka Project Jigsaw) on the JDK level and at some point netbeans module system might also enforce this.

 As an alternative (untested): 

```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
+++ b/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
@@ -37,6 +37,7 @@
 import java.awt.geom.Rectangle2D;
 import java.beans.PropertyChangeEvent;
 import java.beans.PropertyChangeListener;
+import java.beans.PropertyChangeSupport;
 import java.lang.ref.Reference;
 import java.lang.ref.WeakReference;
 import java.util.Arrays;
@@ -909,9 +910,12 @@
             Document doc = docView.getDocument();
             updateTextLimitLine(doc);
             clearStatusBits(AVAILABLE_WIDTH_VALID);
-            DocumentUtilities.addPropertyChangeListener(doc, WeakListeners.propertyChange(this, doc));
+            PropertyChangeSupport pcs = (PropertyChangeSupport) doc.getProperty(PropertyChangeSupport.class);
+            if(pcs != null) {
+                pcs.addPropertyChangeListener(WeakListeners.propertyChange(this, pcs));
         }
     }
+    }
     
     /* private */ void updatePreferencesSettings(boolean nonInitialUpdate) {
         boolean nonPrintableCharactersVisibleOrig = isAnyStatusBit(NON_PRINTABLE_CHARACTERS_VISIBLE);
```

The idea: the `DocumentUtilities#addPropertyChangeListener` just unwraps an `PropertyChangeListener` from the containing Document and attaches to that, this is now done explicitly in `DocumentViewOp`.

@eirikbakke what do you think?

**Comment by eirikbakke** [comment]
Yes, matthiasblaesing, that works, too. Tested and seems to work. I added some comments and made a new commit.

**Comment by sdedic** [comment]
@matthiasblaesing unlike ``addPropertyChangeListener`` which is a versioned API, the updated change distributes the knowledge of `PropertyChangeSupport` presence to another module; I would rather avoid that.

Since this type of bug seems to be rather common, I'd suggest to put an check (not `assert` so existing code is not affected) in the code which logs (level INFO ?) usage of WeakListener (Listener's class has a well-known name prefix).

Last, if we already know that the API method does not work well with core API feature, what about adding a weak alternative to the API, which constructs the weak prop change listener ?

**Comment by matthiasblaesing** [comment]
@sdedic my reasoning for directly accessing the `PropertyChangeSupport` was, that you already need to know, that adding a `PropertyChangeListener` can fail silently (if called on a `Document` not holding a `PropertyChangeSupport`.

However I read your reply as such, that `DocumentUtilities` should gain a new method `addWeakPropertyChangeListener`:

```java
    public static PropertyChangeListener addWeakPropertyChangeListener(Document doc, PropertyChangeListener l) {
        PropertyChangeSupport pcs = (PropertyChangeSupport) doc.getProperty(PropertyChangeSupport.class);
       PropertyChangeListener weakListener = null;
        if (pcs != null) {
                weakListener = WeakListeners.propertyChange(this, pcs);
                pcs.addPropertyChangeListener(weakListener);
        }
        return weakListener;
    }
```

The semantik would be, that the created weak listener is returned, so that is can be used for removal. Callers would need to check for `NULL` if the backing document does not support listening to property changes.

That method would then be used by `DocumentViewOp`. Was this your intention?

As a note for @eirikbakke: if this will be the agreed upon route, this means, the normal API enhancement work needs to be done: The specification version of `editor.util` needs to be incremented, the dependency of `editor.lib2` on `editor.utility` needs to be updated, the API change is to be recorded in `apichanges.xml` and the new method needs to be documented.

**Comment by matthiasblaesing** [comment]
@sdedic could you please revisit this?

**Comment by sdedic** [comment]
@matthiasblaesing apologies / thanks for the reminder. Yes, I think that it would be better to add the API method. There are number of situations when UI need to attach to the document, but typically it's desirable to let GC collect unused UI while the data is alive. 
Thanks for your efforts.

**Pull request closed without merging**
