### PR TITLE
lib.nbjavac: Fix type change for Java 11

### PR DESCRIPTION
**Pull request by wltjr**
Fixes the following issue

```java
src/org/netbeans/lib/nbjavac/services/NBMessager.java:80:
error: method does not override or implement a method from a supertype
    @Override
    ^
src/org/netbeans/lib/nbjavac/services/NBMessager.java:98:
error: no suitable method found for error(DiagnosticPosition,String,Object[])
        super.error(pos, key, args);
```

### CODE REVIEW

**Comment by geertjanw** [comment]
So, should this be merged only for JDK 11 and onwards, i.e., not in release90, which is not aimed at JDK 11?

**Comment by wltjr** [comment]
Seems it is safe for other versions, the test build passed with 1.8. Though this may not work for post Java 11, as it seems its [deprecated](https://github.com/dmlloyd/openjdk/blob/jdk/jdk/src/jdk.javadoc/share/classes/com/sun/javadoc/SourcePosition.java#L42), also mentioned in [JDK 10 docs](https://docs.oracle.com/javase/10/docs/api/com/sun/javadoc/SourcePosition.html)

It was not an issue under JDK 10 or 9. This is only a JDK 11 fix. It can wait till a release that targets JDK 11. No rush, more a heads up to issues with JDK 11. If not merged that is fine. There maybe a better solution for long term, as SourcePosition is set for removal. I just had to do that for JDK 11, so figured I would submit a PR.

**Comment by ebarboni** [comment]
this PR should be relocated to the new folder organisation.
lib.nbjavac is blocking the build on jdk11

**Comment by matthiasblaesing** [comment]
I'm missing something, because I just build the module without the patch. What is the sequence to trigger the mentioned bug? Can the issue be triggered if using the netbeans ant harness or do you need to work around the build system?

**Comment by wltjr** [comment]
To trigger the issue just build under JDK 11. The Messager class [error method](https://github.com/unofficial-openjdk/openjdk/blob/jdk/jdk/src/jdk.javadoc/share/classes/com/sun/tools/javadoc/main/Messager.java#L246) parameters changed from DiagnosticPosition to SourcePosition.

**Comment by matthiasblaesing** [comment]
I cherry-picked the change onto master (git took care of adjusting the path) and pushed it:
https://github.com/apache/incubator-netbeans/commit/aed622a9c2467f37d8abea38f2d80019e24d5067

**Comment by wltjr** [comment]
@matthiasblaesing sounds good, thanks for addressing!

**Pull request closed without merging**
