### PR TITLE
Merge the 2ndDonation branch into the master branch

### PR DESCRIPTION
**Pull request by junichi11**
I ran the following command:
```
$ git checkout master
$ git checkout -b integrate-2ndDonation
$ git merge --allow-unrelated-histories --no-ff 2ndDonation
```
Then resolved the merge conflict (nbbuild/cluster.properties).
I just kept the master branch's file. Is this correct?

### CODE REVIEW

**Comment by jlahoda** [comment]
So, there appear to be (at least) two Travis CI checks failing:
-the rat check; I'd suggest to modify ".travis.yml", replacing the line:

>   - ant -quiet rat -Drat-report.haltonfailure=true
with

>   - (ant -quiet build-source-config && mkdir scratch && cd scratch && unzip -qq ../nbbuild/build/platform-src* && ant -quiet rat -Drat-report.haltonfailure=true && cd .. && rm -rf scratch)

That should ensure rat only checks what is in the default build in Travis.

Then there's a failure that some of the files are using different line endings than LF, I guess the easiest would be to simply change that.

I can try to work on these in the evening, if needed.

**Comment by junichi11** [comment]
> I can try to work on these in the evening, if needed.

@jlahoda Could you please do it? I'll leave it to you. Thanks!

**Comment by matthiasblaesing** [comment]
I see no files with windows line endings and the check in the travis run also return 0 (the shell equivalent of true), so this looks good. The rat report problem is kind of expected.

In general the approach of @junichi11 is sound. We might merge and disable the rat test for now (instead of introducing a work around) -- the rat report needs to be worked, but getting things into master might be worth it.

**Comment by junichi11** [comment]
Thank you for taking over it, @jlahoda ! I'll close this PR :)

**Pull request closed without merging**
