### PR TITLE
[NETBEANS-1074] Module Review websvc.core

### PR DESCRIPTION
**Pull request by vikasprabhakar**
Checked the rat-report.txt file, are these files ok with Apache License ?
glassfish-license.txt
Apache Bug: https://issues.apache.org/jira/browse/NETBEANS-1189

Add the license header for binaries-list
Add the license header for java files
Add the license header for Bundle.properties
Add the licenseinfo.xml

### CODE REVIEW

**Comment by junichi11** [comment]
Related changes for websvc.core:

- https://hg.netbeans.org/releases/rev/ec54710325a8
- https://hg.netbeans.org/releases/rev/09747df6994d
- https://hg.netbeans.org/releases/rev/96b27242f997

**Comment by matthiasblaesing** [comment]
The license of `websvc.core-external-resources.zip` is not correct and it would be better to include the files directly in the source.

- `sun-jaxws.xsd` already holds a valid license info
- The original version of `javaee_web_services_metadata_handler_2_0` can be found at
https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/javaee_web_services_metadata_handler_2_0.xsd and carries also a valid header
- The same is true for the original version of `wsdl_customizationschema_2_0` from http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/jaxws/wsdl_customizationschema_2_0.xsd

We elect the CDDL as the license under which we use the files (add a licenseinfo.xml for this). We can include the source according to (second last paragraph):
https://www.apache.org/legal/resolved.html#category-b

This way the hole external binary can be dropped and we don't have to deal with the broken license.

**Comment by vikasprabhakar** [comment]
Following steps taken to remove external folder
1. Remove external folder
2. Update build.xml file
3. Restore xsd file to "/src/org/netbeans/modules/websvc/core/resources" folder
4. Update license details in xsd file.

**Comment by matthiasblaesing** [comment]
Great so far - I think the final nitpick: CDDL code needs reasoning to be included in ASF projects. Please see here:

https://github.com/apache/incubator-netbeans/blob/dffa844eece9ffc49dd4073db043d0807cb6e50e/web.core/licenseinfo.xml#L90-L102

I faced the same situation as you did. CATEGORY-B here references to an explanation that give the reasoning required in [Apache Legal FAQ](https://www.apache.org/legal/resolved.html#category-b) (second last paragraph)

**Comment by vikasprabhakar** [comment]
@matthiasblaesing added the xsd file in licenseinfo.xml file plz review it

**Pull request merged**
