### PR TITLE
[NETBEANS-1074] Module Review php.phpdoc.documentation

### PR DESCRIPTION
**Pull request by junichi11**
Remove this module because phpdocdesc.zip is used no longer: https://hg.netbeans.org/web-main/rev/eebf8c598245

### CODE REVIEW

**Comment by tmysik** [comment]
@junichi11 Unfortunately, no idea. I would not be surprised if they were not used at all.

**Comment by junichi11** [comment]
@tmysik Thanks for your reply.

I'll try to investigate where they are used later.

**Comment by matthiasblaesing** [comment]
For the module discussed here (php.phpdoc.documentation): phpdocdesc does not seem to be used (I grepped through the whole tree and there are only referenced, that don't look like "usage"). So maybe the module should just be purged from the tree? The packaged version is dead (according to wikipedia) and phpDocumentor2 replaced it. If you think we gain anything with the introduction of the ALv2 header to binaries list, feel free to merge, but I don't see the benefit.

For the predefined_vars.zip: That looks like extracts from php.net, these are licensed CC-BY-SA 3.0:
http://de2.php.net/manual/en/copyright.php
which is possible to include:
https://www.apache.org/legal/resolved.html#category-b

**Comment by junichi11** [comment]
I found the changeset related to phpdocdesc.zip: https://hg.netbeans.org/web-main/rev/eebf8c598245

This is used no longer. So we should be able to remove this module. Am I wrong?

**Comment by tmysik** [comment]
@junichi11 Correct.

**Comment by junichi11** [comment]
@tmysik Thanks! I'll remove it.

**Comment by junichi11** [comment]
@tmysik Thank you for reviewing it! I've fixed it.

**Pull request merged**
