### PR TITLE
[NETBEANS-54] exclude .ser files via Rat exclusions

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Can someone advise how to resolve the conflict here?

**Comment by matthiasblaesing** [comment]
To resolve the conflict I suggest that you:
- rebase the changes onto master
- resolve the conflict while rebasing
- push the updated branch (you'll need to do a forced-push to be able to push a rebased branch)

**Comment by geertjanw** [comment]
It should be OK now.

**Comment by geertjanw** [comment]
Yes, I used the GitHub web interface, not the command line. I wanted to see if it was possible to use the conflict like that, and it seems to have worked.

**Comment by geertjanw** [comment]
@matthiasblaesing, is this safe to merge from your point of view, if not, will just close this and start a new pull request.

**Comment by matthiasblaesing** [comment]
Yes this looks safe.

**Comment by geertjanw** [comment]
OK, merging. And if this works without side effects, we’re able to resolve conflicts via GitHub (versus multiple and potentially error prone command line calls), which is nice.

**Comment by matthiasblaesing** [comment]
@geertjanw if it helps you or others I'm ok with this, but I'll stay with the CLI tools, which also happily work with non-github repositories. Remember: sourceforge mostly died because they decided that "free project hosting" does not pay bills and then began to modify projects binaries - if github pulls a stunt like that, I will just go on and work against the apache hosted repository.

What is more with the CLI (or other local tools) I can pull from other sources than github, so if contributers don't like github, but host their changes in another public git repository (bitbucket, gitlab, ...) we can still pull their changes.

**Comment by geertjanw** [comment]
Makes sense.

**Pull request merged**
