### PR TITLE
[NETBEANS-856] Remove last OASIS license references

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The catalog files were imported into the netbeans package because they
are missing from the maven central xml-resolver sources, but are part
of the binary on maven central.

The xml-commons-resolver-1.2.zip also contains the files:

http://archive.apache.org/dist/xerces/xml-commons/xml-commons-resolver-1.2.zip

so it is assumed they are part of the release.

So the netbeans binary is created by:

- fetching sources from maven central
- patching the source
- build new binary
- repackage the new binary:
  - add CRC reference to original library
  - merge grammar files from maven central binary

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@vieiro @emilianbold could you please have a look at this? This is still the aftermath of the release of netbeans 9.0. Lets just say, that the OASIS license raised some concerns when it is included by us. On the other hand, about fifteen years ago the same files were included into xml-resolver. So instead of refighting, I think it is better to work with the established code base of xml-resolver. 

I decided to stick with the data from maven central, but an alternative approach would be to fetch the "real" release data from apache, but I think we don't gain anything from that and maven central has a massive CDN, that I'd like to take advantage of as much as possible.

**Comment by emilianbold** [comment]
I totally support consuming ASF dependencies on rely on their existing IP clearance.

**Comment by vieiro** [comment]
Hi @matthiasblaesing ,
To clarify my understanding: we're removing these offending sources from our repo (that were not offending years ago  but are now) and instead download them from Maven Central (after some patching). If so this workaround seems good to me, as it's important to add these schemas to NetBeans.

**Comment by matthiasblaesing** [comment]
@vieiro your summary is correct.

**Comment by vieiro** [comment]
Hi @matthiasblaesing , 
This being so, I have no issues with mergin. 
Thanks very much for doing this!.

**Pull request merged**
