### PR TITLE
[NETBEANS-1074] AddFormLicense tool used to add licenses

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Seems to me that the PR also relicenses form files to Apache that had already been relicensed to Apache. Not sure if this is a problem though.

**Comment by thilina01** [comment]
Like to know how the rat-report looks like afer this commit.

**Comment by geertjanw** [comment]
Rat report will be cut in half from about 1200 to around 600 unknown files.

**Comment by geertjanw** [comment]
Anyone have a reason not to merge this, or does anyone have comments of any kind?

**Comment by junichi11** [comment]
@geertjanw There are duplicate license headers. Probably, the license header was added to files of other than the 2nd donation again.

**Comment by geertjanw** [comment]
That sucks. How do we add licenses only to the files that don't already have them?

**Comment by geertjanw** [comment]
This needs to be tweaked to only be run if no Apache license is already in the file: https://github.com/apache/incubator-netbeans-tools/blob/master/convert/src/convert/AddFormLicense.java

**Comment by geertjanw** [comment]
Closing, will send a new one with only the form files in the newly added modules relicensed.

**Pull request closed without merging**
