### PR TITLE
[NETBEANS-144] Changes to About Dialog and Lic Accept wnd

### PR DESCRIPTION
**Pull request by lbruun**
- Changes the text below the image in the About Dialog

- Changes the URL which is used when the image in the About Dialog is clicked upon.

- Changes the text of the license accept window which is used when the user starts the IDE for the first time from a zip bundle. To reviewers: I've made changes to the All-Caps text part at the beginning of the file:  I've replaced "Oracle" with "Apache Software Foundation" and a few minor changes as well. The text was:
> PLEASE READ THE FOLLOWING LICENSE AGREEMENT TERMS AND
> CONDITIONS CAREFULLY, INCLUDING WITHOUT LIMITATION THOSE
> DISPLAYED ELSEWHERE (AS INDICATED BY LINKS LISTED BELOW),
> BEFORE USING THE SOFTWARE.  THESE TERMS AND CONDITIONS
> CONSTITUTE A LEGAL AGREEMENT BETWEEN YOU, OR THE ENTITY FOR
> WHICH YOU ARE AN AUTHORIZED REPRESENTATIVE WITH FULL
> AUTHORITY TO ENTER INTO THIS AGREEMENT, AND ORACLE.  BY
> CLICKING "ACCEPT" OR THE EQUIVALENT YOU AGREE TO ALL OF
> THE TERMS AND CONDITIONS OF THIS LICENSE AGREEMENT.  IF YOU
> DO NOT AGREE TO THIS LICENSE DO NOT CLICK "ACCEPT" OR
> THE EQUIVALENT AND DO NOT INSTALL OR USE THIS SOFTWARE.
> 

and is now:

> PLEASE READ THE FOLLOWING LICENSE AGREEMENT TERMS AND CONDITIONS CAREFULLY
> BEFORE USING THE SOFTWARE. THESE TERMS AND CONDITIONS CONSTITUTE A LEGAL
> AGREEMENT BETWEEN YOU, OR THE ENTITY FOR WHICH YOU ARE AN AUTHORIZED
> REPRESENTATIVE WITH FULL AUTHORITY TO ENTER INTO THIS AGREEMENT, AND
> APACHE SOFTWARE FOUNDATION (ASF). BY CLICKING "ACCEPT" OR THE EQUIVALENT
> YOU AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS LICENSE AGREEMENT. IF
> YOU DO NOT AGREE TO THIS LICENSE DO NOT CLICK "ACCEPT" OR THE EQUIVALENT
> AND DO NOT INSTALL OR USE THIS SOFTWARE.
> 

- Splash images for Platform and IDE changed so that the text at the bottom of the image reflect the new Apache licensing. Only the text is changed. No changes to the art-work itself. (i.e. logo, colors, etc)

I feel this sufficient to close NETBEANS-144.

Outstanding:

- The splash on the Platform Updater ([link](https://github.com/apache/incubator-netbeans/blob/master/autoupdate.services/libsrc/org/netbeans/updater/resources/updatersplash.gif)) is just plain wrong as has been for the past 15 yrs. It refers to _Sun Public License_. It is a bit difficult to change as the background of the text isn't solid. I don't think it matters much currently as the Updater Splash is shown very, very briefly, which I guess is the reason why this hasn't been noticed. (the IDE Updater Splash is ([link](https://github.com/apache/incubator-netbeans/blob/master/ide.branding/autoupdate.services/libsrc/org/netbeans/updater/resources/updatersplash_nb.gif)) doesn't have text, so doesn't have this problem).

- The About Dialog images for the IDE (not for the Platform, as the Platform uses the Splash images also in the About Dialog) contains the text "www.netbeans.org", but it is difficult to change graphically as the background of the text isn't solid. In terms of releasing under the the ASF, I think this looks 'stupid', but is probably acceptable for now.

### CODE REVIEW

**Comment by geertjanw** [comment]
Looks good. Can we merge this and open a new issue or do a new pull request for any connected items that need to be worked on?

**Comment by lbruun** [comment]
I feel this closes NETBEANS-144. 

I'll open ticket(s) for the outstanding issues but I don't think they are important for a release.

**Comment by jtulach** [comment]
Does Apache require us to show the license acceptance window? I expect the answer is no. Then, the easiest thing is to remove the license acceptance window altogether.

**Comment by lbruun** [comment]
@jtulach. Agreed. But this PR is a stop-gap which allows us to release now. It doesn't exclude other measures in the near future, but it means we don't have to wait for an answer from whoever.

Btw: If active license acceptance by the user is no longer required then we should also remove the equivalent feature from the IDE's installer, not just from ZIP bundle. (however, the IDE's Installer is not yet donated so we cannot make such a change yet, even if we wanted to)

**Comment by lbruun** [comment]
I've updated the PR so that the "outstanding issues" mentioned originally is now also fixed (despite me saying it was difficult to fix, graphically .. it wasn't !). 
Please merge.

**Pull request merged**
