### PR TITLE
Replace the old icon with new icon

### PR DESCRIPTION
**Pull request by thilina01**
Replacing the old icons found by going through all icons (png / ico / gif ) in the project several times.
These are the icons used the pure old logo, so that can be easily replaced by the new one.

### CODE REVIEW

**Comment by sdedic** [comment]
Seems good

**Comment by emilianbold** [comment]
Also to release90 perhaps?

**Comment by geertjanw** [comment]
Only if we need to create a new vc should we include this in release90, I think, unless I'm wrong. We should simply merge it into main, that's all, imho.

**Comment by geertjanw** [comment]
Many thanks for doing this, merging.

**Pull request merged**
