### PR TITLE
[NETBEANS-1227] Mark Windows launchers as DPI-aware

### PR DESCRIPTION
**Pull request by eirikbakke**
Add manifest information to the netbeans64.exe, app64.exe, and nbexec64.exe executables (and their 32-bit equivalents) to tell Windows that Java supports HiDPI scaling, like javaw.exe already does. This enables HiDPI support on Windows, without needing to fuzz around with special settings. This works on both Java 9 and Java 10. See https://issues.apache.org/jira/browse/NETBEANS-1227 .

For those who are still using Java 8, NetBeans will now appear small (but sharp) on HiDPI screens. The old behavior, of NetBeans appearing normal size but blurry, can be reverted by right-clicking the NetBeans shortcut, and clicking Properties->Compatibility->Change HiDPI Settings->Override high DPI scaling behavior->Scaling performed by System. If we expect this to be a problem, an alternative would be have the launcher detect the use of Java 8 (and Windows 8.1 minimum) and turn off DPI awareness programmatically using the Windows [SetProcessDpiAwareness](https://docs.microsoft.com/en-us/windows/desktop/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness) API call. But I'd rather recommend that people with HiDPI screens should run NetBeans with Java 9 or above, where support for such screens is actually available.

This pull request also fixes some relative paths that broke when directories were moved around, and makes two other minor fixes.

Note that the new Windows launchers (app64.exe and netbeans64.exe) seem not to suppress the console properly; this is an unrelated bug that was present before this patch.

### CODE REVIEW

**Comment by lkishalmi** [comment]
Well, I do not have a Windows system to try, but looking at the code it is nice and clean.

**Comment by geertjanw** [comment]
For me, this looks good and makes sense.

**Comment by geertjanw** [comment]
Any reason not to merge this?

**Comment by eirikbakke** [comment]
Are the Windows EXE files generated as part of the normal build process, or do they need to be recompiled and added as binary files to the github repo?

I saw the comment on another launcher issue https://issues.apache.org/jira/browse/NETBEANS-417 saying "we need to publish the binaries from this source and then use it in the netbeans build." But there is also https://issues.apache.org/jira/browse/NETBEANS-128 "NetBeans platform shall not contain IDE launchers".

If the EXE files are built automatically, then the PR should be good to merge.

**Comment by ebarboni** [comment]
hi there is an issue https://issues.apache.org/jira/browse/NETBEANS-1145 concerning the windows launcher build I guess any tips, comment are welcome there

**Comment by lkishalmi** [comment]
What is the status of this PR. If it is ready then let;s merge it!
Since NB 10.0 vc1 vent out without launcher script update, we might consider this one cherry picked into release100 branch and release the next vc with this.

**Comment by eirikbakke** [comment]
This PR is ready to merge.

But as far as I know, simply updating the source files do not cause the new EXE files to be included in the new NetBeans distro (I assume that's what https://issues.apache.org/jira/browse/NETBEANS-1145 will fix). Is there some manual step we need to take in addition, to locally build the EXE files, and include them in the repo or some external location? Do we actually put EXE files somewhere in the repo?

**Comment by lkishalmi** [comment]
Merged and cherry picked into release100. AFAIK the launchers now is in the repo as a zip filr. I'm going to update that as well, till NETBEANS-1145 solves this issue.

**Pull request merged**
