### PR TITLE
[NETBEANS-1074] Module Review websvc.wsitmodelext

### PR DESCRIPTION
**Pull request by vikasprabhakar**

### CODE REVIEW

**Comment by geertjanw** [comment]
Any reason not to merge, can someone who has reviewed other similar pull requests take a look at this one?

**Comment by matthiasblaesing** [comment]
The licensing is not correct and the situation is a bit more difficult. At least for parts of the schemas (from my quick check):

- wsat.xsd
- wsrmp-1.2-schema-200702.xsd
- wsrm-policy-200502.xsd
- ws-securitypolicy.xsd
- ws-securitypolicy-1.2.xsd
- WS-Trust.xsd
- ws-trust-1.3.xsd
- oasis-200401-wss-wssecurity-utility-1.0.xsd

I found these as OASIS schemas (or even a different license). The OASIS schemes are really bad, as we are not allowed to get them into version control. I don't know how the license for the OASIS files was determined, but I could not verify it. See for example http://docs.oasis-open.org/ws-sx/ws-trust/v1.4/cd/ws-trust.xsd (the WS Trust XSD)

This situation was already solved for the `ide/xml.wsdl.model`. The idea there is that the license allows redistribution, but not modification. The XSDs can most probably be extracted from apache cxf artifacts on maven central. See her:

http://cxf.apache.org/docs/schemas-and-namespaces.html

**Comment by vikasprabhakar** [comment]
@matthiasblaesing it will be helpful if you can provide the license details or license related path (non oasis license) for the following xsd files:
wsat.xsd
wsrmp-1.2-schema-200702.xsd
wsrm-policy-200502.xsd
ws-securitypolicy.xsd
ws-securitypolicy-1.2.xsd
WS-Trust.xsd
ws-trust-1.3.xsd
oasis-200401-wss-wssecurity-utility-1.0.xsd

**Comment by matthiasblaesing** [comment]
I found some of the schemas:
- org.apache.cxf:cxf-rt-ws-policy:3.2.6
- org.apache.cxf:cxf-rt-ws-rm:3.2.6
- org.apache.cxf:cxf-core:3.2.6
I think I never saw ws-trust in the CXF files.

**Comment by rtaneja1** [comment]
wsat.xsd : https://github.com/javaee/metro-wsit/blob/master/wsit/ws-tx/wstx-services/src/main/webapp/WEB-INF/wsdl/wsat.xsd

**Comment by rtaneja1** [comment]
http://schemas.xmlsoap.org/ws/2005/02/trust/ws-trust.xsd
Below seems to be available only from oasis, can you please compare if there's a difference between both, apart from comments.
http://docs.oasis-open.org/ws-sx/ws-trust/200512/ws-trust-1.3.xsd

**Comment by vikasprabhakar** [comment]
Changes for following xsd files:
1. oasis-200401-wss-wssecurity-utility-1.0.xsd -> Taken from cxf-rt-ws-policy-3.2.6.jar
2. ws-securitypolicy-1.2.xsd -> Taken from cxf-rt-ws-policy-3.2.6.jar
3. ws-securitypolicy.xsd -> W3C license added
4. wsrmp-1.2-schema-200702.xsd -> Replace with wsrmp-1.1-schema-200702.xsd i.e taken from cxf-rt-ws-rm-3.2.6.jar
5. wsrm-policy.xsd-> Taken from cxf-rt-ws-rm-3.2.6.jar
6.WS-Trust.xsd -> Remove the xsd file, http://schemas.xmlsoap.org/ws/2005/02/trust/ws-trust.xsd license is not appropriate
7. ws-trust-1.3.xsd -> Remove the xsd file, OASIS license require
8. wsat.xsd -> License is added in header file (https://github.com/javaee/metro-wsit/blob/master/wsit/ws-tx/wstx-services/src/main/webapp/WEB-INF/wsdl/wsat.xsd)

Note:
1. There is no compile errors with these changes.
2. Removing of ws-trust*.xsd files may cause error in functionality.

@matthiasblaesing , @rtaneja1 Please provide your feedback on the above changes.

**Comment by vikasprabhakar** [comment]
Logged a jira bug to follow up the licensing issue: https://issues.apache.org/jira/browse/NETBEANS-1756

**Comment by vikasprabhakar** [comment]
Plan to remove the module from release.

**Pull request closed without merging**
