### PR TITLE
[NETBEANS-402] ClassCastException at org.netbeans.lib.profiler.server…

### PR DESCRIPTION
**Pull request by cowwoc**
….ProfilerRuntimeCPU.getParSize()

### CODE REVIEW

**Comment by cowwoc** [comment]
@jlahoda How do I request reviews for PR? I noticed you did so in another issue. Does it require special permissions?

**Comment by geertjanw** [comment]
Requested the review, not sure if special permissions are needed.

**Comment by blackleg** [comment]
https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by cowwoc** [comment]
@blackleg @geertjanw Thanks. Seeing as most contributors won't have write access to this repository, does it make sense that they can't request a review? Will committers know to regularly review new PRs?

**Comment by geertjanw** [comment]
Like I said, I’m not sure if this is true. And, yes, committers know to regularly review, that’s what I’ve been asking on the mailing list. And anyone can review, not just committers. Will you review some too, and, no, you don’t need to be an expert, just read the PR and give your opinion.

**Comment by jlahoda** [comment]
To me, looks OK, even though I don't know much about the profiler.

**Comment by jtulach** [comment]
+1

**Comment by matthiasblaesing** [comment]
Merged - thank you!

**Comment by cowwoc** [comment]
Thanks @matthiasblaesing :)

**Pull request merged**
