### PR TITLE
[NETBEANS-47] readded not donated maven-4.0.0.xsd

### PR DESCRIPTION
**Pull request by lhochet**
During the NetBeans code review maven.grammar\src\org\netbeans\modules\maven\grammar\maven-4.0.0.xsd was removed, this re-adds it as it is already an Apache file (from https://maven.apache.org/xsd/maven-4.0.0.xsd)

### CODE REVIEW

**Comment by dtrebbien** [comment]
This should fix https://netbeans.org/bugzilla/show_bug.cgi?id=271097 NullPointerException at java.net.URL.&lt;init&gt;

**Comment by matthiasblaesing** [comment]
Please add a license header - see my comment in #281.

**Comment by lhochet** [comment]
I've added the licence header.

**Comment by matthiasblaesing** [comment]
Thank you for looking into this. I squashed the commits of both changesets together and merged these in https://github.com/apache/incubator-netbeans/commit/262b820ccf2ae2823b585adbb3ee682ad8798e09. The commit for maven-4.0.0.xsd was further modified, as the line endings were MSDOS (\r\n) and the non-binary files in the repository should only contain UNIX endings (\n).

**Comment by lhochet** [comment]
Thanks. 
Once I'll have edit rights for the wiki I'll add a mention about nbm-1.0.0.xsd which isn't at Apache, and which I could not find.

**Pull request closed without merging**
