### PR TITLE
NETBEANS-716 Help-Report Issue should navigate to JIRA link in browser

### PR DESCRIPTION
**Pull request by rtaneja1**
This ui currently points to bug infra on netbeans.org and fails on submit task.  We should redirect user to Apache JIRA.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Looks good. Please consider cherry-picking this to release90, the branch that was created to finally release Netbeans 9.0.

**Comment by neilcsmith-net** [comment]
Found this while checking through vc3 and wondering why that action was still broken.  Guess it didn't get cherry-picked in time?!

IMO this link should be to something under `https://netbeans.apache.org/nb/....` though.  We can set up a redirect from there to JIRA.  The idea was to give us a common root URL for everything inbound from the IDE.

**Comment by rtaneja1** [comment]
Right, backport for this PR was missed out. I can create one today. Should I create a new page https://netbeans.apache.org/nb/issues_redirect.html and point to that in place of jira link?

**Comment by neilcsmith-net** [comment]
@geertjanw should really be in the `.htaccess` with the others I think.  See https://github.com/apache/incubator-netbeans-website/pull/65

I've added the existing link and `https://netbeans.apache.org/nb/report-issue/` - clean URL is probably better for this, but existing one with `.html` should work.

I can't remember where the JBake logs are off-hand - the PR you committed doesn't seem to have built?!

**Pull request merged**
