### PR TITLE
[NETBEANS-299] Fixing parser over classfiles, tested by java.source.b…

### PR DESCRIPTION
**Pull request by jlahoda**
…ase/src/org/netbeans/modules/java/source/parsing/ClassParser.java.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I did a local merge to master and build that. I found the problem fixed (nbjavac with java 8). I see a minor difference to netbeans 8.2: When a class file outside a jar is selected the navigator window in netbeans 8.2 shows the class name (no members), with netbeans 9 the navigator window remains empty. From my POV this is ok.

Without nbjavac I saw exceptions, I'll see if I find time to check these and will followup with reports.

**Comment by jlahoda** [comment]
Hm, I admit I was only trying with JDK classes (which seemed to work OK, including navigator). Will try with other classes as well.

**Comment by matthiasblaesing** [comment]
Just to prevent misunderstandings: The navigator and editor window work correctly if the class file is inside a jar. If the class file is outside a jar it can't be opened in the editor and the navigator window remains empty. This is really minor and I would not even consider it a regression, as the info in NB 8.2 was not really helpful:

nb82
nb9

I would merge it as is.

**Comment by geertjanw** [comment]
Looks good to me.

**Pull request merged**
