### PR TITLE
[NETBEANS-161] Changed license header introducer to simple slash-star

### PR DESCRIPTION
**Pull request by lbruun**
The new Apache license header on all `.java`, `.cpp`, `.c`, `.js` files (etc) started with slash-star-star (the Javadoc introducer). While strictly speaking this is acceptable, the header is not a Javadoc comment, and no present or future Javadoc parser should attempt to regard as a Javadoc comment. Therefore all such occurences are changed to simple slash-star introducer.

For future reference: The following snippet was used to change the files. I tried bash+sed but it never gave me correct result, so I resorted to good old Java. As I bonus, the snippet also checks for Windows line endings.

``` java
package org.apache.netbeans.sourceutils;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

public class ChgLicHeader extends SimpleFileVisitor<Path> {

    private static final List<String> EXCLUDES = new ArrayList<>(Arrays.asList(
            ".gif", ".png", ".jpg", ".PNG", ".pdf",
            ".jar", ".zip", ".ico", ".icns", ".wav",
            ".idb", ".odt", ".gz", ".jar"));

    private static final byte[] AL_JAVADOC_INTRO = "/**\n * Licensed to the Apache Software Foundation"
            .getBytes(StandardCharsets.US_ASCII);
    
    private Map<String, Set<Path>> filesChanged = new HashMap<>();
    private Set<Path> windowsLineEndingFiles = new TreeSet<>();  

    public static void main(String[] args) throws IOException {

        System.out.println("Path: " + args[0]);
        Path path = new File(args[0]).toPath();
        ChgLicHeader fileVisitor = new ChgLicHeader();
        Files.walkFileTree(path, fileVisitor);

        System.out.println("Files changed: ");
        for (String ext : fileVisitor.getFileChanged().keySet()) {
            System.out.println("  " + ext);
            for (Path file : fileVisitor.getFileChanged().get(ext)) {
                System.out.println("        " + path.relativize(file));
            }
        }

        System.out.println();
        System.out.println();

        System.out.println("Files with (supposedly) CRLF line endings: ");
        for (Path file : fileVisitor.getWindowsLineEndingFiles()) {
            System.out.println("  " + path.relativize(file));
        }
    }

    @Override
    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {

        if (attrs.isRegularFile()) {
            for (String excludedExt : EXCLUDES) {
                if (file.getFileName().toString().endsWith(excludedExt)) {
                    return FileVisitResult.CONTINUE;
                }
            }
            if (!usesUnixLineEndings(file)) {
                windowsLineEndingFiles.add(file);
            }

            checkAndRewrite(file);
        }
        return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
        if (dir.endsWith(".git")) {
            return FileVisitResult.SKIP_SUBTREE;
        }
        return super.preVisitDirectory(dir, attrs);
    }

    private void addChangedFileByExtension(String ext, Path file) {
        Set<Path> set = filesChanged.get(ext);
        if (set == null) {
            set = new TreeSet<>();
            filesChanged.put(ext, set);
        }
        set.add(file);
    }

    private void checkAndRewrite(Path file) throws IOException {
        byte[] buf = Files.readAllBytes(file);

        if (usesApacheHeaderWithJavadocIntroducer(buf)) {
            String fileNameStr = file.getFileName().toString();
            int pos = fileNameStr.lastIndexOf('.');
            if (pos > 0) {
                addChangedFileByExtension(fileNameStr.substring(pos), file);
            }

            // New array, which is a copy but with 3rd byte excluded
            byte[] newBuf = new byte[buf.length - 1];
            System.arraycopy(buf, 0, newBuf, 0, 2);
            System.arraycopy(buf, 3, newBuf, 2, buf.length - 3);

            Files.write(file, newBuf);  // rewrite file
        }
    }

    /**
     * Check if file (as represented by byte buffer) has the ASF license header,
     * and the header begins with the Javadoc introducer.
     */
    private boolean usesApacheHeaderWithJavadocIntroducer(byte[] buf) throws IOException {

        if (buf.length >= AL_JAVADOC_INTRO.length) {
            boolean match = true;
            for (int i = 0; i < AL_JAVADOC_INTRO.length; i++) {
                if (buf[i] != AL_JAVADOC_INTRO[i]) {
                    match = false;
                    break;
                }
            }
            return match;
        }
        return false;
    }

    private boolean usesUnixLineEndings(Path file) throws IOException {
        int noOfLF = 0;
        int noOfCRLF = 0;
        byte[] buf = Files.readAllBytes(file);

        for (int i = 0; i < buf.length; i++) {

            if (buf[i] == '\n') {
                noOfLF++;
            }
            if (buf[i] == '\r') {
                i++;
                if (i < buf.length && buf[i] == '\n') {
                    noOfCRLF++;
                }
                noOfLF++;
            }
        }
        return (noOfCRLF == 0);
    }

    public Map<String, Set<Path>> getFileChanged() {
        return filesChanged;
    }

    public Set<Path> getWindowsLineEndingFiles() {
        return windowsLineEndingFiles;
    }
}
```

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I have two comments:
- is there a real reason to change about any file in the repository?
- the usage of an exclusion list sounds dangerous - why not an inclusion list with just "*.java"? This is about javadoc after all

**Comment by lbruun** [comment]
Why all files?  Not sure I understand. Either we decide that this is incorrect behaviour and then we change _all_ files where this occurs, rather than just some of them. Or we decide it is acceptable, and then we change _none_ at all.

Strictly speaking it is only on `.java` files where there I can prove unwanted side-effects from using the Javadoc introducer. The JIRA issue contains an example where you can see one such negative side-effect.

On other files, e.g. `.css`, `.c`, `.js`, etc, I don't think there's any negative side-effect of using `/**`, but I just chose to include them nevertheless. It is just safer that way, for the present and for the future. For example for JavaScript files you have JSDoc (a Javadoc look-alike), which happen to also use `/**` as the introducer.

FYI: The number of files changed by extension are:

```text
  .cpp             12
  .css             17
  .pass           165
  .xjava            1
  .java         24740
  .javax            1
  .hint            39
  .patch            2
  .jj               4
  .jjt              1
  .txt              7
  .c               45
  .js               8
  .aj               2
  .g                2
  .h               52
  .plist            3
  .test            27
  .m                3
  .rc               8
  .my_extension     1
```

**Comment by lbruun** [comment]
I don't think it is any safer to use include list. After all the snippet only change those files which already today use `/**` as the beginning of the license header. The match must be at the beginning of the file. It checks the first 49 bytes of each file to see if there's a match.

If anything the method included too little, not too much, as it doesn't catch those Java files with CRLF which have inadvertently been committed to Apache NetBeans during the past 2 months. Examples:

```text
autoupdate.services\test\unit\src\org\netbeans\modules\autoupdate\services\ExecutablePermissionsTestDisabled.java
autoupdate.services\test\unit\src\org\netbeans\modules\autoupdate\services\InstallEagerModuleTest.java
```

(ok, these aren't examples, these are actually the only ones I've found.  :-) )

**Comment by matthiasblaesing** [comment]
Thank you for explaining. My question came from the the fact, that at least one file in the archive (.gif) was destroyed because someone though it a good idea to do plain text-replacements. And the reference to the example was good, as I'd object changing a few thousand files just for a theoretical problem.

I revisited your modification code and agree, that the approach should be save. In addition, I visited a few of the more exotic formats and i feel save.

Please rebase this on master and I'll pull it in.

**Comment by lbruun** [comment]
Good stuff. Please know that I value your comments. They are always justified and always make me think twice. 
I'll rebase.

**Pull request merged**
