### PR TITLE
[NETBEANS-1440] Fixed BadLocationException on triple click to select …

### PR DESCRIPTION
**Pull request by arusinha**
…text at EOF

Jira Link:https://issues.apache.org/jira/browse/NETBEANS-1440

Steps to reproduce the issue
1.let the very last line in the editor is empty
2.have the editor caret at the very last line
3.have the mouse cursor over the last line as well
4.double click, but don't release on the second click (i.e. down-up-down)
move the mouse to right

### CODE REVIEW

**Comment by jlahoda** [comment]
Please no. While it might be acceptable to do things like this in some cases, I think it would require a good argument on why that's the best solution. In this case, there appear to be at least two alternative fix candidates:
-LineDocumentUtils.getWordEnd apparently returns an offset that is beyond the document's length, so that might be fixed/changed to not do that. Probably simple, and while it might need some more double-checking, probably the best solution/fix.
-EditorCaret.mouseDragged could replace:
offset = LineDocumentUtils.getWordEnd(lineDoc, offset);
with something like:
offset = Math.min(LineDocumentUtils.getWordEnd(lineDoc, offset), c.getDocument().getLength())
but that feels somewhat hacky (i.e. why getWordEnd even returned the offset that is too high), but would still be better than catching the BadLocationException.

**Comment by arusinha** [comment]
Thnaks @jlahoda ,I had implemented the review comments in latest commit.

**Comment by lkishalmi** [comment]
I'm not sure if this is the right way to fix it. 
https://github.com/apache/incubator-netbeans/blob/b54acfa82d2bc32ee63841191939a044fa0fbcd1/ide/editor.lib2/src/org/netbeans/modules/editor/lib2/DocUtils.java#L212 is actually used only twice,
once it is called with offset, docLenght() +1 on the other time offset, docLenght() (this one later causing the excepion to be thrown. I do not think that the intent of the two validation would be different. Changing the validation to docLenght() +1 in both calls, removes the exception. Though I'm not sure if that would be the right solution either. unfortunately the hg.netbeans.org is down so I can't check the code why is it called so different in those cases.

**Comment by arusinha** [comment]
Fix:  had corrected  getWordEnd API of TextSearchUtils class in latest commit

**Comment by arusinha** [comment]
@lkishalmi , can you please review the fix

**Comment by lkishalmi** [comment]
I need to test this. What happens if there is no EOL character at the end of file?

**Comment by arusinha** [comment]
If last character is not  '\n'  then there is no issue in double clicking and dragging the mouse to select text

**Comment by arusinha** [comment]
@lkishalmi , request you to review the PR

**Comment by jlahoda** [comment]
Seems OK to me.

**Comment by lkishalmi** [comment]
Tested. Works. The code seems reasonable.

**Pull request merged**
