### PR TITLE
[NETBEANS-1074] : module review web.monitor

### PR DESCRIPTION
**Pull request by arusinha**
Changes.
1. Added licenseinfo.xml for image file
2.  servlet-2.3.jar  is not present in maven repo, it is now replaced with generated jar from servlet-api2.4.jar and jsp-api-2.0.jar
3. Added license header for l10n.list,monitor.dtd

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
The switch to the servlet 2.4 api is ok (though 2.3 is available: javax.servlet:servlet-api:2.3 - keep your change).

I would skip the combination of the jar. The file is not redistributed  and only used to build the server plugin. Instead of combining, just adjust the classpath in the `server.cp.extra` property in `project.properties` should do it.

The license of server and jsp api looks dubious. Both file originate from the _apache_ tomcat project. The ASFs policy requires project to distribute its source under the apache license, why would they choose the CDDL?

**Comment by matthiasblaesing** [comment]
For the proposed changes (btw: a new commit would be easier to comment on):
2.: Both jars need to be on the classpath - there is no a) or b) here (the property is used in the `compile-server` target)
3.: I don't know where mvnrepository.com gets its info from, but I don't see why the ASF or the tomcat PMC would not choose the ALv2. There is no indication, that this file is covered by CDDL|GPLv2. I would switch to ALv2, indicated by the fact that the Apache Foundation is listed as author. In fact I found org.apache.tomcat:tomcat-jsp-api:9.0.12 which is ALv2 licensed for the 2.3 jsp api.

**Comment by arusinha** [comment]
> For the proposed changes (btw: a new commit would be easier to comment on):
> 2.: Both jars need to be on the classpath - there is no a) or b) here (the property is used in the `compile-server` target)
> 3.: I don't know where mvnrepository.com gets its info from, but I don't see why the ASF or the tomcat PMC would not choose the ALv2. There is no indication, that this file is covered by CDDL|GPLv2. I would switch to ALv2, indicated by the fact that the Apache Foundation is listed as author. In fact I found org.apache.tomcat:tomcat-jsp-api:9.0.12 which is ALv2 licensed for the 2.3 jsp api.

Review comments implemented in last commit

**Comment by matthiasblaesing** [comment]
Thank you - while investigating the version difference between the `servlet-api` and the `jsp-api` dependcy, I noticed, that the `jsp-api` is not used. The code in `serversrc` only depends on the `servlet-api`.

For the `servlet-api-6.0.13-license.txt` please add a `Type: compile-time` header.

With these changes I think this is good to be merged.

**Comment by arusinha** [comment]
> Thank you - while investigating the version difference between the `servlet-api` and the `jsp-api` dependcy, I noticed, that the `jsp-api` is not used. The code in `serversrc` only depends on the `servlet-api`.
> 
> For the `servlet-api-6.0.13-license.txt` please add a `Type: compile-time` header.
> 
> With these changes I think this is good to be merged.

Changed incorporated in last commit

**Comment by arusinha** [comment]
by-mistake clicked the "comment & close" button

**Comment by matthiasblaesing** [comment]
Thank you - looks good.

**Pull request merged**
