### PR TITLE
[NETBEANS-997] Fix for unable to download and create GlassFish server / support for installing GF 4.1.2 & GF 5.0

### PR DESCRIPTION
**Pull request by peedeeboy**
Root cause of issue
---------------------
1) NB first looks for a .txt file for the relevant Glassfish version on serverplugins.netbeans.org (it will follow redirects to try and find it).
2) If NB finds the txt file, it reads the first line, which contains the directory path for that version of glassfish (see http://serverplugins.netbeans.org/glassfishv3/post71v3-1-2.txt which is still up!)
   2a) The directory path is appended to the hardcoded base URL, http://download.java.net
   2b) NB will then try and download the glassfish .zip from this URL (but won't follow redirects!)
3) If NB fails to find/parse the .txt file, it will try and download the .zip from the direct download.java.net link (the one with the ?nbretriever=fallback querystring), but won't follow redirects
 
Because serverplugins.netbeans.org no longer exists & there are now 301 redirects on the download.java.net URLs from http to https, even the fallback was failing.

What this patch does in a nutshell
--------------------------------------
No longer parses a .txt file for the location of Glassfish.  The enum representing Glassfish versions still has two URLs.  NB will now expect a .zip file containing GF at either.  NB will follow redirects on the indirect URL, if that fails, NB will still fallback to the direct URL, which NB expects to be valid (currently points to download.oracle.com)

Code for downloading/installing GF 5.0 de-commented.  Code for downloading/installing GF 4.1.2 added.

Outstanding questions
-------------------------
Currently, both direct and indirect URLs point to same location.  Geertjan suggested on the mailing list that the GF binaries could be hosted at http://netbeans.osuosl.org/binaries

Do we want to do this? NB could first try and download Glassfish from netbeans.osuosl.org/binaries and fallback to downloading from download.oracle.com, or vice versa.  Let me know! :)

To test
--------
1) Servers tab -> Right-click Servers -> Add Server
2) Select "Glassfish Server" -> Next
3) Browse to "Install Location" -> check "I have read and accept the licence agreement" -> Download now...
* Before PR : dialog will be displayed with choice of GF 3.1.2.2, 4.0, 4.1, 4.1.1
* After PR: choice will be GF 3.1.2.2, 4.0, 4.1, 4.1.1, 4.1.2, 5.0
4) Choose a glassfish version
* Before PR: After a few seconds, "Does not exist" error message will be displayed
* After PR: GF will download and install normally

Files changed
-------------
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
* Added new string for Glassfish 4.1.2

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
* Changed download location to remove references to serverplugins.netbeans.org and download.java.net and to reference valid download.oracle.comm https locations
* Added entry to enum for Glassfish 4.1.2
* Updated iterator of supported Glassfish versions to include 4.1.2 and 5.0

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/AddServerLocationVisualPanel.java
* Updated download prefix to https://download.oracle.com
* Updated URL to licence to valid location: https://javaee.github.io/glassfish/LICENSE

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/Retriever.java
* getDowloadLocation() now uses HEAD rather than GET requests, as it is now just checking headers and not downloading any content
* no longer tries to parse a text file to get Glassfish download location, instead on HTTP 200, it just checks that content-length > 0 bytes

enterprise/glassfish.common/test/unit/src/org/netbeans/modules/glassfish/common/wizards/RetrieverTest.java
* Unit Test updated to handle redirect, and check both indirect and direct download locations work correctly

enterprise/glassfish.common/test/unit/src/org/netbeans/modules/glassfish/common/wizards/TestServer.java
* Test server updated to simulate redirects
* Test server only serves up the .zip file on GET requests, not HEAD requests

enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
* Updated so that Netbeans will now recoginse a Glassfish 4.1.2 installation as such, rather than falling back to recogising it as Glassfish 4.1

enterprise/glassfish.common/test/unit/data/nottaDir-4_1_2.jar
enterprise/glassfish.common/test/unit/data/subdir/

* UtilsTest unit test was failing (nothing to do with this PR) as it was expecting these files, so added them...

### CODE REVIEW

**Comment by geertjanw** [comment]
Excellent, I think we should merge this.

**Comment by geertjanw** [comment]
Eclipse GlassFish 5.1 is available, from the Eclipse Foundation. Maybe support could be added for downloading that too?

**Comment by peedeeboy** [comment]
Provided nothing major has changed, downloading & installing should be a simple matter of adding new entries for GF5.1 to necessary enums/properties files.

The slightly bigger piece of work would be updating NB UI to dynamically change the target of the licence link, so that if GF5.1 were selected, it would point to the new EF licence

**Comment by geertjanw** [comment]
Can you explain, i.e., which enum/properties files need to be changed, or do it? Would be great to be able to support 5.1, since that's the latest release.

**Comment by peedeeboy** [comment]
Sure thing! I'll try and find some time tonight/tomorrow to create a feature request in Jira for GF5.1, with the steps I think need to be followed - somebody can have a crack at it to get in it for 11.0 (I'm going to be away for a couple of weeks..)

**Comment by geertjanw** [comment]
Would be great, thanks!

**Comment by geertjanw** [comment]
Here's the related download page: https://projects.eclipse.org/projects/ee4j.glassfish/downloads

**Comment by juneau001** [comment]
Thanks for doing this work @peedeeboy.  It would be great if GlassFish 5.1 could be added, as it marks a major milestone for the platform.  I think that GlassFish 3.1.2.2 should be removed as a choice.   It is probably a bad practice for developers to be using such an old server.  Thoughts?

**Comment by geertjanw** [comment]
+1 

I'll leave it to you Josh and other Java/Jakarta EE aficionados to recommend minimum/recommended release numbers for GlassFish -- and ideally @peedeeboy's instructions should be sufficient for this to be updated/added/changed as needed without too much work.

**Comment by matthiasblaesing** [comment]
Maybe this helps, the glassfish is available on maven central:
https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/5.1.0/
https://search.maven.org/search?q=g:org.glassfish.main.distributions%20AND%20a:glassfish&core=gav
The same is true for payara, if anyone is interested in that one:
https://repo1.maven.org/maven2/fish/payara/distributions/payara/5.184/
https://search.maven.org/search?q=g:fish.payara.distributions%20AND%20a:payara&core=gav

**Comment by peedeeboy** [comment]
https://issues.apache.org/jira/browse/NETBEANS-2130

The Eclipse Download link is a PHP script, rather than a direct link to a .zip file, so Resolver.java may also need to be updated to deal with that. 

HTH!  I'll be back in a couple of weeks, and if no-one else has had a crack at it, I will then :)

**Comment by geertjanw** [comment]
Excellent, thanks for the work here. I will take a look.

The download from here would be good because (a) it is from Maven Central and (b) it is a ZIP file, so Resolver.java would not need to be updated:

https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/5.1.0/glassfish-5.1.0.zip

**Pull request merged**
