### PR TITLE
org.jdesktop.layout library is under LGPL and cannot be used.

### PR DESCRIPTION
**Pull request by jlahoda**
Luckily, replacement classes are part of JDK since JDK 6.
References to the module/library that appeared important enough have been deleted.
Some more references remain, some needed (form should still handle the library is available), some hopefully benign (in tests).

### CODE REVIEW

**Comment by geertjanw** [comment]
Thanks for this work, great to have this covered now.

**Comment by geertjanw** [comment]
+1 for merging this.

**Comment by junichi11** [comment]
@jlahoda  It seems that the license headers are removed from *.form files automatically.

**Comment by jlahoda** [comment]
@junichi11, right, thanks. I've forgot about that (and missed it when looking at the patch). Sorry for that. Will fix tomorrow.

**Pull request merged**
