### PR TITLE
Include webcommon into the release

### PR DESCRIPTION
**Pull request by sdedic**
Webcommon cluster has been reviewed and separated into its cluster directory, the next step is to include it in the Apache Netbeans release

### CODE REVIEW

**Comment by geertjanw** [comment]
Great that you're doing this, but something broke.

**Comment by junichi11** [comment]
```
unzip:  cannot find or open ../nbbuild/build/basic-src*, ../nbbuild/build/basic-src*.zip or ../nbbuild/build/basic-src*.ZIP.

No zipfiles found.
```
Here?

**Comment by sdedic** [comment]
Yes, the .travis.yaml supposes `basic` cluster name, I renamed the final product to `release`. Not sure if the config should use an (again) explicit `release`, or `*` to satisfy all :)

**Comment by geertjanw** [comment]
There's a problem with Travis, otherwise I would merge this. Can it be merged?

**Comment by geertjanw** [comment]
OK, looks like you responded to this, looks good from everyone's perspective here, so I am merging.

**Pull request merged**
