### PR TITLE
[NETBEANS-1074] Module Review web.struts

### PR DESCRIPTION
**Pull request by sarveshkesharwani**
- Mavenization of jars
- I couldn't find a maven equivalent of web.struts-external-resources.zip, so I accumulated the contents (tld files) from different locations. I did not add struts.xml file because I noticed that it merely contained the information about dependent maven jars, and now we specify the jars in binaries-list file. Does this seem like the right approach?

### CODE REVIEW

**Comment by sarveshkesharwani** [comment]
@rtaneja1 , Could you please take a look at this too?

**Comment by rtaneja1** [comment]
Changes look fine to me, please make sure test results are same as before changes. Also run ant -Dcluster.config=full verify-libs-and-licenses to check that there are no warnings in this module. 
Not sure about license for struts-config_1_2-custom.dtd, struts-config_1_3-custom.dtd, not included in this PR?

**Comment by sarveshkesharwani** [comment]
@rtaneja1 , There was on overlapping jars warning in verification. I have added the changes to `ignored-overlaps` file. I tried running the tests, but the tests are failing due to the same reason with/without my changes.

I could not see any place where `struts-config_1_2-custom.dtd` or `struts-config_1_3-custom.dtd` are being used in the codebase, so I think it would be okay if we don't include them.

I see that there is a merge conflict. I will resolve it and squash the commits once this PR is approved.

**Comment by matthiasblaesing** [comment]
I see a few problems - I pushed an updated branch here:

https://github.com/matthiasblaesing/incubator-netbeans/tree/github-pr-940

- Use the declarative method for copying files and let the build system do the work
https://github.com/matthiasblaesing/incubator-netbeans/commit/aadd5122b4ceac942ef9e5eba1fb1bc6a1d1f82c
- Include DTD/XML/TLD files with correct license attribution 
https://github.com/matthiasblaesing/incubator-netbeans/commit/463af8c90453e028a12e214d03333024d5249555
If you just extract the DTD/XML/TLD files, you won't get the license information. From the perspective of the build system the external dependency is not used and as such the license/notice is not included. My change moves the license information into the `licenseninfo.xml` file where it can be extracted from. 
- The referenced libraries are almost all Apache libraries and normally they come with NOTICE files, which we are required to analyse and if appropriate include in our NOTICE file. Just adding the `NOTICE.txt` in `external` does not work, as the build system won't promote the file into build binaries. The build system was enhanced to pick up a `<basename>-notice.txt` file, if it would pick up a `<basename>-license.txt` file and include the contents of that file into the final netbeans NOTICE file. I removed the javadoc license files and replaced them with a `Files` header in the main artifact license file. For `antlr` the license is not correct. ANTLR _2_ is public domain and a matching license file is already present in the `nbbuild/licenses` directory. These changes are committed as: https://github.com/matthiasblaesing/incubator-netbeans/commit/81878a431221da0f801dccca9f2bda797539dddb
- The struts javadoc does not need to be rebuild everytime `build-init` is called. It was be conditionalized and moved to embedded `zipfileset`s instead of expanding the zip and rezipping them: https://github.com/matthiasblaesing/incubator-netbeans/commit/3daed9b79b2fc7810c9744af743501079a77550f

In the second commit above I also rebuild `struts-config_1_3-custom.dtd`. It is trivially derived from `struts-config_1_3.dtd`, the process is described in the document itself. This also fixed a build failure, as without `struts-config_1_3-custom.dtd` the build just does not work. The license for that file than results from the original file.

The `web-app_2_3.dtd` is not referenced and thus removed from the codebase.

**Comment by sarveshkesharwani** [comment]
@matthiasblaesing , I see that instead of collecting the `*.dtd` files from different jars, you added them directly along with licenseinfo.xml. The rest of your changes also make sense. 

Without `struts-config_1_3-custom.dtd`, was the build failing at the root folder? Because, I tried building just the `web.struts` module without `struts-config_1_3-custom.dtd` file and the build was passed for the module.

So, we have two options to go forward from here, I can close this PR and you can merge your commits, as they contain all the necessary changes exhaustively, or I can cherry pick your commits, squash them, and then merge the changes through this PR. Which way do you think we should go forward with?

**Comment by matthiasblaesing** [comment]
@sarveshkesharwani I created a squashed version with my suggestions applied:
https://github.com/matthiasblaesing/incubator-netbeans/tree/github-pr-940-2
You are credited as the author, I'll be present as committer. If you agree with the changes, I'll merge the changes to master as presented in the above referenced branch. in that process I would also let github close this PR.

For `struts-config_1_3-custom.dtd`: Yes for me the build failed. I think I know what happend: You did a build with the file present, removed the file and rebuild. This could have worked, if the build system did not detect changes, it would not try to rebuild the generated classes and it would look like building without the file succeeded. I ran the build after running `git clean -f -x -d` which basicly removes everything not part of the repository.

**Comment by sarveshkesharwani** [comment]
@matthiasblaesing, I took your changes and built the module, everything works just fine. There are no verification errors either. I think we can merge it. Thank you for your help!

**Comment by matthiasblaesing** [comment]
Thank you for checking - I just merged the changeset, so closing this.

**Pull request closed without merging**
