### PR TITLE
[NETBEANS-491] use framework support to disable error reporting

### PR DESCRIPTION
**Pull request by rtaneja1**
Removed change done in #471 to invoke JIRA url in browser on Review and Report Problem button click. Framework already supports disabling issue reporting via ERROR_URL page.

### CODE REVIEW

**Comment by geertjanw** [comment]
Can we come to a resolution on this point so that we can wrap it up?

**Comment by geertjanw** [comment]
So, is this URL ok: http://netbeans.apache.org/misc/bug_report.html

**Comment by neilcsmith-net** [comment]
@geertjanw it should be without the `.html` suffix IMO.  I'm also not sure about putting it under misc - though having one subsection used for all things linked to from the IDE might be a good idea, and possibly version specific so that update centre links can be there too.  And all links should be `https` unless we have a very valid reason for them not to be - the website doesn't currently enforce that but probably should.

So, my vote would probably be something like `https://netbeans.apache.org/nb90/issues`

I pinged @vieiro earlier for his thoughts on this - he's looked a lot more at the `.htaccess` and update centre config on the site.

**Comment by rtaneja1** [comment]
The ERROR_URL page http://netbeans-vm.apache.org/misc/bug_report.html is not displayed to the users in browser. This is used internally by the error reporting framework for submitting errors reports. The display text on page is shown in a JEditorPane. User should click on the JIRA link available on this JEditorPane to navigate to NetBeans JIRA page in browser.

**Comment by rtaneja1** [comment]
Hi @neilcsmith-net @vieiro , Can you please confirm if we should use url : https://netbeans.apache.org/nb90/issues for ERROR_LOG page.

**Comment by neilcsmith-net** [comment]
@jkovalsky create what?! :smile: Are we going with a redirect to JIRA, or a landing page, or the page Geertjan mentions?

In my opinion, all links inbound from the IDE should be under a specific root, possibly with a version, not because the content they go to is version specific, but so that we can manage and track redirects now and in future in a version-orientated way.  That's why I requested @vieiro input because he was looking at this for update centers.

**Comment by geertjanw** [comment]
Create https://netbeans.apache.org/nb90/issues, since it does not exist.

I don't understand why it needs to be version specific, hence this is why I suggest https://netbeans.apache.org/participate/report-issue.html.

**Comment by jkovalsky** [comment]
Guys seriously, did you read Reema's question? She needs an HTML page which she reads and displays in a dialog which is opened when NetBeans user encounters an exception. We cannot display 60 page downs long [report-issue.html](https://netbeans.apache.org/participate/report-issue.html) page.

You requested that page located under https://netbeans.apache.org so I thought you would simply create https://netbeans.apache.org/issues.html page with same content as mine http://netbeans-vm.apache.org/misc/bug_report.html page. There is no need for any redirection here if I don't miss something obvious.

**Comment by geertjanw** [comment]
Content here:

http://netbeans-vm.apache.org/misc/bug_report.html

...is not the same as here:

https://netbeans.apache.org/participate/report-issue.html

The long list of components on the page above was not needed.

**Comment by neilcsmith-net** [comment]
@jkovalsky I think there might be some confusion here. I assumed we were opening this in the user's browser?

@geertjanw the point of having separate links, versioning and redirects is to able to manage inbound links from the IDE independently from website structure in future.

**Comment by neilcsmith-net** [comment]
@geertjanw just that by doing this we can always redirect links from the IDE wherever is most appropriate without breaking links used by people browsing, googling, whatever.  Or send people elsewhere if they're on a legacy version.  Or track usage.  It's easier to separate now than wish we had later - we don't *need* to ever use that functionality.  The only thing relevant specifically to this PR is making sure we have a unique inbound link here.

**Comment by geertjanw** [comment]
So, must Reema hardcode https://netbeans.apache.org/nb90/issues when the "Review and Report Problem" button is clicked? Or must a different URL be used (which one) and if not can you create that page?

**Comment by neilcsmith-net** [comment]
The PR for the website above has added temporary redirects for `/issues`, `/nb/9.0/issues` and `/issues/9.0`.  I personally think we should put all inbound links under something like `/nb/XX` but if no-one else agrees, plain /issues is there!  However, if this is a dialog not the user's browser, then I'm not sure that's the right target?

```
+Redirect 307 /issues https://netbeans.apache.org/participate/report-issue.html
+Redirect 307 /nb/9.0/issues https://netbeans.apache.org/participate/report-issue.html
+Redirect 307 /issues/9.0 https://netbeans.apache.org/participate/report-issue.html
```

**Comment by geertjanw** [comment]
Just for clarity here, @neilcsmith-net, what should the URL be that should be used to display the page in a JEditorPane?

**Comment by jkovalsky** [comment]
I think https://netbeans.apache.org/nb/9.0/issues.html for NetBeans 9.1, https://netbeans.apache.org/nb/9.1/issues.html for NetBeans 9.1 and so on even though the content of the files will be exactly the same which in my opinion makes no sense hence my proposal to save it into https://netbeans.apache.org/issues.html file. Not talking about necessity to update the branding file for no reason. :)

**Comment by geertjanw** [comment]
I agree with you, except that @neilcsmith-net has an intention here that we do not understand yet.

**Comment by geertjanw** [comment]
It seems clear that @neilcsmith-net wants to do analysis per release, in some way, that's the reason for the version specific scheme, i.e., it's not about the content being the same, but the URL being different so that some kind of analysis can be done, hoping @neilcsmith-net can provide more details.

**Comment by neilcsmith-net** [comment]
Following up on this and private email discussion here - 

There are two concerns - one putting all IDE links under a common root path (eg. `/nb`) which is more important.  Gives us flexibility in handling those, in terms of .htaccess, robots.txt, hosting and build - such as possibly not having anything to do with JBake!  You may have noticed my quick fix got filtered out in by JBake anyway :confounded: - new PR up at https://github.com/apache/incubator-netbeans-website/pull/37 which hopefully works now!

In that I've also moved it to `https://netbeans.apache.org/nb/issues.html` so no more version number but common root path. Version was thinking about potential future flexibility rather than anything specific that we need to do / can do now (based on some past experiences).  We can still add that later just as well, so let's keep without for now.  I also realise it would have added an extra step between releases, but there are already links that will need updating between versions - I have an audit file that has been shared with most of those existing links.

Query about form (via email) was more about the link than it being there - that will disappear at some point too?

**Comment by jkovalsky** [comment]
Excellent, https://netbeans.apache.org/nb/issues.html should work fine. Thank you @neilcsmith-net!

**Comment by geertjanw** [comment]
OK, merging.

**Pull request merged**
