### PR TITLE
[NETBEANS-410] (partial) Moving test data into the tests themselves.

### PR DESCRIPTION
**Pull request by jlahoda**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Why don't we just add a licenseinfo.xml stating, that

a) these binary files are ALv2 licensed and
b) that the files are need as they are as they are regression tests and can't be recreated on the fly and
c) that the files can't hold license info themselves

**Comment by jlahoda** [comment]
(Please see Justin's e-mail for context:
https://lists.apache.org/thread.html/73ce8a13d5c13b56c300e4aad1e9e9bc8351ea6e836f5dc60a55cfaa@%3Cgeneral.incubator.apache.org%3E
)

I think there are many directions that we could take:
-do nothing - this means we will argue at every release if we can or cannot release. I suspect we will have other more important things to argue about.
-add licenseinfo.xml as you suggest (or some other comment somewhere), but I suspect it will basically lead to the option above (i.e. the argument won't be if it is documented, but if having a class file in the distribution is allowed).
-delete the tests, eliminates any risk of not being able to release due to these tests, but test coverage will be smaller, and sets a wrong precedent.
-download the test files as an external binary
-exclude the tests from the source distro (but some will argue that the source distro and the git tag are not the same)
-attempt to do some other workaround, like this one.

Frankly, out of all these bad options, it seems this one is a fairly viable.

**Comment by matthiasblaesing** [comment]
I won't interfere if this is merged (or Geertjans version).

**Comment by JaroslavTulach** [comment]
Thanks for eliminating the disturbing files.

**Comment by geertjanw** [comment]
Thanks! Will close the other one by me.

**Pull request merged**
