### PR TITLE
[NETBEANS-54] Module Review maven.indexer

### PR DESCRIPTION
**Pull request by rosslamont**
- binaries-list updated to use maven coords where possible
   - Need solution for apache maven indexer-core SNAPSHOT - suggestion
		below
- no notices required - already apache licensed except for 
		javax.annotation-api which is presumably ok (has embedded cddl 
		license)
- file NOTICE-patched-indexer-core-6.0.0 and mvn-indexer.patch not 
		licensed pending solution above.

### CODE REVIEW

**Comment by geertjanw** [comment]
Anything more needs to be done here?

**Comment by rosslamont** [comment]
Yes. Not sure what to do about the binary  org.apache.maven.indexer:maven-indexer:6.0-SNAPSHOT

My comment from earlier: 

"Regarding org.apache.maven.indexer:maven-indexer:6.0-SNAPSHOT, I suggest we clone that into apache/netbeans owned git, apply the patch, change the maven coordinates to make it netbeans owned and deploy back to maven central.”

Not sure how you want to approach that.

**Comment by geertjanw** [comment]
I think I'd leave them unchanged for the moment, i.e., we do not have to get everything from Maven, right now this minute. Do as much as you can in terms of the other JARs, i.e., the Lucene JARs, and let's handle that patch as a separate issue.

**Comment by rosslamont** [comment]
No worries Geertjan. Everything else is done.  I'll log an issue regarding the patch and update the APIReview doc , but you can merge this one in I think...

**Comment by rosslamont** [comment]
actually on second thoughts I should add a copyright notice to the patch, so hold off merging.

**Comment by rosslamont** [comment]
OK, I've pushed a squashed version with
 - copyright notice in the patch
 - exclusion for NOTICE-patched-indexer-core-6.0.0" (no degree of creativity)

Good to go now.

**Comment by junichi11** [comment]
I've sorted rat excludes. (This PR already had the conflicting file(nbbuild/build.xml))

**Comment by geertjanw** [comment]
Should this be merged or closed?

**Comment by rosslamont** [comment]
I didn't realise I could resolve conflicts from GitHub.  I've done that now, but that's made a mess after the alphabetisation.  So hold up a bit and I'll sort it out.  Hopefully have a clean squashed commit for you soon.

**Comment by rosslamont** [comment]
OK, all sorted, but I haven't squashed the merge masters.  I'm not that familiar with git/squashing - is it safe to squash the merge commits?  Just a regular squash?

**Comment by javydreamercsw** [comment]
In all my GitHub projects I can configure how PR are handled. From allowing all types (merge, squash, etc.) to selecting one or some of them.

If squashing is the preferred way it should be probably the only option. Usually the person(s) configured to merge to trunk can choose which one.

image

**Comment by rosslamont** [comment]
Thanks Javier,

I didn’t know about that.  Is this something committers do? Or something I was meant to do as a contributor?  

I mis-spoke in my prior comment, what I was concerned about was squashing a conflict merge, i.e. the additional commits are to do with sorting out the conflict with base (I don’t know why GitHub made me do 2 commits.  I read somewhere git can get confused with how it tracks conflicts if you mess around with squashing.

Is there something else I can do to finish this as a contributor?

Cheers
Ross

**Comment by javydreamercsw** [comment]
@rosslamont this is done by the repository admins. What I meant is that if the admins want it merged, squashed or rebased that can be done with one click most of the time. That's the beauty of GitHub.

It can be configured to only have one option on that dropdown for the users with write access or all.

**Comment by rosslamont** [comment]
OK, not sure what is holding this back, but I've done all I can here. Ready to merge

**Comment by junichi11** [comment]
Probably, `rebase` is preferred than `merge` when a PR is provided.

I may be wrong but...
- Just in case, save your changes e.g. https://patch-diff.githubusercontent.com/raw/apache/incubator-netbeans/pull/163.diff
- `git remote add upstream https://github.com/apache/incubator-netbeans`
- `git checkout master`
- `git pull upstream master`
- `git push origin master`
- `git checkout maven_indexer`
- `git reset --hard [commit id]` (reset your merges)
- `git rebase master maven_indexer` (if there are conflicts, fix them, then, add them, `rebase --continue`)
- `git push origin maven_indexer` (probably, need `-f` option to overwrite. i.e. `git push -f origin maven_indexer`)

Anyone, Are these OK?

**Comment by matthiasblaesing** [comment]
Merged - thank you.

**Pull request merged**
