### PR TITLE
Made Gradle to be downloaded from hg.netbeans.org

### PR DESCRIPTION
**Pull request by lkishalmi**
Just uploaded the gradle runtime to hg.netbeans.org. If somebody has problem to download it from it's original location.
It is possible that I could make it work with the standard NetBeans binary download mechanism, so do not merge this yet.

### CODE REVIEW

**Comment by geertjanw** [comment]
Would recommend to not use hg.netbeans.org but the one Emilian arranged, in Oklahoma or somewhere.

**Comment by geertjanw** [comment]
I mean here: http://netbeans.osuosl.org/binaries/

**Comment by emilianbold** [comment]
Yes, replace it with http://netbeans.osuosl.org/binaries/2564503471E1FC18A4E7D2A120BC567EA3B26AA4-gradle-4.10.2-bin.zip

**Comment by lkishalmi** [comment]
Well, the upload works on hg.netbeans.org, the Oregon State University (as an Oregonian myself, I'm kind of happy about that) syncs that in 24 hours, but I did not want to let our architect down, that's why this link is being to used at the moment.

As I said I try to make it work with the standard external download mechanism.

**Comment by JaroslavTulach** [comment]
Here is a [different fix](https://github.com/apache/incubator-netbeans/commit/f2c5275430ef882a26c6716feb120a53f7c48ac8) for your consideration. It sets the same proxy as our `DownloadBinaries` task is using to the Gradle subprocess. With that changes I am able to build fine.

I am not sure which approach is better.

**Comment by emilianbold** [comment]
The OSUOSL link works already.

**Comment by matthiasblaesing** [comment]
Another alternative, that uses the netbeans infrastructure: https://github.com/matthiasblaesing/incubator-netbeans/commit/775f14eb6138084c0f671c0f00870048ee8cd0d0

**Comment by lkishalmi** [comment]
Wow @matthiasblaesing please create a PR from that commit! I'm going to close this one in favor of that!

There is only one minor thing. Theoretically the .gitignore might not required to be changed, unless someone would like to open the project with the other Gradle plugin.

**Pull request closed without merging**
