### PR TITLE
[NETBEANS-54] Module Review schema2beans

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Waiting for someone to review, will then merge this.

**Comment by struberg** [comment]
+1 to apply it.

**Comment by junichi11** [comment]
It seems that failed unit tests increase.

**Comment by geertjanw** [comment]
Failed unit tests increase because of this pull request?

**Comment by struberg** [comment]
Weird, the 2 commits just add ALv2 headers to a bunch of files.

**Comment by junichi11** [comment]
In my environment,
Before: 24 tests success, 8 tests fail
After: 16 tests success, 16 tests fail

So, perhaps, there are problems in some schema2beans/test/unit/data files.

**Comment by geertjanw** [comment]
Can you see which ones fail? I don't see a difference in terms of failed tests.

**Comment by junichi11** [comment]
I attach results as screenshots. Sorry in Japanese UI.
Before:
nb-54-pr-178-before

After:
nb-54-pr-178-after

e.g. testExeptions
log:
```
------------- ---------------- ---------------
Testcase: testExceptions(tests.MainTest):	FAILED
DIFF: incubator-netbeans/schema2beans/build/test/unit/work/t.M/e/testExceptions.diff
  9   Finished compiling: 0
 10   out: TestExceptions - creating the bean graph
 11   out: TestExceptions - Hit Exception: class org.netbeans.modules.schema2beans.Schema2BeansException
 12 - out: TestExceptions - Doc root 'EXCEPS' not found in the DOM graph! Found 'foo' instead.
    + out: TestExceptions - Doc root 'EXCEPS' not found in the DOM graph! Found '#comment' instead.
 13   Finished running TestExceptions: 0

org.netbeans.junit.AssertionFileFailedError: DIFF: incubator-netbeans/schema2beans/build/test/unit/work/t.M/e/testExceptions.diff
  9   Finished compiling: 0
 10   out: TestExceptions - creating the bean graph
 11   out: TestExceptions - Hit Exception: class org.netbeans.modules.schema2beans.Schema2BeansException
 12 - out: TestExceptions - Doc root 'EXCEPS' not found in the DOM graph! Found 'foo' instead.
    + out: TestExceptions - Doc root 'EXCEPS' not found in the DOM graph! Found '#comment' instead.
 13   Finished running TestExceptions: 0

	at tests.MainTest.compareReferenceFiles(MainTest.java:542)
	at org.netbeans.junit.NbTestCase.compareReferenceFiles(NbTestCase.java:1272)
	at tests.MainTest.tearDown(MainTest.java:512)
	at org.netbeans.junit.NbTestCase.runBare(NbTestCase.java:500)
	at org.netbeans.junit.NbTestCase.run(NbTestCase.java:275)
```

If I remove the license header of `schema2beans/test/unit/data/TestExceptions.xml`, `testExeptions` succeeds.

If you cannot reproduce this, something may be wrong with my environment.

**Comment by geertjanw** [comment]
It seems to me that these are all "test data for which the addition of a source header would cause the tests to fail" -- i.e., these do not require a license header (https://www.apache.org/legal/src-headers.html). 

I think these should be included in the Rat report exclusions.

**Comment by junichi11** [comment]
I also think so. Test data are already excluded in some modules because tests fail, probably.

**Comment by struberg** [comment]
Or fix the test or the tested code to be ok with that header?

**Comment by geertjanw** [comment]
I would suggest not for the first incubator release of Apache NetBeans (incubating). I.e., for the first release, I propose we handle these via Rat exclusions, we create an issue to document the need for this to be solved in a better way, and leave it at that for the moment.

**Comment by struberg** [comment]
perfectly fine for me. Do we want to create a low-prio ticket for it so we can better track it?

**Comment by geertjanw** [comment]
Will create low-prio ticket and have excluded these files via Rat exclusions, so closing this PR.

**Pull request closed without merging**
