### PR TITLE
[NETBEANS-1074] Module Review j2ee.weblogic9

### PR DESCRIPTION
**Pull request by arusinha**
Changes:
1. External zip was deleted instead generated schema files( total 803 .java files)
     present inside ext zip was added back with  Apache license header.
2. Image files are added to licenseinfo.xml.

### CODE REVIEW

**Comment by geertjanw** [comment]
Any reason not to merge, can someone who has reviewed other similar pull requests take a look at this one?

**Comment by matthiasblaesing** [comment]
I think this should be tackled differently. Generated source files are basicly useless under version control. They will rot and at some point stop working. The idea as I see it is:

- take the XSD
- assume that the license does not carry over to generated code
- distribute the generated code without the XSDs

I just realized how well the glassfish is licensed (I have yet to find a source file that has no license info).

So is there a source for the weblogic XSDs, so that we could get them at build time and generate the source files then?

**Comment by arusinha** [comment]
I had earlier send mail to Weblogic team seeking their help for license info on Weblogic schema files and they replied back stating these Weblofic schema files are not licensed to be used in NetBeans. 
So I  went forward and used only generated java files instead for external schema files after discussing the same with Geertjan and team

Those external files are still available in  jet-main repository
https://hg.netbeans.org/jet-main/file/default/j2ee.weblogic9/src/org/netbeans/modules/j2ee/weblogic9/resources

We need all  .xsd, .dtd and .mdd files(total 57 files) from that location. 

I had mailed you the mail chain that followed on the license help we seek from Weblogic team.

Please advice whether  generated java files can be used or we need to check-in those external schemas.

**Comment by arusinha** [comment]
Closing the PR , Plan to remove the module from release.

**Pull request closed without merging**
