### PR TITLE
[NETBEANS-1074] : module review j2ee.jboss4

### PR DESCRIPTION
**Pull request by vikasprabhakar**

### CODE REVIEW

**Comment by vikasprabhakar** [comment]
@matthiasblaesing can we use "LGPL-2.1" license for dtd files?

**Comment by matthiasblaesing** [comment]
I wanted to open a ticket with apache legal with that question. I found this:

https://issues.apache.org/jira/browse/LEGAL-408

@ehsavoie already opened the issue and my reading of the answer is: We can't include/distribute the schema (that was IMHO clear already) and we also can't distribute generated code. (@ehsavoie if you understand it differently please chime in)

@arusinha this also affects `j2ee.weblogic9` there the situation is even worse: As we have no license for the weblogic XSDs, there is no basis for generating code and/or including the weblogic XSDs

At this point I'm tempted to suggest to remove both modules.

**Comment by geertjanw** [comment]
Can't we download these XSD's, just like we're downloading JARs that we can't include/distribute either?

**Comment by vikasprabhakar** [comment]
The jar http://central.maven.org/maven2/jboss/jboss/4.2.2.GA/jboss-4.2.2.GA.jar  contains following dtd files:
1. jboss-app_4_0.dtd
2. jboss-client_4_0.dtd
3. jboss-web_4_0.dtd
4. jboss_4_0.dtd
No license mention for jboss-4.2.2.GA.jar in maven repository. 
Which license can we add for jboss-4.2.2.GA.jar??

Not able to find the jars for following dtd files:
1. jboss-ds_1_5.dtd
2. jboss-service_4_0.dtd
Help us to find the respective jars for above dtd files.

**Comment by matthiasblaesing** [comment]
@geertjanw The XSDs/DTDs are used to generate code and my interpretation of the reply from apache legal is, that the license transcends to the generated code. So for weblogic we would distribute unlicensed code (i.e. we have no right to distribute) and for jboss/wildfly we would distribute LGPL code, which is against the ASF rules.
Getting the XSDs/DTDs at runtime would be perfectly doable, but the modules would need to be reworked to no rely on code generated at build-time.

@vikasprabhakar the DTD files are present here:
https://www.jboss.org/j2ee/dtd/
The files are missing an explicit license and as such I would assume they are covered by the projects LGPL license. That at least is reflected in some of the XSDs I saw. Asking redhat would most probably reveal the same. That still leaves us with the "wrong" license.

**Comment by vikasprabhakar** [comment]
@matthiasblaesing could you provide the list of task in module to get XSDs/DTDs at runtime with reference to your comment: "Getting the XSDs/DTDs at runtime would be perfectly doable, but the modules would need to be reworked to no rely on code generated at build-time."

**Comment by ehsavoie** [comment]
I read the answer form legal in the same way as @matthiasblaesing :(
Honestly I don't know how to bypass that since the generated code is required to compile and build the plugin (as the wildfly plugin)

**Comment by vikasprabhakar** [comment]
We logged a jira bug to follow up and fix the licensing issue : https://issues.apache.org/jira/browse/NETBEANS-1736

**Comment by matthiasblaesing** [comment]
Closing this, as we can't integrate LGPL files. Different idea (not for Apache Netbeans, but a thirdparty builder): Fetch the DTDs at build time directly from red hat. We can't distribute them, but nothing stops a third party to do it (LGPL is not acceptable for the ASF, but not necessarily incompatible with the ALv2).

**Pull request closed without merging**
