### PR TITLE
Ensuring important DTDs are used locally when running java.completion…

### PR DESCRIPTION
**Pull request by jlahoda**
… tests.

Adding the DTDs to the web was nice, but didn't seem to help the builds much. So trying to resolve this for java.completion tests by using the local copies of the DTDs.

### CODE REVIEW

**Comment by lkishalmi** [comment]
Looks sane. Merging.

**Comment by vieiro** [comment]
Wow, that's a fast merge :-)
What about using netbeans.apache.org as the URL? That's already there (no redirections required)

**Comment by lkishalmi** [comment]
That could work as well, though I really value unit test independence of external environment.

**Comment by vieiro** [comment]
That's a sound reason to have all DTDs included in a directory somewhere :-)

**Comment by lkishalmi** [comment]
I could really support that move! Shall I file a JIRA Improvement on that?

**Comment by vieiro** [comment]
Definitely! Feel free to assign it to me.

**Comment by jtulach** [comment]
Using DTDs locally is the best fix. Thanks @jlahoda.

**Pull request merged**
