### PR TITLE
[NETBEANS-68] Remove SwingX dependency 

### PR DESCRIPTION
**Pull request by matthiasblaesing**
This PR removes the dependency on SwingX. It is not a complete
replacement, as the primary component (the DatePicker) was
not replaced, but an alternative using JTextFields was implemented.

### CODE REVIEW

**Comment by geertjanw** [comment]
Wow, nice job. Will review each file and comment more ASAP.

**Comment by geertjanw** [comment]
To me, looks good, can someone else review this too?

**Comment by geertjanw** [comment]
Matthias, are you confident about this one or would you like more opinions and reviews?

**Comment by matthiasblaesing** [comment]
Merging - thanks for reviewing.

**Comment by bolsover** [comment]
Excellent work but BooleanCellRenderer this a null pointer exception if database value is null rather than 0 or 1. Sorry for lack of detail here - I only found through issue late last night.

**Comment by matthiasblaesing** [comment]
@bolsover Thank you for looking into this David. I created a fix and added that as  PR #254. When this run through the verification build, I'll merge it and that should fix this.

**Pull request merged**
