### PR TITLE
Remove dependency on java.xml.bind module

### PR DESCRIPTION
**Pull request by matthiasblaesing**
As brought up on the incubator mailing list:

https://lists.apache.org/thread.html/695c0a025f26f51e742faa52343692ef82c35f6e6c3b4bd6acd90f77@%3Cdev.netbeans.apache.org%3E

the dependency on java.xml.bind causes problems when running on JDK 11.
The module is removed from the JDK and would need to be replaced with
a direct dependency on the jaxb.library. Netbeans contains the jaxb library,
but the occurences of jaxb usage, where the library is not yet a direct
dependency, are few. So the usages were replaced with alternatives.

### CODE REVIEW

**Comment by jtulach** [comment]
The tests seem to be passing, I assume. +1 then.

**Comment by jlahoda** [comment]
Seems fine. Thanks a lot for fixing this!

**Comment by matthiasblaesing** [comment]
Thank you both for reviewing. Merged to master.

**Comment by fredfox1** [comment]
We are in the process of moving a large project from Java 8 to Java 11. I installed a fresh copy of Netbeans 11.3 on Ubuntu 18.04, set the JDK to Java 11, loaded the project and resolved all issues, made sure all project settings are set to Java 11, did a clean and build, which completes with:

BUILD SUCCESSFUL (total time: 30 seconds)

When I try to run the project in netbeans (regular or debugging) I receive the following error:

Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
nbproject/build-impl.xml:1346: The following error occurred while executing this line:
nbproject/build-impl.xml:952: Java returned: 1
BUILD FAILED (total time: 8 seconds)

    <target depends="init,compile" name="-debug-start-debuggee">
        <j2seproject3:debug>     <-------------------------- line 1346

I am able to run the resulting jar from the dist directory (with the lib class path specified) without error.

I have also added these jars to the project libraries:

jakarta.xml.bind-api-2.3.3.jar
jaxb-runtime-2.3.3.jar

I find no dependencies on java.xml.bind when running:

jdeps -cp 'lib/*' -R --multi-release base <jar>

Is it possible that the netbeans run function is somehow still dependent on java.xml.bind, or is it more likely that something in the project is still looking for this?

**Comment by matthiasblaesing** [comment]
This is not a discussion forum, please move either to the issue tracker or the mailinglist.

**Comment by fredfox1** [comment]
My apologies. Reported as issue and deleted here.

**Pull request merged**
