### PR TITLE
Updating spec versions and update centers for release 9.0

### PR DESCRIPTION
**Pull request by jlahoda**
Hi,

For specification versions, I've first moved all of them in a trunk mode (the first commit), so that in mainline, all modules are newer than any other existing modules (the legacy development AUC has some weird upgrades). I'll merge this to trunk as well (so trunk will in the end move +2 in versions, and release 9.0 +1.1).

For update centers, I used what I think is our intended target for the NB distribution AUC (https://netbeans.apache.org/nb/updates/9.0/updates.xml.gz + hash) and for plugin portal I used "http://plugins.netbeans.org/nbpluginportal/updates/9.0/catalog.xml.gz". Jirka, does it make sense to add 9.0 to the (legacy) plugin portal? We kind of need to have a place from where we can download nb-javac (after this patch, downloading nb-javac does not work, as there's no 9.0 plugin portal, but using 8.2 pluginportal for 9.0 does not seem quite right either).

Any feedback?

### CODE REVIEW

**Comment by geertjanw** [comment]
Does this PR also update user & cache directories from dev to rc1?

**Comment by matthiasblaesing** [comment]
One question: should 7f2fee1 and  e803780  both be there? It looks as if the second commit supesedes the first one. 
And a second question: The versions in trunk need to be bumped to (and higher than release90) - aren't they?

**Comment by jlahoda** [comment]
Both https://github.com/apache/incubator-netbeans/commit/7f2fee14d01d34e91489ef0d09e6e97eaef416d3 and https://github.com/apache/incubator-netbeans/commit/e803780f53529db9a55c41c9799b85e0c011cafe are intended. The reason is that there exist modules on the legacy update centers that are newer that the modules in the repository, and if we just incremented +0.1 (in release90) and +1 (in master), there would be legacy/old modules with the same spec. versions as our current modules. The intent is that 7f2fee14d01d34e91489ef0d09e6e97eaef416d3 would be merged to master as well, and then the spec versions. would be incremented again. So in the end, we would increment the spec. versions in master +2 and in release90 +1.1, and both master and release90 should be newer than any other existing module.

Checking it again, it turned out the spi.editor.hints on a legacy AUC has spec. version 1.43.0.7.55, so I'll need to move spec. version of that module even further on.

PR for master is coming later.

**Comment by matthiasblaesing** [comment]
Thank you for the explanation - that makes sense.

**Comment by jlahoda** [comment]
FWIW, I've rebased the patch on top of Jarda's PR #555, and dropped the additional change to spi.editor.hints, but otherwise it should be the same as before.

**Comment by jlahoda** [comment]
To answer the question about the userdir and cachedir, these are not updated by this patch. Branding like this includes:
-the userdir and cache dir
-splash screen
-window title

I think that in the past, even RCs had their own userdirs, splash screen updates, etc. So next time, we should do that before attempting a release, guess (currently it is unclear if there will be a respin on RC1 or not - if yes, we can prepare a branding patch to update the above to 9.0rc1, otherwise we should update that before either next RC or FCS.)

**Comment by jlahoda** [comment]
I've just rebased the branch, adjusting the spec. version of java.source.base as needed. Unless there are objections, I'd like to merge tomorrow.

**Pull request merged**
