### PR TITLE
[NETBEANS-1443] Error creating Symfony project

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-1443
netbeans-1443

- Always install the latest LTS version because We can't install the latest stable version using the installer any longer
- Remove the LTS Checkbox of NewProjectConfigurationPanel

### CODE REVIEW

**Comment by junichi11** [comment]
Let's restart build after PR #971 is merged.

**Comment by junichi11** [comment]
This is just an assert exception, so need not  to do it. However, we already know that the command for the latest stable version is not available. So we should avoid using it, I thought. Should we just check the LTS by default?

**Comment by tmysik** [comment]
> This is just an assert exception, so need not to do it. However, we already know that the command for the latest stable version is not available. So we should avoid using it, I thought. Should we just check the LTS by default?

I see. Frankly, I do not know :) I would need to investigate the current state of Symfony, the current state of its support in NetBeans (do we handle correctly Symfony 3 projects? What about Symfony 4 as I can see it is the latest version?). In other words, I would expect that the next LTS version will stop working as well; or am I wrong? :)

**Comment by junichi11** [comment]
The latest stable version seems Symfony 4. We have to install it via composer. i.e. We can install only Symfony 3 (LTS)projects using the installer. (see the attatched above image) Currently, we don't provide support for Symfony 4 yet...

**Comment by tmysik** [comment]
Exactly. So this change will work unless Symfony project starts creating Symfony 3 LTS projects using `composer` :) That will not happen I guess so we can merge. Of course, Symfony 4 needs to be investigated whether the current support can be extended or a new module should be created.

I will merge this MR once the build passes.

Thanks!

**Comment by junichi11** [comment]
The build passed :)

**Comment by tmysik** [comment]
So merged :)

**Pull request merged**
