### PR TITLE
[NETBEANS-461] providing ZIP file with extbrowser DLLs during build

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by efremmc** [comment]
Thanks for looking into this incident as I have temporary workaround because I am a NetBeans user.

**Comment by matthiasblaesing** [comment]
@geertjanw thanks for looking into this - I assume the files were build from the sources contained in the `native` subdirectory of extbrowser? This currently breaks builds, because the Verification task fails:

```
/home/travis/build/apache/incubator-netbeans/nbbuild/build.xml:1532: Failed VerifyLibsAndLicenses test(s):
Some license files have incorrect headers
extbrowser/external/extbrowser-dlls.zip does not appear to include a version number
extbrowser/external/extbrowser-dlls.zip is not associated with any license file
```

I suggest to rename the zip to something like `extbrowser-dlls-<year><month><day>.zip` to satisfy the "requires version" requirement. For the "license file requirement" a file `extbrowser-dlls-<year><month><day>-license.txt` is required. Assuming the files were build from the CDDL sources, `lib.profiler/external/profiler-external-binaries-8.2-license.txt` can be used as a template.

**Comment by geertjanw** [comment]
I think the question also is whether a ZIP file containing the two DLLs is the right approach. Maybe the two DLLs need to be listed separately in the binaries-list, i.e., they'd then be downloaded as DLLs and automatically put in the right place since they'd be in the 'external' folder. That could be better than downloading a ZIP file which will then somehow need to be unzipped?

**Comment by geertjanw** [comment]
To answer my own question, this is how it's done, in the module's build.xml:

 <property name="resourcesdir" value="./release/modules/lib/"/>
 <target name="build-init" depends="projectized.build-init">
        <unzip src="external/extbrowser-dlls.zip" dest="${resourcesdir}"/>
 </target>

**Comment by geertjanw** [comment]
Not really sure what license to use, so followed @matthiasblaesing suggestion above.

**Comment by geertjanw** [comment]
A question at this point that remains is whether 18.03.15 (i.e., today's date) makes sense as a version number.

**Comment by efremmc** [comment]
Hi, the date should be fine but see what the previous versions
reported.  I think the files should be listed in
the binary-list.  How are other similar dll being handled?


from NB 8.2 reports:
org.netbeans.modules.extbrowser                    1.53.1
          Enabled

from NB 8.0.2 reports:
org.netbeans.modules.extbrowser                    1.48.1
   Enabled

Maybe this release if not the date, use 1.54.1, the date is easier to
remember and document.

My vote is for the date because I have not background on the original
versioning.

Regards,

Efrem McCrimon (efremmc2)

On Thu, Mar 15, 2018 at 3:54 AM, Geertjan Wielenga <notifications@github.com

**Comment by geertjanw** [comment]
Native libs are handled in this way generally, i.e., they’re made available and registered in a ZIP file, then unzipped and put in the right place during the build.

**Comment by geertjanw** [comment]
No objections received, time to merge, any problems please file a new issue.

**Pull request merged**
