### PR TITLE
[NETBEANS-1074] Module Review j2ee.ddloaders

### PR DESCRIPTION
**Pull request by sarveshkesharwani**
- Changed license of a file
- Added license to a file
- Added graphic files to licenseinfo.xml

The Rat Report mentioned a .form file in this module, but there are multiple .form files across multiple modules without licenses. Also, it is mentioned [here](https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review) that .form license is one of the problems to be solved centrally. So, I have not added license to the .form file. Please correct me if I am wrong.

### CODE REVIEW

**Comment by junichi11** [comment]
The same as #766

**Comment by sarveshkesharwani** [comment]
@junichi11 , I asked this question in the mailing list, and Geertjan mentioned that some .form files have escaped the automation tools to add licenses and that we should follow the platform module, as it has been donated. All .form files in the platform module have licenses. So, it looks like I should add licenses to all .form files present in this module too.

**Comment by junichi11** [comment]
Thanks for adding it!
I'm not sure about `xml.xsl`. Probably, @matthiasblaesing could look at it.

**Comment by matthiasblaesing** [comment]
`xml.xsd` seems to be from the W3C: https://www.w3.org/2001/xml.xsd

The file evolved in the last years and at the above url the current version can be found. As this file is authored by the w3c the w3c software license applies. Please have a look at `html.editor/licenseinfo.xml` and `html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml1-strict.dtd` which shows how the situation was handled in the past.

Basic idea:
- download the current version of the `xsl.xsd`
- replace the currently present version
- add W3C license header + Changes section
- add file to `licenseinfo.xml`

The Schema file is used at runtime for validation (it is accessible via the catalog).

**Comment by sarveshkesharwani** [comment]
@matthiasblaesing , Thanks for the review. I have added W3C license to xml.xsd and added it to licenseinfo.xml

**Comment by matthiasblaesing** [comment]
Thank you.

**Pull request merged**
