### PR TITLE
[NETBEANS-1074] Review j2ee.kit

### PR DESCRIPTION
**Pull request by juneau001**
- Added license header to Bundle.properties
- Scanned remaining files and headers looked good
- Ignored test files as to not change headers...tests fail without adding any license headers to test files so left alone

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Could you please also adjust `/enterprise/j2ee.kit/test/qa-functional/src/org/netbeans/test/j2ee/Bundle.properties`? It has a GPLv2/CDDL header, which should not be there anymore.

I found it by running:

```shell
cd enterprise/j2ee.kit
grep -r CDDL *
```

That grep call can produce false positives, but it can be used to quickly assess the situation.

**Comment by matthiasblaesing** [comment]
Sorry - I just realized, that that was the file you modified. You original change was correct, I failed to checkout the correct revision. The second commit removes the ALv2 header, which should be there.

The situation can be rectified with the CLI client:
```shell
git checkout review-j2ee.kit # switch to the branch used for the PR
git rebase -i HEAD~1 # change the first verb in the line from pick to drop, save and quit, this removes the last commit from history
git push -f          # force push, as history was changed
```

**Comment by juneau001** [comment]
@matthiasblaesing thanks for your help.  I've removed the last commit, thereby reverting the last change.  Let me know if you need anything else for this PR.  Again, thanks for all of your assistance...it is appreciated!

**Comment by matthiasblaesing** [comment]
Merged - thank you.

**Pull request merged**
