### PR TITLE
[NETBEANS-126] Re-instate browser icons

### PR DESCRIPTION
**Pull request by lbruun**
Reinstates those browser icons that were originally removed from Oracle's donation to Apache. See [NETBEANS-126](https://issues.apache.org/jira/browse/NETBEANS-126) for more information.

IANAL, but I _assume_ that we are allowed to distribute these icons as part of Apache NetBeans, but that Oracle didn't want them in the donation bundle as this is not their trademarks. Please validate assumption before merging.

### CODE REVIEW

**Comment by geertjanw** [comment]
I'd suggest you start a new thread in the Apache NetBeans dev mailing list with this question, starting with [mentors] in the subject line to ensure they're notified of this question.

**Comment by Chris2011** [comment]
It would be great, if we can have new icons, modern, flat for example and free to use. As you can see, the icons are different, different opera icon, different chrome icon, so a set of icons which is the same is needed here anyway.

**Comment by lbruun** [comment]
@Chris2011. The browser icons are about 0.5% of all icons used in the Platform / IDE. Wouldn't it look strange if we replaced only those few icons with a design different than all the other 99.5%  ?

**Comment by Chris2011** [comment]
But why not starting there first and do it incremental further? Or starting to make them looks both the same, as you can see both opera and both chrome icons are diffferent. We need consistency and I think we can start there. Only IMHO.

**Comment by lbruun** [comment]
@geertjanw.
Tracked in [LEGAL-343](https://issues.apache.org/jira/browse/LEGAL-343). If this is wrong procedure, I'll withdraw LEGAL-343. I was just assuming that mentors would guide us to this process anyway (I would certainly do that as a mentor)

**Comment by matthiasblaesing** [comment]
Which question are we following here?

If it is the copyright of the icons, there are several free icon themes out there, that have free enough licenses and hold the icon, there is also font-awesome, that holds glyphs with the shapes. I would feel better with sensible licensed icons.

 If it is trademark then I would not advertise with the icons, but using in the program to represent the application they belong to sounds sensible.

**Comment by lbruun** [comment]
**How they are used:**
* For `css.editor` I don't think the icons add much value. See [NETBEANS-126](https://issues.apache.org/jira/browse/NETBEANS-126) for how they are actually used.
* For `"web.browser.api` I'm not aware of how they are actually used.

**The license of the art-work**
I've taken the icons in the PR from the NetBeans Hg. Thus, I assume that they already have a proper 'free' license. If that assumption falls short then we'll have to review each and every icon in NetBeans. Ouch!

I wonder if the NetBeans core has (historically) had any policy wrt to icons and other art work?

**Comment by Chris2011** [comment]
> For css.editor I don't think the icons add much value. See NETBEANS-126 for how they are actually used.

What do you mean with much value? They are used to show you the browser compatibility of css features.

> For "web.browser.api I'm not aware of how they are actually used.

I think it is for the run/debug session, the panel, where you can choose your browser to start from NetBeans, when you run an application. Only guessing.

**Comment by lbruun** [comment]
>> For css.editor I don't think the icons add much value. See NETBEANS-126 for how they are actually used.
> 
> What do you mean with much value? They are used to show you the browser compatibility of css feature.

I just meant that the same can easily be conveyed _without_ using the actual logo - if usage of the logo turns out to be a [legal problem](https://issues.apache.org/jira/browse/LEGAL-343).

**Comment by lbruun** [comment]
[PR289](https://github.com/apache/incubator-netbeans/pull/289) is an alternative to this pull request which I think is what should be done for now. 

However, I'll leave this PR intact so that it can be activated later if need be.

**Pull request merged**
