### PR TITLE
Fix build after changes for cluster reorganisation (PR #536)

### PR DESCRIPTION
**Pull request by matthiasblaesing**
- junit4 and javahelp libraries were moved to platform subdirectory
- platform-launchers-9.0-license.txt was placed in the wrong directory
- VerifyLibsAndLicenses needed adjustments to scan correct directories
  in the per-module case and the "all modules" case

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@geertjanw could you please have a look, this implements the first changes necessary as indicated in #725 

@jtulach could please evaluate if you can identify further tasks, that need adjustments after your changeset for the per cluster subdirectory change in #536? It would be great if you could check the nbbuild project, as `FixTestDependenciesTest` is still broken, because you changed the constructor of `org.netbeans.nbbuild.ModuleListParser.Entry`

**Comment by geertjanw** [comment]
Just checking -- what's wrong with javahelp being in platform?

**Comment by matthiasblaesing** [comment]
Nothing is wrong with that - but the reference from the nbbuild project needs to be adjusted for the moved path - before the change in line 208:

https://github.com/apache/incubator-netbeans/blob/3a6f41789456fd1473163b1ac9e4e6616436c61b/nbbuild/nbproject/project.xml#L208

the reference pointed to a non-existing file after the cluster reorgnisation of platform.

**Comment by matthiasblaesing** [comment]
I pushed a followup to fix the test failures revealed (not caused!) by the first commit.

**Comment by geertjanw** [comment]
Thanks a lot, merging. This should fix all the problems you found, @jtulach.

**Pull request merged**
