### PR TITLE
Extend the SizeEqualsZero Java hint to look for Yoda conditions

### PR DESCRIPTION
**Pull request by dtrebbien**

### CODE REVIEW

**Comment by sdedic** [comment]
Looks OK

**Comment by junichi11** [comment]
@dtrebbien Just one question: Did you send an ICLA[1]? If no, you should send it :)

[1] https://www.apache.org/licenses/icla.pdf

**Comment by dtrebbien** [comment]
Hello @junichi11,

I have not signed the ICLA.

From a cursory review of the ICLA, I don't like it. I would rather stick with the application of Section 5 "Submission of Contributions" of the Apache License, Version 2.0 for my contributions. This shouldn't be a problem because, according to https://cwiki.apache.org/confluence/display/NETBEANS/How+to+Participate I would need to sign the ICLA if I wished to become a Committer, Member, and/or PPMC Member, but I don't think I want to become a Committer, Member, and/or PPMC Member.

Daniel

**Comment by junichi11** [comment]
Hello @dtrebbien,

I asked about it via ML, just in case :) https://lists.apache.org/thread.html/73540b253cae18feef9faf53342627eae385dcf370be64e1d4303bc2@%3Cdev.netbeans.apache.org%3E

Thanks for your contribution,
Junichi

**Pull request merged**
