### PR TITLE
 [NETBEANS-946] PHP 7.3 support

### PR DESCRIPTION
**Pull request by junichi11**
#### PHP 7.3 RFC

https://wiki.php.net/rfc#php_73

We need to provide support for the following features:

1. [Allow a trailing comma in function calls](https://wiki.php.net/rfc/trailing-comma-function-calls) : this PR
2. [list() Reference Assignment](https://wiki.php.net/rfc/list_reference_assignment) : this PR
3. [Flexible Heredoc and Nowdoc Syntaxes](https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes) : **Not Yet**

I've implemented No.1 and 2 in this PR. Main changes are `php/php.editor/tools/ASTPHP5Parser.cup` and `php/php.editor/src/org/netbeans/modules/php/editor/verification/PHP73UnhandledError.java`. Other than those, I added unit tests.

However, No.3 is not easy because of BC break.
Probably, we should create a lexer(and parser, too?) for PHP 7.3, but I suppose unit tests will be complicated. (We are using the common lexer and parser for all PHP versions, so far.)

### CODE REVIEW

**Comment by tmysik** [comment]
@junichi11 

> However, No.3 is not easy because of BC break.
Probably, we should create a lexer(and parser, too?) for PHP 7.3, but I suppose unit tests will be complicated. (We are using the common lexer and parser for all PHP versions, so far.)

Why exactly? Could you explain, please? Thanks.

**Comment by junichi11** [comment]
@tmysik 
I'm not working on anything about it yet. So, just my estimate... somehow I just thought like that. I'll try it once :) So, just ignore my above comment. Thanks!

**Comment by tmysik** [comment]
@junichi11

You can be right, of course; I just had a feeling that it could be backward compatible (and also I am not aware of many BC breaks on the PHP side for a long time). We will see.

Thanks.

**Comment by junichi11** [comment]
@tmysik 
In the below case, unit tests fail if we implement the new syntax. We cannot implement both syntaxes at the same time. However, a user should be able to choose another marker instead. In this case, e.g. choose `HEREDOCMARKER` instead of `ENDOFHEREDOC`

https://github.com/apache/incubator-netbeans/blob/6a382b93ebc5a99ee99306b8c758126aba9de59c/php/php.editor/test/unit/data/testfiles/parser/heredoc_009.php#L8-L24

My idea: Just don't provide support for the above case(the old syntax) because I think that that case is almost never used and we can use another marker instead.

That way, we need not create a new lexer for PHP 7.3, maybe. What do you think?
Thanks.

**Comment by tmysik** [comment]
Not sure if I fully understand. I would remove the unit test, basically, this is a nonsense and IMHO worked earlier in PHP just by a mistake. So, NetBeans would "fail" on such a code now - for how many users is this a problem? Three? Maybe less? :)

I would **really** try to avoid to have more lexers - it will be hell to maintain them all (unless we are able to create them somehow "smart" so they can share their code). What do you think, does it make sense to support mainly the new syntax and the old syntax as much as possible? And if someone really reports a bug, she should fix her code, in fact (that should be trivial).

Am I missing something? Please let me know. Thanks.

**Comment by junichi11** [comment]
Exactly! I think so. Let's go with it :)
We provide support for the old syntax no longer. If someone reported about it, I would say "Please use another text as a marker" ;)
Thanks!

**Comment by tmysik** [comment]
Yes, the code will stop working with PHP 7.3 so it will need to be fixed anyway...

**Pull request merged**
