### PR TITLE
Check whether line endings are LF with Travis CI

### PR DESCRIPTION
**Pull request by junichi11**
- Change line endings of a few files to LF.
- Add a script for Travis CI to check line endings.

### CODE REVIEW

**Comment by geertjanw** [comment]
+1 looks good to me. Would be good if someone else reviewed this too.

**Comment by junichi11** [comment]
@geertjanw Thanks a lot for your review!

Jan is working on #269. So I'll fix `.travis.yml` again after Jan's changes are merged.

**Comment by lbruun** [comment]
Great stuff.

I'm far from a git expert but as far as I understand there also the solution of using a `.gitattributes` file.  Because this file lives in the repo itself, users will automatically get the correct git setting when they clone the repo. See [Vaadin project on GitHub](https://github.com/vaadin/framework/blob/master/.gitattributes) for an example of such a file.

I'm thinking that we should probably do both this PR as well as as `.gitattributes` file, but someone with git experience will probably know if the `.gitattributes` solution is worthwhile.

**Comment by junichi11** [comment]
Changed `/**` to `/*`

**Comment by lbruun** [comment]
@junichi11 
I think we should monitor if this works or not. As far as I can tell the check relies on Git's ability to predict if a certain file is to be considered a text file or not. There may be some text files where we actually find it ok for them to use CRLF.  Files of type `.rc` comes to mind. These are Windows resource scripts and have no relevance outside of Windows. Just an example.

I've now proposed [PR290](https://github.com/apache/incubator-netbeans/pull/290). These two PRs will complement each other.

**Pull request merged**
