### PR TITLE
[NETBEANS-938] When browsing JDK sources, need to use --patch-module …

### PR DESCRIPTION
**Pull request by jlahoda**
…to parse as-if the source is part of the appropriate modules.

@tzezula, any comments? Thanks!

### CODE REVIEW

**Comment by geertjanw** [comment]
Great.

**Comment by tzezula** [comment]
As far as I remember there should be already such a code adding -Xmodule for non project sources.
The `org/netbeans/modules/java/source/parsing/ModuleOraculum.java` in `java.source.base` should do this.

**Comment by jlahoda** [comment]
@tzezula, thanks, I didn't realize there's such a class. It does depend on working (-XD)-Xmodule, though, which does not work on vanilla javac. But I realized that with custom FileManager, it is possible to emulate that, so that's what the current patch is trying to do. (We could use -Xmodule, but not -XD-Xmodule, instead of a newly introduced -Xnb-Xmodule: option, but it seemed better to be to use option that that would make it clear it is a NB-only option.)

**Comment by geertjanw** [comment]
@jlahoda, should we merge, and into release90 too?

**Comment by geertjanw** [comment]
Any reason not to merge this?

**Comment by jlahoda** [comment]
I don't see a reason to not merge this, so I will do that unless there are objections.

**Comment by tzezula** [comment]
Feel free to merge.

**Comment by geertjanw** [comment]
Thanks, merging.

**Pull request merged**
