### PR TITLE
[work-in-progress] The Travis build should fail when there are either rat or verify-libs…

### PR DESCRIPTION
**Pull request by jlahoda**
…-and-licenses failures.

### CODE REVIEW

**Comment by geertjanw** [comment]
Ironically, the Travis build failed, can I merge this one anyway?

**Comment by jlahoda** [comment]
@geertjanw - please don't merge yet, the original failure was intentional, the new one is not, need to figure out how this all should work. (I'll remove the [work-in-progress] when it seems good. (Unfortunately, I don't know how to test the Travis build without having a pull request open.)

**Comment by junichi11** [comment]
> Unfortunately, I don't know how to test the Travis build without having a pull request open.

@jlahoda Why not enable Travis CI in your repository(https://github.com/jlahoda/incubator-netbeans) when you need it(It can be disabled/enabled easily)?

**Comment by jlahoda** [comment]
Will reopen a new pull request.

**Pull request closed without merging**
