### PR TITLE
[NETBEANS-2040] Maven first in New Project dialog

### PR DESCRIPTION
**Pull request by geertjanw**
See this blog entry for details: https://blogs.apache.org/netbeans/entry/restructuring-of-project-templates-in

### CODE REVIEW

**Comment by lkishalmi** [comment]
I do not know if it matters anything, but +1 for this PR. An thanks for the bolgpost as well!

**Comment by matthiasblaesing** [comment]
Looks good to me too.

**Comment by geertjanw** [comment]
Since this represents the concluding points of various discussions, and since no one is objecting, I am merging this. If strong objections emerge, we can revert; if tweaks are needed on the basis of this starting point, we can always tweak and modify as needed. But in the spirit of ‘get it done’, I am now going to merge this.

**Comment by vieiro** [comment]
Late to the party but +1 to this PR as well. Thanks.

**Pull request merged**
