### PR TITLE
[NETBEANS-54] Module Review c.google.guava

### PR DESCRIPTION
**Pull request by junichi11**
- external library guava-15.0.jar: Maven coordinates added.
- checked Rat report: everything has been relicensed to Apache, included in 'central problems' list above, or excluded via Rat
- skimmed through the module, did not notice additional problems

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
This is nitpicking but as the target is cleanup I hope you understand:
- the license file should match the binary `<binaryname>.zip` should be accompanied by `<binaryname>-icense.txt` in this case `guava-15.0-license.jar`
- in the license file the version should be corrected to `15.0`
Thanks :-)

**Comment by junichi11** [comment]
@matthiasblaesing Thanks for looking at it :) Fixed. I hope that my understanding is correct.

**Comment by matthiasblaesing** [comment]
For me this looks good - thanks for taking care!

**Comment by emilianbold** [comment]
Feel free to commit.

**Pull request merged**
