### PR TITLE
[NETBEANS-1074] Module Review libs.nashorn

### PR DESCRIPTION
**Pull request by sdedic**
Just added license to binaries-list

### CODE REVIEW

**Comment by sdedic** [comment]
Folks, this will not be that easy. Nashorn binary needs to be distributed, since it is used at runtime, but uses `GPLv2+CPE` license, which is not compatible with Apache distribution AFAIK.

I would separate two issues: cleaning up / fixing license so that the code may reside in the repository. This is what this PR is about. Other code can compile against the nashorn classes (compile-time dependency), but that code will not actually run.

I filed issue [NETBEANS-1159](https://issues.apache.org/jira/browse/NETBEANS-1159) to explore possible relicensing from the contributor (Oracle). In the meantime, approach similar to NB javac could be used, as the code **can** (IMHO, IANAL) be legally compiled AND distributed, though not using Apache mirrors. See [NETBEANS-1160](https://issues.apache.org/jira/browse/NETBEANS-1160).

**Comment by sdedic** [comment]
NB is working, at least the 'basic' cluster. I hope to fix the non-political issue soon ;)

**Comment by matthiasblaesing** [comment]
Yeah - I meant working javascript support. My understand was/is, that for the incubation period it is more or less expected, that releases are not perfect and as such, we gain nothing by breaking the js support.

**Comment by sdedic** [comment]
So do you think it's OK for the GPLed binary to appear in convenience master builds ?

@geertjanw  - what's your opinion ?

**Comment by matthiasblaesing** [comment]
Yes - and if nashorn follows OpenJDK convention, this is GPL-CPE, which is at least discussed as Category-B: https://issues.apache.org/jira/browse/LEGAL-336

**Comment by sdedic** [comment]
@matthiasblaesing returned nashorn back to the build. Please re-check before squash/merge.

**Pull request merged**
