### PR TITLE
Change category

### PR DESCRIPTION
**Pull request by dukescript**
Moving the wizard into an appropriate category as requested by Geertjan.

### CODE REVIEW

**Comment by geertjanw** [comment]
I think 'Java GUI Application' is maybe a bit misleading/too general, shouldn't it be "DukeScript Application" or "HTML/Java API Application"?

**Comment by jtulach** [comment]
Thanks for the review, @geertjanw! I agree the classification of the wizard as **GUI** is general. But it is not incorrect. Quite opposite. Dmitry [pointed out when trying to use the wizard](http://mail-archives.apache.org/mod_mbox/incubator-netbeans-dev/201803.mbox/%3CCAM6-voFo4bvdWp_7gmV6PMEECXbT5FwXksMd9mjSTmuafTWjSQ%40mail.gmail.com%3E) that a proper name for the wizard is needed:

> Select: File -> New Project -> JavaFX -> Java HTML5 Application (again,
> only because I knew from this thread where to click)
> Read description: "Generates a WebView based DukeScript application".
>
> DukeScript? WebView based?... huh...

Based on his feedback I'd like to avoid mentioning **DukeScript** or **WebView** or **HTML** in the wizard name or its description. It is too confusing. Either people don't know what the term means, or they start to think about *servlets*, *JSPs*, etc. None of that is what they get. They will really get **GUI**.

**Comment by geertjanw** [comment]
Maybe 'Java HTML GUI Application' then? To me and probably many having used NetBeans ever, GUI signified Java Swing.

**Comment by matthiasblaesing** [comment]
I like Geertjans suggestion - it is simple and transports the necessary info. 

If you want a simple self-contained application without external dependencies there is currently Swing as the build-in GUI. HTML GUIs that are created here are different beast and the user should be able to see that.

**Comment by neilcsmith-net** [comment]
Agree with Matthias on Geertjan's wording.  Can I clarify what happens when a user doesn't have JavaFX?  Is the project _and the wizard_ still usable?

**Comment by dukescript** [comment]
I've changed the name to "Java Frontend Application". The PR was initiated because the category and also the title "Java HTML5 Application" was found to be confusing. I think "Java HTML Application" is not less confusing, so I'd like to suggest "Fontend" instead, and add the "HTML"-part to the description, where we can add more context.

**Comment by geertjanw** [comment]
Makes sense to me! From my point of view, this can be merged.

**Comment by matthiasblaesing** [comment]
What happens if we add:

- SWT based Frontend Application
- Swing based Frontend Application
- $Toolkit based Frontend Application?

I think Frontend is much to generic. Consider a newbee programmer coming to Java and reading a book and now wants to test the GUI parts. He connects GUI == Frontend and runs the wizard and will be faced with a much more complex project than he intended. He would need to know, that a basic Swing GUI needs a "Java Application".

**Comment by geertjanw** [comment]
Well, to me then, clearest would be "DukeScript Application". But I think @jtulach and @dukescript  and @eppleton have objections to this.

**Comment by eppleton** [comment]
I’d be OK with “DukeScript Application”.

 

--Toni

 

Von: Geertjan Wielenga <notifications@github.com> 
Gesendet: Donnerstag, 5. April 2018 12:55
An: apache/incubator-netbeans <incubator-netbeans@noreply.github.com>
Cc: Anton Epple <toni.epple@eppleton.de>; Mention <mention@noreply.github.com>
Betreff: Re: [apache/incubator-netbeans] Change category (#466)

 

Well, to me then, clearest would be "DukeScript Application". But I think @jtulach <https://github.com/jtulach>  and @dukescript <https://github.com/dukescript>  and @eppleton <https://github.com/eppleton>  have objections to this.

**Comment by JaroslavTulach** [comment]
Yes, I agree that **frontend** is generic. However, in contrary to @matthiasblaesing, I don't think it will cause any confusion. Talk to any **Java EE** developer out there and ask him what **frontend** means. There is going to be unison answer: it means an application running in a browser or in a WebView component (on desktop or mobile phone) written using CSS/DOM/etc.

The term **frontend** has been kidnapped by the JavaScript camp few years ago. It no longer means Swing or SWT, it only means DOM, CSS & co. Everyone not deeply knowledgable of Java will expect that **frontend** means exactly this kind of app. From this point of view I find *Java Frontend Application* a perfect fit! Btw. nice idea, Toni!

Of course "DukeScript Application" would exactly describe what is going on. But I have to (again) quote our usability study: Dmitry pointed out when trying to use the wizard that a proper name for the wizard is needed:

> Select: File -> New Project -> JavaFX -> Java HTML5 Application (again,
> only because I knew from this thread where to click)
> Read description: "Generates a WebView based DukeScript application".
>
>   DukeScript? WebView based?... huh...

If Toni wants to use "DukeScript application", fine with me, he invented the brand and he may have emotional attachments to the name. But then the pull request only fixes the category problem and ignores the usability study result with respect to the name - people won't even bother with the wizard, as its name won't sound similar in any way.

**Comment by vieiro** [comment]
I love the "html4j" term...

**Comment by matthiasblaesing** [comment]
@JaroslavTulach I appretiate your view, but 

a) just because everybody uses a term wrong, we don't need to follow that
b) For my colleges Frontend means: Delphi, WinForms, ... - oh and Swing

So the term is overloaded and depends on the context - There are at lease two options, that would work:

- Java HTML Application (this makes it clear we are not talking  Swing here)
- DukeScript Application (calling the backing technology)
- html4j Application (with an explanation in the detail info you can learn what this is)

You need to know what you want - but the same is true for the JS world - JS could mean:
- Plain Javascript
- Knockout
- Angular
- $random framework

Yes it is complicated - don't pretend that calling a random technology "Java Frontend" makes it easier.

**Comment by eppleton** [comment]
Ok, then how about solving it with a better description?

 

“Java GUI Application”

 

“Generates a Java application with a graphical user interface following the Model View View Model (MVVM) pattern. Model and ViewModel are written in Java, the View is defined in HTML, CSS and JavaScript.”

 

A descriptive title like that would solve the problem of “DukeScript” being relatively unknown, while the description would give a user the required context.

 

--Toni

 

 

 

Von: Jaroslav Tulach <notifications@github.com> 
Gesendet: Donnerstag, 5. April 2018 13:43
An: apache/incubator-netbeans <incubator-netbeans@noreply.github.com>
Cc: Anton Epple <toni.epple@eppleton.de>; Mention <mention@noreply.github.com>
Betreff: Re: [apache/incubator-netbeans] Change category (#466)

 

Yes, I agree that frontend is generic. However, in contrary to @matthiasblaesing <https://github.com/matthiasblaesing> , I don't think it will cause any confusion. Talk to any Java EE developer out there and ask him what frontend means. There is going to be unison answer: it means an application running in a browser or in a WebView component (on desktop or mobile phone) written using CSS/DOM/etc.

The term frontend has been kidnapped by the JavaScript camp few years ago. It no longer means Swing or SWT, it only means DOM, CSS & co. Everyone not deeply knowledgable of Java will expect that frontend means exactly this kind of app. From this point of view I find Java Frontend Application a perfect fit! Btw. nice idea, Toni!

Of course "DukeScript Application" would exactly describe what is going on. But I have to (again) quote our usability study: Dmitry pointed out when trying to use the wizard that a proper name for the wizard is needed:

Select: File -> New Project -> JavaFX -> Java HTML5 Application (again,
only because I knew from this thread where to click)
Read description: "Generates a WebView based DukeScript application".

DukeScript? WebView based?... huh...

If Toni wants to use "DukeScript application", fine with me, he invented the brand and he may have emotional attachments to the name. But then the pull request only fixes the category problem and ignores the usability study result with respect to the name - people won't even bother with the wizard, as its name won't sound similar in any way.

**Comment by JaroslavTulach** [comment]
> I love the "html4j" term...

I had also thought it would have been the best, but the problem with **html4j** is that it is **HTML5**, not **4**! At least that was one of the comments I got in the [2014 UX study](http://wiki.netbeans.org/Html4JavaUXStudy2014).

**Comment by matthiasblaesing** [comment]
@JaroslavTulach I saw your opinionated [tweet](https://twitter.com/JaroslavTulach/status/982205644273954816). That is hardly a neutral vote. I don't care anymore. You want to push your pet technology and pretend it is the future - ok fine with me. I made my point and will now unsubscribe from this bug. Whatever is decided, I'm not even remotely interested anymore.

**Comment by jtulach** [comment]
Thanks, @matthiasblaesing. I would have CCed you, if I knew your twitter handle. Tweets tend to be opinionated, but don't I think this is the case. I just reworded [what I had written here](https://github.com/apache/incubator-netbeans/pull/466#issuecomment-378908050).

**Comment by geertjanw** [comment]
OK, everyone is either happy or tired of this discussion. Time to merge!

**Pull request merged**
