### PR TITLE
JavaFX for NetBeans GUI

### PR DESCRIPTION
**Pull request by mnachev**
Replacing Swing with JavaFX for NetBeans GUI.

### CODE REVIEW

**Comment by junichi11** [comment]
Did you mistake something? Why do you merge master into 2ndDonation?

**Comment by mnachev** [comment]
Yes, probably because I have not used GitHub to create requirements,
suggestions, and issues.

**Comment by junichi11** [comment]
I'll close.

**Comment by mnachev** [comment]
OK. Can you help me to add some ideas for future functionality? Maybe for
version 10?

**Comment by geertjanw** [comment]
Here are some ideas: https://issues.apache.org/jira/projects/NETBEANS -- and better to discuss on the mailing list than in this issue.

**Comment by matthiasblaesing** [comment]
As a general comment: Swing can be used for GUI because you can expect an installed JDK to carry it. We can't currently depend on OpenJFX, as GPL-v2-CPE is not whitelisted by the apache foundation. There are discussions whether or not it should be usable, but at this time, JavaFX as a core dependency must be considered off-limits.

**Comment by mnachev** [comment]
Hi,

Thank you very much for the reply.

Almost all Apache projects are based on Java/JDK, are they? This means,
that the Java license is acceptable to Apache policy.
Until September 2018, JavaFX is still part of Java. Then it becomes OpenJFX
<http://jdk.java.net/openjfx/> with the GNU General Public License, version
2, with the Classpath Exception
<http://openjdk.java.net/legal/gplv2+ce.html>.

Why the same license is acceptable from Apache for one product (Java) and
not acceptable to another (OpenJFX)?

I started using Java 20 years ago in 1998. The Java world has been waiting
for JavaFX for over 20 years. Swing and AWT were a failure for Java and
Desktop applications in the Java world. This was one of the serious
reasons, Microsoft .NET to overtake Java in many ways.

Why repeat the same mistake so many times?


Miro.

**Comment by junichi11** [comment]
@mnachev As @geertjanw wrote above, please discuss your issue on other places. Here is not a proper place.

**Comment by matthiasblaesing** [comment]
The apache projects depend on Java, not the GPLv2-CPE licensed OpenJDK. To make this clear: No I don't like that and I don't like, that the ASF considers the GPLv2-CPE not compatible with the ASFs views, but at this time I won't put time into the fight.

There is a issue open to query whether GPLv2-CPE should considered Category B:
https://issues.apache.org/jira/browse/LEGAL-336

If that is resolved, and we can formally depend on OpenJDK/OpenJFX, we can discuss further, because moving to JavaFX has also other consequences and needs to be carefully considered.

Please note: I will not reply here anymore: @junichi11 is right, the discussion should take place on the mailinglist.

**Pull request closed without merging**
