### PR TITLE
[NETBEANS-126] Replace with trademark free icons

### PR DESCRIPTION
**Pull request by lbruun**
In an effort to move on with the ASF release, the icons which were removed(*) from the donation are now replaced with icons which may not be the prettiest but which are free from trademark or other restrictions. If the outcome of [LEGAL-343](https://issues.apache.org/jira/browse/LEGAL-343) is that the original icons are OK to be distributed as part of Apache NetBeans, then this can be reversed, i.e. the original icons can be re-instated as per [PR251](https://github.com/apache/incubator-netbeans/pull/251).

*) Technically they weren't removed but were replaced by Oracle with an NB dummy icon

Changes are explained below.

### css.editor

The icons which hints the user about CSS support for various browsers looked like this in NetBeans 8.2:

browser-css-support-before

After this PR they'll look like this:

browser-css-support-after

(icons are made by me, which is why they are so ugly, but they serve the purpose for now)

### web.browser.api

All browser-logo icons are replaced by the generic browser icon (which was already there in same location)

### CODE REVIEW

**Comment by Chris2011** [comment]
I think there are other icons, which are out of trademark. What about using fontawesome icons and convert the SVG back to PNG? Os try to use the SVG instead? Or finding others instead of creating new ones.

**Comment by geertjanw** [comment]
+1 I think this is a really great solution, unless someone provides something concretely different to compare this with.

**Comment by lbruun** [comment]
@Chris2011 Java Swing doesn't support SVG. As for using some other icons:   If we choose something which for sure isn't trademarked then by definition it won't look like the real brand icon, i.e. user will not instantly recognize it representing e.g. Safari. In other words it defeats the purpose. The legal question here is not what art-work of say a Safari logo we can use (there are lots to choose from and there are many which have a license compatible with Apache). Nope, the question is - as I understand it - if we can distribute with the release something which is a trademarked logo.  So the question is if we can use the Safari logo itself, not which icon suite to get it from.  (Safari used here as an example)

**Comment by Chris2011** [comment]
Yeah but we can use SVG files, convert it to PNG and use them. I found a lot when I search for: https://www.google.de/search?q=free+browser+icon. Of course, not everything can be used but I think some, like this: https://dribbble.com/shots/1545132-Free-Flat-Browser-Icons maybe?

So he said, you can use it for free and commercial use. I don't know the license problems there but why can't we try those icons?

**Comment by geertjanw** [comment]
OK, try them, submit a pull request. Until then, I propose we accept this pull request.

**Comment by lbruun** [comment]
@Chris2011.  How would these icons that you propose be any better (from an AFS legal point of view) than the icons that were in NetBeans 8.2? , the ones that Oracle removed from the donation. Those icons were also "free". Again: The problem is _not_ the license of the art-work. 

The problem is that we cannot use a trademarked logo (in whatever form) until we get an ok in [LEGAL-343](https://issues.apache.org/jira/browse/LEGAL-343). Until then we have to use something which for sure is acceptable meaning until then we err on the side of cation, legally.

**Comment by Chris2011** [comment]
I didn't get that point, I thought there is a problem, because of the license for the icons from oracle or smth like that.

**Comment by neilcsmith-net** [comment]
@Chris2011 why would you use FontAwesome or another icon font as SVG? Swing can use icon fonts directly - came up on discussion in dev mailing list a while ago, and @emilianbold was experimenting with this (pinged for thoughts). Of course, that might be a discussion for another time (retina, etc.) since they don't solve the direct trademark issue anyway.

**Comment by matthiasblaesing** [comment]
I see two distinct problems we need to solve:
1. Copyright: Are we allowed to use artwork and
2. Trademarks: Are we allowed to use a "symbol" and "name"

I read some more and (I'm not a lawyer and I know that quoting from wikipedia is questionable):

https://en.wikipedia.org/wiki/Fair_use_(U.S._trademark_law)

> A nonowner may also use a trademark nominatively—to refer to the actual trademarked product or its source. In addition to protecting product criticism and analysis, United States law actually encourages nominative usage by competitors in the form of comparative advertising.

Some more, that might better hold up:

https://www.inta.org/TrademarkBasics/FactSheets/Pages/Fair-Use-of-TrademarksNL.aspx

> Nominative fair use generally is permissible as long as (1) the product or service in question is not readily identifiable without use of the trademark, (2) only so much of the mark as is reasonably necessary to identify the product or service is used and (3) use of the mark does not suggest sponsorship or endorsement by the trademark owner. 

My reading: The trademark part would be ok, as it is the intention to refer to the product itself and it is required to be quickly recognizable.

The remaining thing is copyright: We don't know where the icons come from. They were distributed with netbeans, but they could be distributed with the source as "fair use". So I could live with just readding the icons (#251) or taking the icons from another source under a compatible license.

**Comment by neilcsmith-net** [comment]
@geertjanw is there any documentation of how the icons ended up in the NetBeans source tree in the first place and where they came from (ie. where the copyright lies)?

@matthiasblaesing sounds reasonable, and I assume if Oracle didn't request permission before, the way this was done previously.  So, if that's the case, it's not as mentioned in the legal issue ticket a case-by-case thing, but something where I presume we'd still want a blanket OK from legal on when and where trademark fair-use is allowed in an Apache project? One to ask [mentors]? Must have come up before, surely!

**Comment by lbruun** [comment]
@matthiasblaesing 
Excellent links. I think it would be wonderful if this was the case. And is also what I've always thought myself. The whole _fair use_ thing. This is why I started out with suggesting [PR251](https://github.com/apache/incubator-netbeans/pull/251) but perhaps it went haywire because I said "please validate assumption before merging" in the request or perhaps it went haywire because I opened LEGAL-343 and because we don't get a response. (I suspect ASF legal are volunteers like the rest of us)

I still don't understand why Oracle chose to remove exactly these - out of literally hundreds of icons in the NetBeans code base. Why?  I don't think they removed them because of problems with the art-work license, because then they would have removed the generic icon from the same folder too.

How to move on?

**Comment by Chris2011** [comment]
@neilcsmith-net it was only a suggestionto use a font (they use SVG files too) to get them, convert them to PNG, if we can't find another. I don't care what images we use, but I want to be consistent if we can use icons, who looks similar and not take opera from this and ie from this and ff from this etc. Font-awesome has browser icons which looks similar, but yeah this is another topic.

**Comment by geertjanw** [comment]
Shall we go ahead and merge the solution by @lbruun? And then any improvement/enhancement that anyone has can be discussed separately?

**Comment by matthiasblaesing** [comment]
I would merge #251 with the "fair-use" reasoning and close this.

**Comment by neilcsmith-net** [comment]
I agree with @matthiasblaesing that we should merge #251 as soon as possible.  However, looking back through the dev list, our mentors advised us in April to put in a legal ticket to clarify acceptable trademark "fair-use".  Maybe the legal ticket linked above needs bumping and better wording before merging 251, in which case this PR is probably the right stopgap if we can't get an answer quickly.

Trademark fair-use doesn't cover copyright of the artwork, but I assume as they were in NetBeans before we can use under CDDL?

**Comment by matthiasblaesing** [comment]
Closing this, as the alternative PR #251 was merged.

**Pull request closed without merging**
