### PR TITLE
[NETBEANS-956] Fix location of progress bar and progress text on splash screen.

### PR DESCRIPTION
**Pull request by svenreimers**
Updates colors to better fit in with the new branding.

### CODE REVIEW

**Comment by emilianbold** [comment]
+1

screenshot looked good on JIRA (a bit pixelated, but that's a different matter).

**Comment by svenreimers** [comment]
Can me merge this?

**Comment by geertjanw** [comment]
+1

**Comment by matthiasblaesing** [comment]
Looks good - feel free to merge. I would also cherry-pick it into master.

**Pull request merged**
