### PR TITLE
New phpsigfiles

### PR DESCRIPTION
**Pull request by junichi11**
First of all, we can create this PR, definitely, thanks to @tmysik and @matthiasblaesing :)

1. Merged the changes suggested by Matthias into this branch
2. Generated the new sigfiles (2018/10/23 version)
3. Fixed the license
    - Change the license of sigfiles to CC-BY-3.0 because they are generated from the PHP manual
    - Add the notice file
    - Sigfiles don't have license headers, instead, add the license and notice file to the zip file

@matthiasblaesing 
If my understanding is correct, we have to use the zip file because sigfiles license is CC-BY-3.0, right?
I didn't add the license headers to the sigfiles, instead, added the license and the notice file(from you) to the zip file. Is this OK?
If there is something having a problem, please let us know.

Maybe, `http://netbeans.osuosl.org/binaries/` is not synchronized with `https://hg.netbeans.org/binaries/` yet. So this build would fail. If we would like to verify this soon, we have to add `-Dbinaries.server="https://hg.netbeans.org/binaries/"` option.

zip: https://hg.netbeans.org/binaries/09ABCACCDE3E0F75127E84BBB18F92C0B2C6A5CE-phpsigfiles-1.1.zip

If there is no problem, let's merge this into the release100 branch too.
Thanks!

### CODE REVIEW

**Comment by junichi11** [comment]
BTW, I found the following log when I ran `ant tryme`:
<details>
<summary>Log</summary>

```
[exec] INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'MultiView-php#002EsouFACC1D41xt#002Ehistory#007C_1'. Reason: Could not restore: jar:file:/home/junichi11/NetBeansProjects/incubator-netbeans/nbbuild/netbeans/php/docs/phpsigfiles.zip!/phpstubs/phpruntime/standard.php
     [exec] 
     [exec] msg
     [exec] msg
     [exec] msg
     [exec] Caused: java.io.FileNotFoundException: Could not restore: jar:file:/home/junichi11/NetBeansProjects/incubator-netbeans/nbbuild/netbeans/php/docs/phpsigfiles.zip!/phpstubs/phpruntime/standard.php
     [exec] 	at org.openide.filesystems.AbstractFolder$Replace.readObject(AbstractFolder.java:1023)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
     [exec] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
     [exec] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
     [exec] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
     [exec] 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
     [exec] 	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:561)
     [exec] 	at org.openide.loaders.DataObject$Replace.readObject(DataObject.java:1241)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
     [exec] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
     [exec] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
     [exec] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
     [exec] 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
     [exec] 	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:561)
     [exec] 	at org.openide.loaders.OpenSupport$Env.readObject(OpenSupport.java:144)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
     [exec] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
     [exec] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
     [exec] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
     [exec] 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
     [exec] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
     [exec] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
     [exec] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
     [exec] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
     [exec] 	at org.openide.windows.CloneableTopComponent.readExternal(CloneableTopComponent.java:229)
     [exec] 	at org.netbeans.core.multiview.MultiViewCloneableTopComponent.readExternal(MultiViewCloneableTopComponent.java:250)
     [exec] 	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1834)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
     [exec] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
     [exec] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
     [exec] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
     [exec] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
     [exec] 	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.readSerial(XMLSettingsSupport.java:546)
     [exec] 	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:578)
     [exec] 	at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:401)
     [exec] [catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:546)
     [exec] 	at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:656)
     [exec] 	at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
     [exec] 	at org.netbeans.core.windows.LazyLoader.lazyLoad(LazyLoader.java:115)
     [exec] 	at org.netbeans.core.windows.PersistenceHandler.initModeFromConfig(PersistenceHandler.java:416)
     [exec] 	at org.netbeans.core.windows.PersistenceHandler.load(PersistenceHandler.java:179)
     [exec] 	at org.netbeans.core.windows.WindowSystemImpl.load(WindowSystemImpl.java:56)
     [exec] 	at org.netbeans.core.GuiRunLevel$InitWinSys.run(GuiRunLevel.java:212)
     [exec] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     [exec] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [exec] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
     [exec] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [exec] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
     [exec] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [exec] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
     [exec] Content: 
     [exec] <?xml version="1.0"?>
     [exec] <!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
     [exec] <settings version="1.0">
     [exec]     <module name="org.netbeans.core.multiview/1" spec="1.48"/>
     [exec]     <instanceof class="java.awt.Component"/>
     [exec]     <instanceof class="java.awt.Container"/>
     [exec]     <instanceof class="java.awt.MenuContainer"/>
     [exec]     <instanceof class="java.awt.image.ImageObserver"/>
     [exec]     <instanceof class="java.io.Externalizable"/>
     [exec]     <instanceof class="java.io.Serializable"/>
     [exec]     <instanceof class="java.lang.Object"/>
     [exec]     <instanceof class="javax.accessibility.Accessible"/>
     [exec]     <instanceof class="javax.swing.JComponent"/>
     [exec]     <instanceof class="javax.swing.TransferHandler$HasGetTransferHandler"/>
     [exec]     <instanceof class="org.netbeans.core.multiview.MultiViewCloneableTopComponent"/>
     [exec]     <instanceof class="org.netbeans.core.multiview.MultiViewModel$ActionRequestObserverFactory"/>
     [exec]     <instanceof class="org.netbeans.core.multiview.Splitable"/>
     [exec]     <instanceof class="org.openide.text.CloneableEditorSupport$Pane"/>
     [exec]     <instanceof class="org.openide.util.HelpCtx$Provider"/>
     [exec]     <instanceof class="org.openide.util.Lookup$Provider"/>
     [exec]     <instanceof class="org.openide.windows.CloneableTopComponent"/>
     [exec]     <instanceof class="org.openide.windows.TopComponent"/>
     [exec]     <instanceof class="org.openide.windows.TopComponent$Cloneable"/>
     [exec]     <serialdata class="org.netbeans.core.multiview.MultiViewCloneableTopComponent">
     [exec]         ACED0005737200296F72672E6F70656E6964652E77696E646F77732E546F70436F6D706F6E656E74245265706C6163657284
     [exec]         874494BDDF6D64030000787074003A6F72672E6E65746265616E732E636F72652E6D756C7469766965772E4D756C74695669
     [exec]         6577436C6F6E6561626C65546F70436F6D706F6E656E747372000F6A6176612E6C616E672E53686F7274684D37133460DA52
     [exec]         02000153000576616C7565787200106A6176612E6C616E672E4E756D62657286AC951D0B94E08B0200007870000177040000
     [exec]         00017400127374616E646172642E706870205B722F6F5D74008D70687073747562732F70687072756E74696D652F7374616E
     [exec]         646172642E70687020696E202F686F6D652F6A756E6963686931312F4E65744265616E7350726F6A656374732F696E637562
     [exec]         61746F722D6E65746265616E732F6E626275696C642F6E65746265616E732F7068702F646F63732F70687073696766696C65
     [exec]         732E7A69702028726561642D6F6E6C792971007E000670737200316F72672E6F70656E6964652E77696E646F77732E436C6F
     [exec]         6E6561626C654F70656E537570706F7274244C697374656E6572E525E314060C682D0200014C0003656E7674002E4C6F7267
     [exec]         2F6F70656E6964652F77696E646F77732F436C6F6E6561626C654F70656E537570706F727424456E763B7872002D6F72672E
     [exec]         6F70656E6964652E77696E646F77732E436C6F6E6561626C65546F70436F6D706F6E656E74245265664CED3888AC524ABC02
     [exec]         000078707372004C6F72672E6E65746265616E732E6D6F64756C65732E63736C2E636F72652E477366446174614F626A6563
     [exec]         742447656E65726963456469746F72537570706F727424456E7669726F6E6D656E74FFFFFFFFFFFFFFFF020000787200266F
     [exec]         72672E6F70656E6964652E746578742E44617461456469746F72537570706F727424456E76D720E894A9D2FA270200007872
     [exec]         00236F72672E6F70656E6964652E6C6F61646572732E4F70656E537570706F727424456E76E525E314060C682D0200014C00
     [exec]         036F626A7400204C6F72672F6F70656E6964652F6C6F61646572732F446174614F626A6563743B7870737200266F72672E6F
     [exec]         70656E6964652E6C6F61646572732E446174614F626A656374245265706C616365F7497413DEEC538E0200014C0002666F74
     [exec]         00244C6F72672F6F70656E6964652F66696C6573797374656D732F46696C654F626A6563743B78707372002E6F72672E6F70
     [exec]         656E6964652E66696C6573797374656D732E4162737472616374466F6C646572245265706C61636500000000000000010300
     [exec]         034C000666736E616D657400124C6A6176612F6C616E672F537472696E673B4C00047061746871007E00154C000375726C74
     [exec]         000E4C6A6176612F6E65742F55524C3B787074005D2F686F6D652F6A756E6963686931312F4E65744265616E7350726F6A65
     [exec]         6374732F696E63756261746F722D6E65746265616E732F6E626275696C642F6E65746265616E732F7068702F646F63732F70
     [exec]         687073696766696C65732E7A697074002070687073747562732F70687072756E74696D652F7374616E646172642E70687073
     [exec]         72000C6A6176612E6E65742E55524C962537361AFCE47203000749000868617368436F6465490004706F72744C0009617574
     [exec]         686F7269747971007E00154C000466696C6571007E00154C0004686F737471007E00154C000870726F746F636F6C71007E00
     [exec]         154C000372656671007E00157870FFFFFFFFFFFFFFFF7074008466696C653A2F686F6D652F6A756E6963686931312F4E6574
     [exec]         4265616E7350726F6A656374732F696E63756261746F722D6E65746265616E732F6E626275696C642F6E65746265616E732F
     [exec]         7068702F646F63732F70687073696766696C65732E7A6970212F70687073747562732F70687072756E74696D652F7374616E
     [exec]         646172642E7068707400007400036A617270787874000B746578742F782D7068703571007E001374000A7068702E736F7572
     [exec]         63657372003B6F72672E6E65746265616E732E636F72652E7370692E6D756C7469766965772E746578742E4D756C74695669
     [exec]         6577456469746F72456C656D656E74000187D8CEF94C9B0200014C0006656469746F7274003F4C6F72672F6E65746265616E
     [exec]         732F636F72652F7370692F6D756C7469766965772F746578742F4D756C746956696577436C6F6E6561626C65456469746F72
     [exec]         3B78707371007E000074003D6F72672E6E65746265616E732E636F72652E7370692E6D756C7469766965772E746578742E4D
     [exec]         756C746956696577436C6F6E6561626C65456469746F727371007E0003000177040000000071007E000671007E000771007E
     [exec]         0006707371007E000A71007E0010737200116A6176612E6C616E672E496E746567657212E2A0A4F781873802000149000576
     [exec]         616C75657871007E0004000000007701007871007E002074000C746578742E686973746F727971007E002A7371007E002800
     [exec]         0000007371007E0028000000007371007E0028FFFFFFFF7400193C68746D6C3E3C693E7374616E646172642E7068703C2F69
     [exec]         3E78
     [exec]     </serialdata>
     [exec] </settings>
     [exec] ALL [null]: Source: MultiFileObject@732c7afd[Windows2Local/Components/MultiView-php#002EsouFACC1D41xt#002Ehistory#007C_1.settings]
     [exec] ALL [null]: Cannot read class: org.netbeans.core.multiview.MultiViewCloneableTopComponent
```
</details>

I'm not sure whether this is a problem.

**Comment by tmysik** [comment]
> BTW, I found the following log when I ran `ant tryme`:

Could this be caused by an existing userdir? In other words, could you try a clean userdir? Please note that I do not use `ant tryme` so not sure how it works exactly.

**Comment by junichi11** [comment]
> Could this be caused by an existing userdir? In other words, could you try a clean userdir? Please note that I do not use `ant tryme` so not sure how it works exactly.

I ran it after `ant clean`. I'll try running `netbeans` directly after removing the existing userdirectory later. Thanks!

**Comment by junichi11** [comment]
I ran again, I cannot find that log now. So no problems :) Thanks a lot, Tomas and Matthias!
I'll send an email for asking verification to NetCAT team via mailing list when this PR is merged then Jenkins build is available.

**Comment by VBelozyorov** [comment]
Hi! As NetBeans user where should I add some custom php stubs for code autocompletion?
Some time ago (pretty long) I used to just place those files at path like `... / phpstubs / phpruntime`, how should I action now?

**Comment by junichi11** [comment]
@VBelozyorov 
1. Unzip `php/docs/phpsigfiles.zip`
2. Edit/Create files
3. Zip them as `phpsigfiles.zip` again

BTW, If you have questions, please ask them via the mailing list :) https://netbeans.apache.org/community/mailing-lists.html

Thanks.

**Comment by tmysik** [comment]
@VBelozyorov @junichi11 

This is IMHO not needed, even not recommended since the changes will be lost on PHP sigfiles update.

Simply put your files to **any** folder and add this folder to the PHP Include Path - either in Tools > Options for global availability or in the Project Properties dialog if you want these files to be available only in the given project.

**Comment by junichi11** [comment]
@tmysik Thank you!

**Comment by tmysik** [comment]
@junichi11 You are welcome, of course! :)

**Pull request merged**
