### PR TITLE
[Backport] Enhance AU to install missing feature parts (PR-1044)

### PR DESCRIPTION
**Pull request by sdedic**
This is a backport of [PR-1044](https://github.com/apache/incubator-netbeans/pull/1044) for NetBeans rel. 10.

In addition to commits in [PR-1044](https://github.com/apache/incubator-netbeans/pull/1044) I **have also backported part of** [commit 4b8d8a788dc](https://github.com/apache/incubator-netbeans/commit/4b8d8a788dce05c60444c35c895c3be5bc373537), so the code in `ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod` is as close as possible to master without affecting other functionality: it seemed as less error-prone than converting `ExtraModuleInfo`s back to `Strings` for the release branch. 

I have **not cherry-picked** the `MavenRepoURLHandler` or `javafx` addition to extramodules in `java` feature in commit 4b8d8a788dc

### CODE REVIEW

**Comment by lkishalmi** [comment]
@jlahoda please review. This is the only big blocker before vc5

**Comment by geertjanw** [comment]
Tried it, works for me on Mac OS, awesome.

**Comment by jlahoda** [comment]
Seems sensible to me.

**Comment by sdedic** [comment]
all> thanks for the reviews/testing.

**Pull request merged**
