### PR TITLE
[NETBEANS-1987] use javadoc css from jdk8 for apidoc

### PR DESCRIPTION
**Pull request by ebarboni**
I'm not sure that diff matters as it's copy paste from a css to another

'DejaVu Sans' is not present in apidoc resource but it will default to Arial.

### CODE REVIEW

**Comment by vieiro** [comment]
@ebarboni , feel free to merge at will.

**Comment by geertjanw** [comment]
Sorry, what must I do where to use it?

**Comment by ebarboni** [comment]
it's the default style for javadoc part of apidoc when we use ant build-javadoc. .
Screenshot to compare https://issues.apache.org/jira/browse/NETBEANS-1987 
I will merge and also modify for 9.0 and 10

**Comment by ebarboni** [comment]
@geertjanw @vieiro, I did not find a more accurate component. But for me the website is also apidoc,

**Pull request merged**
