### PR TITLE
[NETBEANS-1074] Module Review web.el

### PR DESCRIPTION
**Pull request by gilbertoca**
No external library
Checked Rat report: everything has been relicensed to Apache
Add licenseinfor file with media

Skimmed through module, I see in the test folder there are src and data ones. The src one, the files have the license. In the data folder there is one example with no license.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Could you please see if you can fix license headers in test-data? If possible test files should also carry correct headers.

**Comment by matthiasblaesing** [comment]
test-data can be excluded from the requirement for the ALv2 header if it clashes with the test itself. At some point we'll have to revisit the unittest again anyway and it was done at least for some of the XML unittests (I know because I did). If you don't want to update them, that is ok, please indicate so and I'll pull in only the licenseinfo.xml file, but it would be great if you could also look at the test files.

**Comment by matthiasblaesing** [comment]
Thank you - the file `web.el/test/unit/data/projects/testWebProject/licenseinfo.xml` won't work that way. Please remove it and lets keep it at that - if the file is removed, I would merge the changeset. It is good, that work was done to cover more files with correct licenses.

**Comment by gilbertoca** [comment]
@matthiasblaesing Removed!

**Comment by matthiasblaesing** [comment]
Looks good. Thank you.

**Pull request merged**
