### PR TITLE
[NETBEANS-210] Setting tmp directory

### PR DESCRIPTION
**Pull request by vieiro**
See https://issues.apache.org/jira/browse/NETBEANS-210 for details on issue 210.

This seems to be working properly in my Debian box, and should also work on default Ubuntu boxes and others with limited /tmp space.

May need testing on Windows & OS/X environments, though.

### CODE REVIEW

**Comment by emilianbold** [comment]
At patch level, it might be better to define a netbeans_default_tmpdir next to netbeans_default_cachedir above.

I feel conflictual about this fix.

On one side, it's good that NetBeans started respecting the OS cache dir. Long ago it did not and it was annoying on macOS, for example, because the user couldn't decide which data is safe to remove (to recover disk space) and which not. I also assume a lot of useless cache got backed up to Time Machine which is not good.

macOS is pretty OK about setting (and clearing) the temp folder and it's rarely on another partition.

On the other hand I can see how from a configuration or security standpoint it might be good not to have NetBeans leak files into various folders. But it feels like a user-configuration thing. (2GB for a temp folder doesn't seem like much, I'll compare with my machines).

So, speaking of NETBEANS-210 I believe NetBeans should have some better user level message about needing extra disk space (it probably throws some error, no?).

In order to help the (minority, I guess, of) users that are in this situation the script could use netbeans_default_tmpdir but initialize it by default with $TMPDIR.

Thus, nothing should change for existing users. But users with smaller $TMPDIRs would just tweak netbeans_default_tmpdir in the script instead of learning about `java.io.tmpdir` and -J-D

**Comment by vieiro** [comment]
Hi,

(I've edited the title to see if this sends stuff to JIRA).

Good points, Emilian, thanks.

Maybe the problem is with the Maven indexer itself. Instead of trying to fill the java.io.tmpdir until exhaustion and then fail (for those systems where java.io.tmpdir lives in memory this is very bad) it should probably check first if there's enough space to proceed.

Since that's tough to do in a portable way maybe the best workaround is to have the maven indexer to use Places to create a  specific working directory in the "cache directory" and ensure that it's cleaned up once it's done. 

On startup we could check if that working directory exists (because of previous fatal exit, for instance) and clean it up too.

The "tmp" partition space is the default Debian installation size, so I assume many Debian users will suffer the problem. I may want to see if Debian derivatives are also affected. Will report back.

**Comment by emilianbold** [comment]
Wait, so the Maven indexer first unzips everything into java.io.tmpdir then moves everything to the cachedir? That can't be good, especially if the two folders are on separate partitions and a move means copy.

Let's figure out first how to fix this from the Maven support side.

**Comment by vieiro** [comment]
I can't tell if the indexer unzips or just creates temporary indexes. Anyway I agree, let's figure out the internals.

**Comment by vieiro** [comment]
There was a "TODO" comment on NexusRepositoryIndexerImpl to use Places.getCacheDirectory instead of a temporary file. 

I've tested this in my box and indexing is faster (not flooding tmp is a good think, I assume).

I'd appreciate a review.

**Comment by emilianbold** [comment]
Much better fix!

+1

**Comment by vieiro** [comment]
Thanks Emilian.
I think I'll do some more clean up (there's no point in computing "java.io.tmpdir" free space on failure) and will then rearrange commits for a final review.

**Comment by vieiro** [comment]
Thank for the feedback, Emilian!
Agreed: removing the check for free space is a bad idea [see 250365](https://netbeans.org/bugzilla/show_bug.cgi?id=250365&x=25&y=7) for a case of a big atlassian repo. I've restored it and updated the messages (including now the folder).

**Comment by emilianbold** [comment]
Perfect!

+1

**Comment by geertjanw** [comment]
Is this ready to be merged or are there other thoughts?

**Comment by emilianbold** [comment]
I'd say it's ready.

**Comment by vieiro** [comment]
Ready. I tried it out in os/x and works perfectly

**Comment by matthiasblaesing** [comment]
I agree also - @vieiro its your PR and you are a committer, so I think it would be good if you merge this yourself.

I have one final advise: Currently this PR consists of 4 commits. I would squash them together. This way, one meaningful commit results. In this case I see the commits are an evolution of the patch, not meaningful entities in themselves and so the squash would be the right thing.

There are two options:

1. Use git cli: You can switch to the isssue-210 branch, rewrite history (squash the entries) and do a force push, that will update this PR and you can then locally merge and push master. Github recognises, that the two commits match and will close this PR automatically.
2. Use the Web-GUI - in this PR you can choose "Merge pull request" (this will use your commits as is) or "Squash and merge" (this will squash the 4 commits into one and merge it to master). The latter would be the advised option.

Thank you!

**Comment by vieiro** [comment]
Merging (I was offline during most of the day).

**Pull request merged**
