### PR TITLE
[NETBEANS-1313] Start NetBeans without printing to console

### PR DESCRIPTION
**Pull request by geertjanw**
there is an option

-J-Dnetbeans.logger.console=true -J-ea

in netbeans/etc/netbeans.conf

That should be removed for the release. We want NetBeans to start without 
printing anything to the console.

### CODE REVIEW

**Comment by geertjanw** [comment]
This is not for master but for release10 branch, once Laszlo creates it.

**Comment by jlahoda** [comment]
+1

**Comment by lkishalmi** [comment]
This is good, but isn't this only valid on release branches?

**Comment by matthiasblaesing** [comment]
Yes this should only be on the release branch - in the past only the `-J-ea` was removed. I think that is enough: If you start netbeans from a shell, I like to see output from the called programm. If started from the GUI (the output is discarded anyway).

**Comment by eirikbakke** [comment]
I agree with matthiasblaesing here: "If you start netbeans from a shell, I like to see output from the called programm." But this patch reverses that? What's the rationale for this?

**Pull request merged**
