### PR TITLE
Deadlock in lexing

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Wrapping version increment in synchronized(this) block is causing deadlocks. I don't think such wrapping is necessary. Enough to use `volatile` for such diagnostic value. Right, Bečoune?

Another possible fix (that I tried) is to _not_ fire changes under the `rootTokenList` lock. However that is a bigger change, possibly changing semantics. Right, Mílo? Thus I decided to go with the safer fix in the Javadoc module.

### CODE REVIEW

**Comment by jtulach** [comment]
This is the deadlock:
```
Found one Java-level deadlock:
=============================
"Editor Parsing Loop (20171223-unknown-revn)":
  waiting to lock monitor 0x00007f25e4202e88 (object 0x00000000fc299fe8, a org.netbeans.modules.javadoc.highlighting.Highlighting),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007f25a46014e8 (object 0x00000000fc267720, a org.netbeans.lib.lexer.inc.IncTokenList),
  which is held by "Editor Parsing Loop (20171223-unknown-revn)"

Java stack information for the threads listed above:
===================================================
"Editor Parsing Loop (20171223-unknown-revn)":
        at org.netbeans.modules.javadoc.highlighting.Highlighting.tokenHierarchyChanged(Highlighting.java:135)
        - waiting to lock <0x00000000fc299fe8> (a org.netbeans.modules.javadoc.highlighting.Highlighting)
        at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openide.util.WeakListenerImpl$ProxyListener.invoke(WeakListenerImpl.java:462)
        at com.sun.proxy.$Proxy44.tokenHierarchyChanged(Unknown Source)
        at org.netbeans.lib.lexer.TokenHierarchyOperation.fireTokenHierarchyChanged(TokenHierarchyOperation.java:555)
        at org.netbeans.lib.lexer.EmbeddingOperation.createEmbedding(EmbeddingOperation.java:365)
        at org.netbeans.api.lexer.TokenSequence.createEmbedding(TokenSequence.java:422)
        - locked <0x00000000fc267720> (a org.netbeans.lib.lexer.inc.IncTokenList)
        at org.netbeans.modules.editor.javajs.JSEmbeddingProvider.run(JSEmbeddingProvider.java:111)
        at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
        at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
"AWT-EventQueue-0":
        at org.netbeans.lib.lexer.TokenHierarchyOperation.isActive(TokenHierarchyOperation.java:344)
        - waiting to lock <0x00000000fc267720> (a org.netbeans.lib.lexer.inc.IncTokenList)
        at org.netbeans.api.lexer.TokenHierarchy.isActive(TokenHierarchy.java:306)
        at org.netbeans.modules.javadoc.highlighting.Highlighting.getHighlights(Highlighting.java:96)
        - locked <0x00000000fc299fe8> (a org.netbeans.modules.javadoc.highlighting.Highlighting)
```

**Comment by JaroslavTulach** [comment]
Right, `++` isn't atomic. I just thought it doesn't matter. That it is not important to get warnings all the time.

`AtomicInteger` was my original attempt too. Then I realized the above, plus the fact it should be `AtomicLong` - I can make it `AtomicLong` or `AtomicInteger` if desirable.

**Comment by dtrebbien** [comment]
I think using `AtomicLong` would be preferable.

**Comment by JaroslavTulach** [comment]
OK, using `AtomicLong`.

**Comment by dtrebbien** [comment]
Looks good to me

**Pull request merged**
