### PR TITLE
Ant 1.10.4 emilian + fixes

### PR DESCRIPTION
**Pull request by sijskes**
fixes for NETBEANS-781. Unsquashed to separate out emilians fixes.

### CODE REVIEW

**Comment by emilianbold** [comment]
Could you comment on my original fix https://reviews.apache.org/r/67721/ and mention the bugs you found?

**Comment by sijskes** [comment]
done

**Comment by geertjanw** [comment]
Any reason not to merge this?

**Comment by sijskes** [comment]
i consider it low risk, because ant 1.10.4 was a minor revision and no actual code is changed in netbeans.

**Comment by geertjanw** [comment]
Aside from 'master' does this also need to be in 'release90'?

**Comment by junichi11** [comment]
Maybe @emilianbold should handle this PR because he is the author of the original fix.

**Comment by emilianbold** [comment]
This is a bit unusual but I don't mind.

@sijskes followed NETBEANS-781 from start till end, he should also get a commit in the codebase for it.

@sijskes : please change if you can my commit to have the original author. You seem to have imported the patch but it doesn't show me as the author.

The .patch (from https://reviews.apache.org/r/67721/diff/raw/ ) does have the correct author.

**Comment by sijskes** [comment]
@emilianbold i've tried to give you proper attribution:
 applied: 0001-NETBEANS-781-Upgrades-Ant-to-1.10.4.patch

from: Emilian Bold <emilian.bold@protonmail.ch.INVALID>
is in the comments of the commit.
if this is not enough, please use your id when merging.

**Comment by matthiasblaesing** [comment]
@sijskes you are listed as the author in the commit. Git allows you to differ between the committer and the author. The author is the one that created the initial changeset, the committer is the one integrating the changeset. In many cases these two are identical, in other case (here) they are not.

If a git formated patch is supplied, the easiest way for integration is:

- change into the root of the project you are working with
- fetch the patch: `wget -O diff.patch https://reviews.apache.org/r/67721/diff/raw/`
- apply it with git: `git am diff.patch`
- remove the patch: `rm diff.patch`

After this, the changeset is commited to the branch, the executing user is set as the committer, the author is set as author.

This is the result:

```
matthias@athena:~/src/incubator-netbeans$ git log -n 1 --pretty=fuller
commit 388b27ff749de94b979dc2097e571fd0ca721140 (HEAD -> test)
Author:     Emilian Bold <emi@apache.org>
AuthorDate: Mon Jun 25 20:16:57 2018 +0300
Commit:     Matthias Bläsing <mblaesing@doppel-helix.eu>
CommitDate: Wed Jul 4 20:17:15 2018 +0200

    Upgrades Ant to 1.10.4
matthias@athena:~/src/incubator-netbeans$ 
```

Maybe this helps.

**Comment by geertjanw** [comment]
I recommend we go ahead with putting together the first vote candidate for the final release and that we deal with this one in the pretty much inevitable second vote candidate.

**Comment by emilianbold** [comment]
BTW, this was included in release90. I've cherry-picked these two commits back into master: https://github.com/apache/incubator-netbeans/commit/dc04a3e144276f2ce83991be0a92cc2c657e97a3

**Pull request closed without merging**
