### PR TITLE
[NETBEANS-892] Fix lambda expr and multi catch rewrite issues

### PR DESCRIPTION
**Pull request by rtaneja1**
Fixed the two compilation issues after refactor : 

catch (RuntimeException | AssertionError e){
getting converted to
catch (RuntimeException | AssertionErrore){

and

doStuff(item-> item.substring(20));
getting converted to
doStuff(String item-> item.substring(20));

(Lambda issue is reproducible in IDE but not with move test below, as param type is coming as ERROR. Need to investigate this.)

### CODE REVIEW

**Comment by sdedic** [comment]
:+1:

**Comment by SirIntellegence** [comment]
I am guessing you are handling the modification of irrelevant code in a different branch then?

**Comment by rtaneja1** [comment]
Yes

**Comment by rtaneja1** [comment]
Yes, no new failure. Below test failure occurs without my change as well.
Testcase: test1(org.netbeans.api.java.source.gen.AddMethodToInterfaceTemplateTest): Caused an ERROR
    [junit] Called DataObject.find on null
    [junit] java.lang.IllegalArgumentException: Called DataObject.find on null
    [junit]     at org.openide.loaders.DataObject.find(DataObject.java:583)
    [junit]     at org.netbeans.api.java.source.gen.AddMethodToInterfaceTemplateTest.test1(AddMethodToInterfaceTemplateTest.java:170)

**Comment by rtaneja1** [comment]
https://github.com/apache/incubator-netbeans/pull/595

for remaining part of NETBEANS-892, to fix issue of updation of unrelated files.

**Pull request merged**
