### PR TITLE
[NETBEANS-139] Create archive sample to fix RepositoryUpdaterEventTest.

### PR DESCRIPTION
**Pull request by blackleg**
[NETBEANS-139] Create archive sample to fix the RepositoryUpdaterEventTest test on parsing.nb module.
It is the same issue that this: https://github.com/apache/incubator-netbeans/commit/d74705dffc65ae259178fb7f859fc4e8da57a5bb

I use this command to run test: ```ant -f parsing.nb -Dtest.type=unit -Dcontinue.after.failing.tests=true -Dtest.includes=org/netbeans/modules/parsing/nb/RepositoryUpdaterEventTest.java test-single```

### CODE REVIEW

**Comment by DhyanRiktam** [comment]
hey  blackleg, 
i checked your fix -it works as designed.

As i unterstood it right, this jar-file is missing when the setup of the test takes place.
Why not add a "createNewFile" in the setup-function - and leave the build untouched ?

**Comment by DhyanRiktam** [comment]
by the way: there are 3 other tests, that failed on project "parsing.nb"

could you fix it in the same pull request ?
grretings, Rik

**Comment by blackleg** [comment]
@DhyanRiktam I use same fix that @matthiasblaesing in this [commit](https://github.com/apache/incubator-netbeans/commit/d74705dffc65ae259178fb7f859fc4e8da57a5bb) because is same issue. 
I tried to fix it creating a file in the setup function and it's working but the logging show errors because require a zipped file.

**Comment by DhyanRiktam** [comment]
Hello hectorespert,

you are right - even an empty zip / jar file must not been empty.
In the Java packages   java.util.zip   and   java.util.jar   there is no
"createNew...File" method.

You must define your own method.   Here is my solution for setup:

void setUp(){
      ....................
      createNewJarFile(getDataDir(), "JavaApplication1.jar");  

@SuppressWarnings("UseSpecificCatch")
    public void createNewJarFile(File dir, String jarName){
        String path = dir.getPath()+File.separator+jarName;             
      
        File jarFile = new File(path);
        ZipOutputStream os;
        try {
            os = new ZipOutputStream(new FileOutputStream(jarFile));
            os.close();
         }catch(Exception ex){
            assertNull(ex.getMessage());
        }
   }

Happy coding,

Rik

Am 23.02.2018 um 20:53 schrieb hectorespert:

**Comment by blackleg** [comment]
@DhyanRiktam I changed pull request to create the test jar in the setup function instead using the build system.

**Comment by matthiasblaesing** [comment]
Merging this - it improves the situation, even though not completely. The two failing unittests from `parsing.nb` were tracked to commit 775dafe1d2e0f7288d2bfeb116958227f6e4508d:

https://github.com/apache/incubator-netbeans/commit/775dafe1d2e0f7288d2bfeb116958227f6e4508d#comments

Thanks for working on this.

**Pull request merged**
