### PR TITLE
[NETBEANS-54] Module Review apisupport.ant

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by emilianbold** [comment]
Arent't lots of these "Problems to be solved centrally"?

**Comment by geertjanw** [comment]
Yes, though did them just to get it done.

**Comment by emilianbold** [comment]
> Yes, though did them just to get it done.

But if the conclusion is that these should *not* have headers, we'll have to go back and delete them.

**Comment by geertjanw** [comment]
OK, we should decide on that first and until then not merge this PR.

**Comment by matthiasblaesing** [comment]
The situation is already there. With or without Geertjans work a potential automatic system needs to detect present licenses, and if it decided, that the headers are not needed, they are not wrong either (Asuming they don't break tests/functionality). I don't see why we would rip out license headers, that are correct and don't interfere with functions/tests.

**Comment by geertjanw** [comment]
Agree with this, i.e., whether we decide to add them for all of these throughout or not, the fact that these specific ones in this module already have them, now that I've added them manually, shouldn't be a problem and we should merge this PR from my point of view.

**Comment by matthiasblaesing** [comment]
@geertjanw please close this PR, the changeset was also part of #96 and the changes are thus merged already.

**Comment by geertjanw** [comment]
OK.

**Pull request closed without merging**
