### PR TITLE
[NETBEANS-1074] Module Review libs.javacup

### PR DESCRIPTION
**Pull request by junichi11**
- Add the license header to binaries-list

java-cup-11a.jar(JavaCUP-LICENSE)
http://www2.cs.tum.edu/projects/cup/licence.php

Is this license OK?

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
From my POV the license reads a lot like the MIT license. But I would raise this with legal, because there are differences. Here is the reference from OSI:

https://opensource.org/licenses/historical.php

**Comment by junichi11** [comment]
I've submitted about that license to legal-discuss: https://issues.apache.org/jira/browse/LEGAL-400

**Comment by junichi11** [comment]
We got two answers. It seems to be OK.

**Comment by geertjanw** [comment]
Thanks, merging.

**Pull request merged**
