### PR TITLE
NETBEANS-1774 Use fragment host instead of fragment bundle for class loading in Netigso

### PR DESCRIPTION
**Pull request by iajn**
See https://issues.apache.org/jira/browse/NETBEANS-1774 for details.

### CODE REVIEW

**Comment by jtulach** [comment]
The change looks OK. Do you think you could also write a test for it? Then I happily integrate.

**Comment by iajn** [comment]
Sure, I'll look into it when I have more time.

**Comment by lkishalmi** [comment]
Any progress on this?

**Comment by iajn** [comment]
Sorry, I haven't had time to look into the tests yet. I'll try to get them done during the next couple of weeks now that our product release is over and done with.

**Comment by iajn** [comment]
@jtulach Added a test case for substituting the fragment bundle with its host bundle in NetigsoLoader. It currently uses a little bit of reflection since NetigsoModule wraps NetigsoLoader inside some sort of private wrapper class loader, and I can't get access to it otherwise.

**Comment by JaroslavTulach** [comment]
Good, assuming the test passes and no other `core.netigso` tests are failing... Let's integrate.

**Pull request merged**
