### PR TITLE
[NETBEANS-313] Remove bootstrap.css from css.model

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Will squash once approved.

**Comment by matthiasblaesing** [comment]
Why was this merged? According to the legal FAQ:
https://www.apache.org/legal/resolved.html#category-a
MIT is whitelisted and the license terms are perfectly met. The license must stay in place and the unittests are only delivered in source - there is nothing to remove here.

**Comment by geertjanw** [comment]
I understand your point. However, questions have been asked about[1] this file and it seems strange to have bootstrap.css there, especially for one test only, so in this particular case, certainly not as a general rule, though it best just to remove it.

[1]https://lists.apache.org/thread.html/5fdb996c8b25e5c48c47e4eca3942b656f690694d767d795524cc960@%3Cgeneral.incubator.apache.org%3E

**Comment by matthiasblaesing** [comment]
Thanks for explaining - I agree with the assessment.

**Pull request merged**
