### PR TITLE
[NETBEANS-54] Module Review libs.xerces

### PR DESCRIPTION
**Pull request by vieiro**
- Updated maven coordinates for Xerces 2.8.0 (Apache 2).
  - Added xerces notice from https://svn.apache.org/repos/asf/xerces/java/tags/Xerces-J_2_8_0/NOTICE

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Please recheck this as this breaks the build. My local build breaks different than the protocol from travis, but reproducible. To check yourself, please run in the repository:

```
git clean -x -f
ant
```

The git clean part removes all files, that are not part of the repository. The downloaded file gets a different name and is can't be made available at build and compile time.

Hava a look at project.properties - this should do it:

```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/libs.xerces/nbproject/project.properties
+++ b/libs.xerces/nbproject/project.properties
@@ -16,6 +16,6 @@
 # under the License.
 
 is.autoload=true
-release.external/xerces-2.8.0.jar=modules/ext/xerces-2.8.0.jar
+release.external/xercesImpl-2.8.0.jar=modules/ext/xerces-2.8.0.jar
 module.jar.verifylinkageignores=org.apache.xerces.util.XMLCatalogResolver
 spec.version.base=1.39.0

```

**Comment by vieiro** [comment]
Should be ready now. Sorry for the trouble. It would be nice getting a travis warning in case of build failure.

**Comment by matthiasblaesing** [comment]
Your wish was already granted - the travis configuration was added to the repository literally hours ago. That's the reason I saw that. :-)

**Comment by vieiro** [comment]
It would be nice getting a pair of beers in case of build success! :-D

**Comment by matthiasblaesing** [comment]
For the record: The content of the two binaries is identical, the files from maven central and the original netbeans file were zipped with different timestamps and differing directory order.

Diffoscope output is here: https://try.diffoscope.org/qayzdzqugqge.html

To check yourself: unzip both files and run a recursive diff over it.

**Comment by matthiasblaesing** [comment]
I squashed your two commits together and merged this.

**Comment by vieiro** [comment]
Thanks Matthias. If you ever happen to visit Madrid you know you have some free beers here.

**Pull request closed without merging**
