### PR TITLE
Notice2019

### PR DESCRIPTION
**Pull request by tarbear123**
does it upload the sketch like Arduino IDE (runs code without typing something except for when you want to print something)

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
This PR looks strange - it looks as if this PR is not based on the master branch.

**Comment by junichi11** [comment]
@matthiasblaesing Maybe, tarbear123 used this PR for not a PR but an issue report. So, we should close this PR. Actually, the notice2019 branch is in apache/incubator-netbeans repo.

@tarbear123 If you have some requests, please report them to the [JIRA](https://issues.apache.org/jira/projects/NETBEANS/issues) . If you have questions, please join the [mailing lists](https://netbeans.apache.org/community/mailing-lists.html).

**Comment by ebarboni** [comment]
@junichi11 @matthiasblaesing , I try to do a PR via web github for only chaning a 8 to a 9 :p using a name linke notice219. I should have used a more complicated name. tarbear123 is not having a fork of this repo.

**Comment by ebarboni** [comment]
@junichi11 is it ok to delete the branch ? seems pointless

**Comment by junichi11** [comment]
@ebarboni Please feel free to do it if you created the branch :)
BTW, Anyone can create a PR even if a user doesn't have a fork. So, sometimes someone creates a new PR using that behavior to report an issue. I've reported that to the GitHub Support before because that is not expected behavior. But the behavior is not changed yet...

**Pull request closed without merging**
