### PR TITLE
[NETBEANS-54] Module Review applemenu

### PR DESCRIPTION
**Pull request by jlahoda**
-using an external library instead of inline com/apple/eawt classes
-saner handling of "external" java.awt classes (not unpacking them into the source directory)

### CODE REVIEW

**Comment by geertjanw** [comment]
Wow, excellent, thanks, that helps a lot.

**Comment by matthiasblaesing** [comment]
I agree - this looks good. I don't own a mac, so it would be good if someone with a mac could give it a spin.

**Comment by jlahoda** [comment]
I've originally forgot to cleanup the build.xml. I've updated the pull request with the cleanup now.

**Comment by mcdonnell-john** [comment]
@matthiasblaesing I've checked out the PR and it builds fine on my machine.

After running it I've not seen any issues with the menu.  Been able to open projects.  Look at the about dialog, etc. and in general, all menus seem to be working the same as they do on 8.2.

Any specific checks you want me to perform?

**Comment by matthiasblaesing** [comment]
@mcdonnell-john thank you for having a look - this was what I wanted to have ensured. Call it quick-test or smoke test, just to make sure the functions work in general. For me this is good to go in.

**Comment by jlahoda** [comment]
Merged:
https://git-wip-us.apache.org/repos/asf?p=incubator-netbeans.git;a=commit;h=56c952886e51619183a234ffcd7738910de5f31f

Thanks for the comments/testing.

**Pull request closed without merging**
