### PR TITLE
#269262 - [Regression] The editor screen is not scrolled with a keyboard after Japanese strings are input using IME

### PR DESCRIPTION
**Pull request by junichi11**
https://netbeans.org/bugzilla/show_bug.cgi?id=269262

I reported this issue one year ago. Then I attached a patch. Unfortunately, it is not applied yet.
This is a fatal problem for IME users. So, I hope that this is reviewed and merged before NetBeans 9.0 is released.

Thanks.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I tested this and it looks as if it does what i promises. What I did:

- I installed a simulation IME (CityIM.jar from http://javadesktop.org/articles/InputMethod/ )
- I ran the 9.0-dev IDE with the IM, but without the patch and could reproduce the problem
- I switched to the fix branch, rebuild and tested again
- The IDE reacted correctly (scrolling was possible after invoking the IME)

I'm not sure whether I want to merge this without more background knowledge about the inner workings. So it would be good if someone with some more background in the field of input handling could have a look.

Just based on testing this is a +1 from me.

**Comment by junichi11** [comment]
@matthiasblaesing Thanks a lot for looking at it!

It would be nice if Oracle's NetBeans developers can look at this.

**Comment by vieiro** [comment]
Hi @junichi11 ,
Do you use this in a daily basis? I'm sure you do.
If so let's commit this and move on.

**Comment by junichi11** [comment]
Hi @vieiro ,

Currently, I don't use this patch. But I'm providing a jar file applied this patch for Japanese users in NetBeans 8.2 via my blog. (Because this issue was not fixed in hg.netbeans repository.) One person of them said, "I'm using it for one and a half months but it seems that there is no problem." [1]

Once merge this, then if there is some problem, just revert this?

[1] https://twitter.com/shinsan68k/status/893680193075789824 (Japanese, sorry)

**Comment by vieiro** [comment]
Hi @junichi11 @matthiasblaesing  
Users have been using this for a month and a half without issues. I think we should commit this, because "this is a fatal problem for IME users" and so that it enters the 9 Beta. That way we can benefit of the NetCAT testing process.
Cheers,
Antonio

**Comment by geertjanw** [comment]
OK, merging.

**Comment by junichi11** [comment]
@vieiro @geertjanw Thanks a lot for your help! IME users will be happy!

**Comment by vieiro** [comment]
Thank you, @junichi11 !
If IME users are happy this is because of you!
Kind regards,
Antonio

**Pull request merged**
