### PR TITLE
Use FIX_redundantConditional for the fix description

### PR DESCRIPTION
**Pull request by dtrebbien**

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @dtrebbien,
I'm adding the "work in progress" label to this PR, as you keep on submitting commits. You may want to squash these commits together once you're done.
I've also added the "Cosmetics" label as these commits are merely cosmetic and don't seem to solve any real user problem.
Thanks,
Antonio

**Comment by dtrebbien** [comment]
Hello @vieiro,

I am done adding commits; the "work-in-progress" label can be removed.

Also, the first commit fixes a real issue. The FIX_redundantConditional message string should be used as the description of the fix. Otherwise, it's confusing that the fix is also described as "The conditional statement is redundant"; it makes it seem like a fix is not available unless the user remembers that when a fix is not available, the context menu item is "Configure 'The conditional statement is redundant' Hint".

**Comment by dtrebbien** [comment]
NOI18N added and commits squashed.

**Comment by matthiasblaesing** [comment]
Merged - thank you.

**Pull request merged**
