### PR TITLE
Making Maven projects usable without properly installed Java support.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Avoid following error: java.lang.NoClassDefFoundError: com/sun/source/tree/DirectiveTree
    at org.netbeans.modules.maven.nodes.DependenciesNode$DependenciesSet.<init>(:183)
    at org.netbeans.modules.maven.nodes.DependenciesNodeFactory$NList.<init>(:57)
    at org.netbeans.modules.maven.nodes.DependenciesNodeFactory.createNodes(:44)
    at org.netbeans.spi.project.ui.support.NodeFactorySupport$DelegateChildren$1.run(:174)

### CODE REVIEW

**Comment by jlahoda** [comment]
Thanks for looking at this, Jarda. A question though: would synthesizing the interface help the class to link? There is already code that does that in "java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java". Keeping this stuff on one place would help to drop all the workaround when we stop supporting JDK 8. (And may also help other features that would run to this problem.)

**Comment by matthiasblaesing** [comment]
This is tracked as jira issue [[NETBEANS-258]](https://issues.apache.org/jira/browse/NETBEANS-258). The fix works, but Jan has a point for long term considerations.

**Comment by JaroslavTulach** [comment]
Re. `NoJavacHelper.java` - yes, it seems better to have a `hasWorkingJavac` method, than putting the names of classes all around the code base. On the other hand, this is not what my patch does. It just catches `LinkageError`. This kind of `try/catch` code is hard to put into a centralized place, right?

**Comment by jlahoda** [comment]
@JaroslavTulach, please note that I didn't ask to use the hasWorkingJavac method, or a centralized place to put try-catch (LinkageError). I asked if *synthesizing* the interface would help. And, indeed, it appears it would:
---
diff --git a/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java b/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java                                                                 
index d60f6a8..4d45f8a 100644                                                                                                                                                                                                    
--- a/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java                                                                                                                                                   
+++ b/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java                                                                                                                                                   
@@ -19,6 +19,7 @@                                                                                                                                                                                                                
 package org.netbeans.modules.java.source;                                                                                                                                                                                       
                                                                                                                                                                                                                                 
 import java.lang.reflect.Field;                                                                                                                                                                                                 
+import java.util.Arrays;                                                                                                                                                                                                        
 import java.util.logging.Level;                                                                                                                                                                                                 
 import java.util.logging.Logger;                                                                                                                                                                                                
 import org.objectweb.asm.ClassWriter;                                                                                                                                                                                           
@@ -71,6 +72,25 @@ public class NoJavacHelper {                                                                                                                                                                                  
                     //ignore...                                                                                                                                                                                                 
                     Logger.getLogger(NoJavacHelper.class.getName()).log(Level.FINE, null, t);                                                                                                                                   
                 }                                                                                                                                                                                                               
+                synthetizeEmptyInterface("com.sun.source.tree.DirectiveTree", "com.sun.source.tree.Tree");                                                                                                                      
+                synthetizeEmptyInterface("com.sun.source.tree.RequiresTree", "com.sun.source.tree.DirectiveTree");                                                                                                              
+            }                                                                                                                                                                                                                   
+        }                                                                                                                                                                                                                       
+                                                                                                                                                                                                                                
+        private void synthetizeEmptyInterface(String intf, String... superInterfaces) {                                                                                                                                         
+            ClassWriter w = new ClassWriter(0);                                                                                                                                                                                 
+            w.visit(Opcodes.V1_8, Opcodes.ACC_ABSTRACT | Opcodes.ACC_INTERFACE | Opcodes.ACC_PUBLIC, intf.replace('.', '/'), null, "java/lang/Object", Arrays.stream(superInterfaces).map(n -> n.replace('.', '/')).toArray(s -> new String[s]));                                                                                                                                                                                                                
+            byte[] classData = w.toByteArray();                                                                                                                                                                                 
+            try {                                                                                                                                                                                                               
+                Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");                                                                                                                                                   
+                theUnsafe.setAccessible(true);
+                Unsafe unsafe = (Unsafe) theUnsafe.get(null);
+                Class scopeClass = Class.forName(superInterfaces[0]);
+                unsafe.defineClass(intf, classData, 0, classData.length, scopeClass.getClassLoader(), scopeClass.getProtectionDomain());
+            } catch (Throwable t) {
+                t.printStackTrace();
+                //ignore...
+                Logger.getLogger(NoJavacHelper.class.getName()).log(Level.FINE, null, t);
             }
         }
 
---

I guess I don't see how scattering catches for LinkageErrors around the codebase is better than having a centralized place where all the needed stuff is injected. What exactly is the process to remove all the catches? Or will we just leave them in forever masking any LinkageErrors whether related to this or not?

**Comment by JaroslavTulach** [comment]
This is the first time I hear about NetBeans using "synthesizing". I apologize for misunderstanding. Feel free to do whatever you want with my integration.

**Pull request merged**
