### PR TITLE
[NETBEANS-162] Restore autoupdate.services tests

### PR DESCRIPTION
**Pull request by steffendietz**
I restored the tests which were deleted during the first couple of turbulent days after the initial donation.

After that I tried to recreate the test assets which weren't donated by Oracle by looking at the failing and erroneous tests.

I'm currently at 111/112 (99,11%) passing tests but could need some help with the last one.

https://github.com/steffendietz/incubator-netbeans/blob/834579c799e4a3957111fde9bdfc2276d80628a6/autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/UpdateUnitFactoryTest.java#L144

It seems, the test wants to prove, that some of the installed modules have updates in the created `UpdateProvider`. - If anyone has some helpful pointers, that would be great.

### CODE REVIEW

**Comment by geertjanw** [comment]
Very interesting, thanks, will review.

**Comment by steffendietz** [comment]
I found and fixed another test which was not run on Windows systems.

Any progress on the review? Or some pointers from the other contributors how I could fix `UpdateUnitFactoryTest.testGroupInstalledAndUpdates()`? :) - Any help would be appreciated.

In any case, the current tests should be more complete, than what we have now. :+1:

**Comment by steffendietz** [comment]
To fix `UpdateUnitFactoryTest.testGroupInstalledAndUpdates` I now provided an UpdateCenter XML which contains a bogus update entry for one of the installed modules (`org.openide.io`) with an absurdly high specification version of `1000.0`. - If this is not the intended fix, please let me know. :relaxed: 

We now have 100% passing tests `autoupdate.services` package. :tada:

**Comment by geertjanw** [comment]
Great, thanks for your work on this. Is there any specific part of this that needs more review than another part, i.e., or are you very confident that this is all good?

**Comment by steffendietz** [comment]
The tests were fixed by only reverse engineering the missing assets and the use
cases they try to simulate. So I'm pretty confident that this is fine for now.

However, two of the cases could probably need a more subject-specific review, although
it could also happen after the merge, by opening a "reminder" ticket of sorts.

1. The `ExecutablePermissionsTest` checks if there is a `bin` directory with an
executable `start.sh` in the user directory, after installing the `executable-permissions` NBM. 

    I'm currently using an installer in the NBM to create this file and make it executable.
While this works, I'm not sure if this quite captures the essence of the test, or
if it tries to verify some NBM specific behavior, like specifying an executable file
in the manifest. (I could not find anything about this, that's why I went with the installer.)

2. The `UpdateUnitFactoryTest.testGroupInstalledAndUpdates` test checks whether one of the installed modules has an update available in the `test-updates-provider` created in the test.

     The problem I had here is, that there is no test module installed at this point, only real
modules, with correct specification versions. I couldn't think of a clean way to always provide
an update, if the specification version of the installed modules could *someday* exceed
the version available in the static update provider.

    I still haven't figured this out, but I'm now providing an update with an absurdly
high specification version, as mentioned [above](#issuecomment-346498142).

Besides these minor gripes I have, everything should be fine. 👍

**Comment by steffendietz** [comment]
I revisited point 1 from [above](#issuecomment-346595065). I'm now using the correct method of providing an executable file list by using the `nbm.executable.files` property.

I also opened a JIRA issue regarding this change, but couldn't link it on the Confluence page.

**Comment by steffendietz** [comment]
Is there something I can do further to get this merged? - It is ready to go from my perspective.

**Comment by geertjanw** [comment]
From my point of view, makes sense, and am merging.

**Pull request merged**
