### PR TITLE
[NETBEANS-491] hide progress bar from Report Problem dialog

### PR DESCRIPTION
**Pull request by rtaneja1**
Also reduced the height of dialog as there was some empty space between text displayed and buttons below.

### CODE REVIEW

**Comment by jkovalsky** [comment]
Why don't we simply comment out `jpb.setVisible(true);` at line 2380 or remove the `jpb` declaration completely? Do we need that progress bar for anything now that we don't communicate with any NetBeans Statistics server?

**Comment by rtaneja1** [comment]
https://issues.apache.org/jira/secure/attachment/12922249/before_report_problem.png
When we click on Review and Report Problem button, above dialog is displayed with progress bar before either error page or exception report UI is displayed (based on whether there's a submit button in form on the page pointed by ERROR_URL.) This progress bar is required for above dialog.

**Comment by jkovalsky** [comment]
OK, if the progress bar shows progress when connecting to the ERROR_URL it probably makes sense.

**Comment by geertjanw** [comment]
Thanks, merging.

**Pull request merged**
