### PR TITLE
[NETBEANS-318] use external file for rat exclusions

### PR DESCRIPTION
**Pull request by ebarboni**
reorder by theme, 
line starting with hash (#) are considered as pattern by ant
line need to be trimmed

### CODE REVIEW

**Comment by geertjanw** [comment]
Fantastic! I

**Comment by geertjanw** [comment]
I think one more addition could be to add a URL to each category, with the URL pointing to the related Apache guidelines for more details.

**Comment by jlahoda** [comment]
Seems fine, I think. I skimmed through the exclusions, and I think some would be better on some other places (e.g. have "*/test/{unit,qa-functional}/data" as "test data"), so I think fine to integrate, and then we can reorder/fix as needed.

**Comment by JaroslavTulach** [comment]
+1

**Comment by geertjanw** [comment]
OK, merging, many thanks for doing this, @ebarboni. You are definitely the Rat master.

**Pull request merged**
