### PR TITLE
NETBEANS-896 Added missing nullcheck on JCTree.ErrorneousTree

### PR DESCRIPTION
**Pull request by lkishalmi**

### CODE REVIEW

**Comment by lkishalmi** [comment]
Would somebody check and merge this one. It potentially prevents the IDE log pumped with NPE-s when nb-javac is not installed. This shall be cherry picked into release90 branch as well.

**Comment by geertjanw** [comment]
+1 Makes sense to me.

**Comment by matthiasblaesing** [comment]
Looks sane to me too. The NULL check is safe in any case and should not be harmful to performance. I'll merge and also cherry-pick this into release90.

**Comment by matthiasblaesing** [comment]
I cherry-picked the changeset into release90 and ran it through the quick-tests manually. That came back cleanly, so it was pushed.

**Pull request merged**
