### PR TITLE
[NETBEANS-54] Module Review css.lib

### PR DESCRIPTION
**Pull request by rosslamont**
Added or replaced licenses:

- CssTokenId.java
- NoteType.java
- TokenAcceptorsTest.java
- itabbar.css.testfile
- all css files in unit tests

Still todo:
 - antlrv4.patch (not sure what to do here)
 - .txt data files (central solution)

### CODE REVIEW

**Comment by geertjanw** [comment]
Looks great and makes sense not to do anything with that patch and .txt data file. Thanks for this review, great.

**Comment by matthiasblaesing** [comment]
Sorry, but this breaks the unittests. In these the CSS structure is parsed and the result is compared with a reference file. I would do this:

- revert the changes to the files under `css.lib/test/unit/data`
- add an exclusion pattern to the rat report task in the `nbbuild/build.xml` with the pattern `css.lib/test/unit/data/**` with a comment, that these are testdata files

It would be nice if you could have another look at this.

**Comment by rosslamont** [comment]
My apologies, I assumed tests were part of the default build.  Curious: shouldn't travis be running unit tests and picking that up?

I will revert the test changes and look into the rat exclusion.

**Comment by rosslamont** [comment]
Done.

**Comment by rosslamont** [comment]
Sorry - should I also add the patch to the rat exclusions? What would the comment be?

**Comment by matthiasblaesing** [comment]
Sorry! I overlooked the patch case. I did not know it yet, but you can add comments to diff patches:

https://stackoverflow.com/questions/18979120/is-it-possible-to-add-a-comment-to-a-diff-file-unified

So I suggest to just add an ALv2 header to the file.

With regard to the squash question: Please do so, this way the atomic change is contained in one commit.

**Comment by rosslamont** [comment]
All done.  Ready to merge.

**Comment by matthiasblaesing** [comment]
Agreed and merged.

**Pull request closed without merging**
