### PR TITLE
[NETBEANS-586]: NPE findUsages

### PR DESCRIPTION
**Pull request by rtaneja1**
Without nb-javac, workingCopy.getTrees().getTree(c) returns null for nested anonymous class constructor. Added null check.
This change is to avoid:
java.lang.NullPointerException
at org.netbeans.modules.refactoring.java.plugins.FindUsagesVisitor.visitNewClass(FindUsagesVisitor.java:402)
at org.netbeans.modules.refactoring.java.plugins.FindUsagesVisitor.visitNewClass(FindUsagesVisitor.java:54)
at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1711)
at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java

### CODE REVIEW

**Comment by jlahoda** [comment]
So, this will mean some usages won't be found (more or less silently), which does not feel right. I tried a few simple cases (including the platform/core.multitabs), although on a dev build of JDK 12, and didn't see the problem. So I wonder what is the reproducible testcase, so that we can find out what's the issue.

I believe it should be possible to re-write the search for the constructor to only work over trees (basically, do classTree.getMembers() and search for the constructor); it might be tricky to determine which of the members is the constructor, but should be possible. (TreeUtilities.isSynthetic in the worst case). Besides for potentially fixing this bug, it might also be somewhat faster.

**Comment by rtaneja1** [comment]
It's reproducible for nested anonymous class constructor
Like in AbstractTabDisplayer: 
 fullPathListener = new ChangeListener() {
            @Override
            public void stateChanged( ChangeEvent e ) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        updateFullPath();
                    }
                });
            }
        };

 [exec] FindUsages cannot resolve
     [exec] class  implements Runnable {
     [exec]
     [exec]     () {
     [exec]         super();
     [exec]     }
     [exec]
     [exec]     @Override()
     [exec]     public void run() {
     [exec]         updateFullPath();
     [exec]     }
     [exec] } ()

This is not reproducible with jdk-12.
I can try the suggested alternative approach.

**Comment by rtaneja1** [comment]
Hi Jan, Modified code as suggested. Since issue is only reproducible using jdk, didn't add test as tests use nb-javac. Also not sure when addUsages on line 402 gets called. So here we are inside anonymous class constructor(generated), workingCopy.getTreeUtilities().isSynthetic(superCall) is always true. The exact reproducible code is below: Find usages for constructor A() fails with npe without this change: 

public class Test {
    void m() {
        Runnable r = new Runnable() {
            public void run() {
                B b = new B() {
                    void test() {
                        System.out.println("testB");
                    }
                };
            }
        };
    }
    class A {
        public A() {
        }
        void test() {
        }
    }
    class B extends A {
    }
}

**Comment by rtaneja1** [comment]
Thanks Jan, Merging.

**Pull request merged**
