### PR TITLE
[NETBEANS-1613] Fix for 'Select in Project' having no effect in JavaSE Modular Projects

### PR DESCRIPTION
**Pull request by peedeeboy**
Creating an implementation of PathFinder as an inner class of MultiModuleNodeFactory, called ModulePathFinder.  This is registered in the lookup of the ModuleNode class when it is created.

As there is nothing to lookup in ModuleNode, this class delegates down to its children to check if the target is one of their source files / library files.

Have tried to keep coding standards as close as possible to original Class author's.

### CODE REVIEW

**Comment by geertjanw** [comment]
Great, thanks for the PR. Appears to be a problem with the build of this issue, can you check?

**Comment by matthiasblaesing** [comment]
You are right, the travis builds relied on an EA version of JDK 12, that is not available anymore. This was fixed in recent commits. I suggest, that you
- update your master branch to the repository version
- rebase your NETBEANS-1613 branch onto master
- force push the updated changeset

that way you will pick up the changes.

**Comment by peedeeboy** [comment]
Great!  Thanks Matthias :)  Building successfully now... apologies for the mess I've made of the history of this PR and #1090 to get to this stage! :(

**Comment by matthiasblaesing** [comment]
The fix works, it is minimally invasive and if a better solution is found, can be easily removed. Build is clean, so merging this.

Please note: I'll let github squash this (reducing it to one commit), as this matches what you intended.

For the future, this might be interesting to you: https://git-scm.com/book/de/v1/Git-Branching-Rebasing rebasing can result in cleaner PR (at the price of history rewriting), not everyone likes it, so take it with a grain of salt.

Thank you.

**Pull request merged**
