### PR TITLE
CSS changes to improve HTML ui LAF on Windows

### PR DESCRIPTION
**Pull request by dukescript**
Change fort to tahoma and align radiobuttons with label

### CODE REVIEW

**Comment by geertjanw** [comment]
Looks good!

**Comment by geertjanw** [comment]
Any reason not to merge?

**Comment by jtulach** [comment]
+1

**Comment by neilcsmith-net** [comment]
+1, although longer term if we have more of these UI's, might be good to look at generating some of this from the look and feel info?

Incidentally, there is a squash and merge action for PR's in the GitHub UI.

**Comment by geertjanw** [comment]
OK, makes sense, squashing and merging.

**Pull request merged**
