### PR TITLE
[NETBEANS-54] adding license headers to various files in nbbuild

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by geertjanw** [comment]
Thanks a lot for the review!

**Comment by geertjanw** [comment]
Is there a way to integrate your changes via GitHub -- or must I manually rework the code in my fork and then push?

**Comment by matthiasblaesing** [comment]
@geertjanw for this small change this workflow is overkill, but its good to try :-)

I pushed my change into a branch in my repository (branch PR227-update):

https://github.com/matthiasblaesing/incubator-netbeans.git

You can pull my changes with:

```
git pull https://github.com/matthiasblaesing/incubator-netbeans.git PR227-update
```

As I used your commits unmodified a fast-forward merge will be done. After the merge one other unittest will fail, that failure is not caused by this changeset and already fixed in master.

**Comment by geertjanw** [comment]
I think it worked.

**Comment by matthiasblaesing** [comment]
Thanks - build looks good, unittests work correctly - feel free to merge.

**Comment by geertjanw** [comment]
Great, merging.

**Pull request merged**
