### PR TITLE
Multiple maven repository support 

### PR DESCRIPTION
**Pull request by vieiro**
- Modified DownloadBinaries.java to use an eclipse// prefix in a maven coordinate.
	- Added a maven coordinate to the netbinox module.

This PR is currently experimental, just for review.

### CODE REVIEW

**Comment by vieiro** [comment]
Alternate maven repositories can now be defined in nbbuild/default-properties.xml#binaries.repositories

**Comment by geertjanw** [comment]
+1 to me, looks good, makes sense.

**Comment by vieiro** [comment]
Maybe we want to hold on this one, until the "release reviewers" define/state binary download strategies.

**Comment by vieiro** [comment]
D'oh. I deleted this branch by accident. Sorry. Restored it now.
I think we should keep this closed until we decide where to host binaries. Maven central seems to be working fine.

**Pull request closed without merging**
