### PR TITLE
[NETBEANS-1161] Move java modules to java subdirectory

### PR DESCRIPTION
**Pull request by ralphbenjamin**

### CODE REVIEW

**Comment by ralphbenjamin** [comment]
Thanks @geertjanw! But before I pickup anything else, it seems from the build I'm not done yet with the java cluster :-)

**Comment by mcdonnell-john** [comment]
This might be what's wrong with my 2 prs will take a look tonight

**Comment by geertjanw** [comment]
If this results in the build succeeding, should we merge this pr, or is there more to be done here?

**Comment by geertjanw** [comment]
OK, everything is green, great job, any reason not to merge this?

**Comment by ralphbenjamin** [comment]
@geertjanw I think someone should review the commits before merging.

**Comment by geertjanw** [comment]
What specifically would you like to be reviewed, which parts are you most unsure about?

**Comment by geertjanw** [comment]
Awesome, merging this.

**Pull request merged**
