### PR TITLE
[NETBEANS-54] Module Review api.annotations.common

### PR DESCRIPTION
**Pull request by dschoorl**
- external library: jsr305. pom file states AL-v2.0, however, 
  jsr305-license.txt states 'New BSD license'. Assuming AL-v2.0, 
  removing license file, no notice necessary. Maven coordinates added. 

- checked Rat report; changed/added license headers in 3 files: 
  external/binaries-list and apichanges.xml + one file located under 
  META-INF/services, but maybe the latter does not need a license header?

- skimmed through the module, did not notice additional problems

### CODE REVIEW

**Comment by jlahoda** [comment]
I am afraid the license here is a little bit more complex. I think the license is probably BSD, at least based on FindBugs:
https://github.com/findbugsproject/findbugs/blob/master/findbugs/licenses/LICENSE-jsr305.txt

(Its not clear where the Apache license note comes from, but it is probably not correct.)

Also, the file contains some re-packaged annotations from net.jcip.annotations, so these are presumably under:
https://github.com/findbugsproject/findbugs/blob/master/findbugs/licenses/LICENSE-jcip.txt

So we probably need a license file with these both and maybe even a -notice.txt.

The good thing on this particular place is that we only need this file for building.

The license file should be present even if the license would be Apache.

Otherwise, looks OK.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dschoorl** [comment]
Thanks Jan. I restored the jsr305 license and added a jcip license. I updated license header files according to latest insights on Rat exclusions (files that don need a license header). I think a NOTICE should be at the project's top level, so this is outside the scope of this module review.

Is this alright now?

**Comment by jlahoda** [comment]
Hi Dave,

Sorry for belated answer.

I think the jcip license text should be merged into the existing -license.txt file. Also the "License: " tag should probably be changed to something else than "New BSD" (e.g. "BSD+jcip"). Even if though this is probably not ever going to be used.

For notice - I suspect we will need different notices, one at the top level of the repository for things that are in the repository (which this is not), and a different one for binary builds (where the notice should contain exactly what is in the binary, not more, not less, in other words, this will probably differ between the platform and the Java IDE). And there needs to be enough data to construct such notices automatically, I don't think it is realistic to maintain them manually. Hence the request to add -notice.txt to external binaries if needed, so the build will be able to pick them up if needed. But it is not quite clear to me if anything like that is needed for this library.

**Comment by dschoorl** [comment]
Hi Jan,

Thanks for reviewing again.

In no way, I am a legal expert. But I think that by providing the jcip-license.txt file, we meet the requirements of the license stated in article 4b (https://creativecommons.org/licenses/by/2.5/legalcode) and I think no notice is needed? Why do you think needs the jcip license text be merged in the jsr305 one? I believe this is also not done by the findbugs-community who repackaged it with jsr305.jar.

Are these -license.txt files somehow processed automatically and do they need a certain structure, such as having a License-tag? Is that described somewhere?

**Comment by jlahoda** [comment]
Description of the current -license.txt processing is here:
http://wiki.netbeans.org/DevFaqExternalLibraries

I think details under Apache are still somewhat unclear, but I think maintaining -license.txt and -notice.txt (if needed) in the library wrapper near the external library is much more maintainable than trying to have a central registry, and that whatever we do will be based on the current design/state. So, I think it would be good to have things prepared for automatic processing as much as possible.

Thanks.

**Comment by dschoorl** [comment]
I added notice file for jcip-annotations instead of a jcip-license file. I changed the jsr305 license file based on the info in http://wiki.netbeans.org/DevFaqExternalLibraries as pointed out by Jan.

Unfortunately, the checksum of the artifact at the maven coordinates differs from the original download. The META-INF says it's build with a different JRE version. I have not thoroughly checked the contents of the maven download.

**Comment by geertjanw** [comment]
Is anything more needed to be done here or can this one be merged?

**Comment by matthiasblaesing** [comment]
Merged - thank you!

**Pull request closed without merging**
