### PR TITLE
[NETBEANS-54] Module Review profiler.j2se

### PR DESCRIPTION
**Pull request by varaghar**

### CODE REVIEW

**Comment by junichi11** [comment]
Probably, you should send your PR to not `apache:master` but `emilianbold:master`.

The commit message must be `[NETBEANS-54] Module Review <module name>`. In your case, `[NETBEANS-54] Module Review profiler.j2se`

**Comment by varaghar** [comment]
Thank you for the response, I will update this.

**Comment by junichi11** [comment]
@varaghar If you come from @emilianbold 's repo (https://github.com/emilianbold/incubator-netbeans), please send your PR there. i.e. not `apache:master` but `emilianbold:master`.

**Comment by matthiasblaesing** [comment]
@varaghar sorry - the fix for this file was merged via a bigger changeset, that tackled to problem for all build.xml files. Would you please close this PR? Thank you!

**Pull request closed without merging**
