### PR TITLE
[NETBEANS-620] Profiling SQL queries doesn't work under JDK 10

### PR DESCRIPTION
**Pull request by svenreimers**
This is a small non intrusive fix to the multiple class loader problem described in the issue.

### CODE REVIEW

**Comment by svenreimers** [comment]
Debugging through the code I recognized that during updating the ClassRepository for the JDK10 based profiled app I got two versions of the interfaces (java.sql.Statement and java.sql.Connection). Now during lookup if a class is a subclass the wrong instance was selected (not the one updated with the correct information about subclasses but the one with no information updated). This resulted in nor profiling informations recorded since the relevant filter was never true.

I assume there may be more problems below the surface but this will take more time and a bigger change, so I just tried to fix this in a very local manner not affecting any other stuff in the core profiling library.

**Comment by geertjanw** [comment]
Happy to merge if we’re happy with this?

**Comment by geertjanw** [comment]
Will merge 24 hours from now unless there are objections. Many thanks for identifying and fixing this, Sven.

**Comment by geertjanw** [comment]
OK, merging.

**Pull request merged**
