### PR TITLE
create a librarywrapper on jaxws-api to permit usage of Holder class 

### PR DESCRIPTION
**Pull request by ebarboni**
a step toward compiling on jdk 11

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I think you are looking for `websvc.jaxws21` and `websvc.jaxws21api`. JAXWS is already packaged.

**Comment by ebarboni** [comment]
@matthiasblaesing, the cluster java depends on cluster ide. websvc is in java cluster but it would be needed in ide cluster for build. 
Should we relocate websvc to ide cluster.

**Comment by matthiasblaesing** [comment]
@ebarboni the idea sounds reasonable, but I'm not that experienced with the netbeans module structure, that I can advise on that. Please raise it on the mailing list. Thank you.

**Comment by matthiasblaesing** [comment]
@ebarboni I just reread the commit message - is this only for the benefit of the DB module? If so, we can easily work around that by using single element arrays? I'll try to come up with a proposal.

**Comment by ebarboni** [comment]
this is done by #833

**Pull request closed without merging**
