### PR TITLE
[NETBEANS-1074] Module Review php.atoum

### PR DESCRIPTION
**Pull request by junichi11**
- Change the license header of Bundle.properties
- Add licenseinfo.xml
- Fix a unit test because the license headers are changed, then the line counts are changed

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
In general looks good - I would however ask you not to add rat excludes, but use the "licenseinfo.xml" facitlity to declare the license for the file without modifying it. Please have a look at:

`xsl/licenseinfo.xml`

I think that should cover your usecase. The benefit is, that in the end the file can be traced to the license info and the rat exclusion is modular.

**Comment by junichi11** [comment]
@matthiasblaesing Thank you for it :) I'll fix it. Should we also add image files there?

**Comment by matthiasblaesing** [comment]
@junichi11 that would be great - it was for example done in: `/languages/licenseinfo.xml`

**Comment by junichi11** [comment]
@matthiasblaesing OK, I see. I'll also do that :) Thanks!

**Comment by junichi11** [comment]
@matthiasblaesing I've added the below to [2nd Donation: List of Modules to Review](https://cwiki.apache.org/confluence/display/NETBEANS/2nd+Donation%3A+List+of+Modules+to+Review)

"Please add a licenseinfo.xml instead of excluding from the rat-exclusion.txt. (e.g. see xsl/licenseinfo.xml)"

**Comment by thilina01** [comment]
Nice conversation to understand the relicensing process :+1:

**Pull request merged**
