### PR TITLE
[NETBEANS-1074] Relicensing form files in enterprise and ergonomics clusters

### PR DESCRIPTION
**Pull request by geertjanw**
348 files changed, 7308 insertions, specifically and only in the enterprise cluster, and 3 files changed, 63 insertions, specifically and only in the ergonomics cluster, i.e., everything listed here related to form files in the enterprise and ergonomics clusters: https://builds.apache.org/job/incubator-netbeans-linux/lastCompletedBuild/testReport/

### CODE REVIEW

**Comment by geertjanw** [comment]
Somehow Travis failed, does someone know why?

**Comment by junichi11** [comment]
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```
Restarted.

**Comment by geertjanw** [comment]
Same problem as before?

**Comment by geertjanw** [comment]
OK, merging.

**Pull request merged**
